Cancer Cell Agent Simulation: Ciclos_estandares.h File Reference
Ciclos_estandares.h File Reference
Standard cell cycle implementations for cancer simulation modeling.
#include "Constantes.h"
#include "Ciclo_Modelo.h"
#include "Muerte_Parametros.h"
Functions
void Ki67_fase_positiva_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Entry function for the Ki67 positive phase.
void fase_viva_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Entry function for the basic life phase.
void standard_necrosis_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Entry function for the necrosis phase.
void standard_apoptosis_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Entry function for the apoptosis phase.
void standard_lysis_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Entry function for the lysis phase.
bool standard_necrosis_funcion_de_arrest (Volumen &volumen, Muerte_parametros &mp)
Arrest function for the necrosis phase.
bool crear_ciclo_celular_estandar (void)
Creates and initializes standard cell cycles (Ki67, vida)
bool crear_ciclo_de_muerte_estandar (void)
Creates and initializes standard death cycles (necrosis, apoptosis)
Variables
Ciclo_Modelo Ki67
Global cell cycle model instances used throughout the simulation.
Ciclo_Modelo vida
Ciclo_Modelo necrosis
Ciclo_Modelo apoptosis
Muerte_parametros necrosis_parametros
Global death parameter instances used throughout the simulation.
Muerte_parametros apoptosis_parametros
bool ciclo_celular_estandar_inicializado
Flags indicating whether standard cycles have been initialized.
bool ciclo_celular_de_muerte_inicializado
Detailed Description
Standard cell cycle implementations for cancer simulation modeling.
Author
Luciana Melina Luque
This file defines standard cell cycle models that are used in cancer simulations, including proliferative cycles (Ki67, vida/basic life) and death cycles (apoptosis, necrosis). These models are critical for accurately simulating tumor growth dynamics and cell death processes in cancer research.
Inbound Dependencies:
Constantes.h - Defines constants used for cell cycle phases
Ciclo_Modelo.h - Base class for cell cycle models
Muerte_Parametros.h - Parameters for cell death models
Outbound Dependencies:
Main.cpp - Uses these cycles for simulation initialization
Celula.h - Cells use these cycle models for progression
@usage Initialize with crear_ciclo_celular_estandar() and crear_ciclo_de_muerte_estandar()
@license Open Access - Creative Commons Attribution 4.0 International License (http://creativecommons.org/licenses/by/4.0/)
Definition in file Ciclos_estandares.h.
Function Documentation
crear_ciclo_celular_estandar()
bool crear_ciclo_celular_estandar (void)
Creates and initializes standard cell cycles (Ki67, vida)
Initializes proliferative cell cycle models used in the simulation. These cycles model how cancer cells progress through different growth phases, which is essential for tumor growth dynamics research.
Returns
true if initialization was successful, false if already initialized
Creates and initializes standard cell cycles (Ki67, vida)
This function creates and initializes the standard proliferative cell cycles (Ki67 and basic life cycle). It only performs initialization if it hasn't been done already. These cell cycle models are essential for simulating tumor growth dynamics in cancer research.
Returns
true if initialization was successful, false if already initialized
Definition at line 408 of file Ciclos_estandares.cpp.
References ciclo_celular_estandar_inicializado, crear_ciclo_ki67(), and crear_ciclo_vida().
Referenced by main().
crear_ciclo_de_muerte_estandar()
bool crear_ciclo_de_muerte_estandar (void)
Creates and initializes standard death cycles (necrosis, apoptosis)
Initializes cell death models used in the simulation. These cycles model how cancer cells die through different mechanisms, which is crucial for understanding tumor behavior and treatment responses.
Returns
true if initialization was successful, false if already initialized
Creates and initializes standard death cycles (necrosis, apoptosis)
This function creates and initializes the standard cell death cycles (necrosis and apoptosis). It only performs initialization if it hasn't been done already. These death cycle models are crucial for simulating cell death processes in cancer research, including effects of hypoxia and response to therapies.
Returns
true if initialization was successful, false if already initialized
Definition at line 432 of file Ciclos_estandares.cpp.
References ciclo_celular_de_muerte_inicializado, crear_ciclo_apoptosis(), and crear_ciclo_necrosis().
Referenced by main().
fase_viva_funcion_de_entrada()
void fase_viva_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Entry function for the basic life phase.
Called when a cell enters the basic life cycle phase. Sets volume targets for growth during the cell's living phase.
Parameters
volumen Cell's volume parameters that will be modified
mp Death parameters (unused but required by function signature)
Entry function for the basic life phase.
Similar to the Ki67 positive phase, this function doubles volume targets when a cell enters the basic life phase. This is used for simpler cell cycle models where we don't distinguish between different proliferative phases.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters (unused in this function)
Definition at line 58 of file Ciclos_estandares.cpp.
References Volumen::target_citoplasma_solido, and Volumen::target_nucleo_solido.
Referenced by crear_ciclo_vida().
Ki67_fase_positiva_funcion_de_entrada()
void Ki67_fase_positiva_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Entry function for the Ki67 positive phase.
This function is called when a cell enters the Ki67 positive phase of the cell cycle. It adjusts the target volumes to simulate cell growth during proliferation, which is critical for modeling tumor growth dynamics.
Parameters
volumen Cell's volume parameters that will be modified
mp Death parameters (unused but required by function signature)
Entry function for the Ki67 positive phase.
When a cell enters the Ki67 positive phase (indicating proliferation), this function doubles the target volumes for the cell's nucleus and cytoplasm. This simulates the growth process that occurs before cell division, which is a critical aspect of modeling tumor growth rates.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters (unused in this function)
Definition at line 39 of file Ciclos_estandares.cpp.
References Volumen::target_citoplasma_solido, and Volumen::target_nucleo_solido.
Referenced by crear_ciclo_ki67().
standard_apoptosis_funcion_de_entrada()
void standard_apoptosis_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Entry function for the apoptosis phase.
Called when a cell undergoes apoptosis (programmed cell death). Adjusts volume parameters to simulate cell shrinkage during apoptotic death. Critical for modeling therapeutic responses and natural cell turnover in tumors.
Parameters
volumen Cell's volume parameters that will be modified
mp Death parameters used to control the apoptosis process
Entry function for the apoptosis phase.
When a cell undergoes apoptosis (programmed cell death), this function sets volume targets to simulate cellular shrinkage. Apoptosis is a critical process in cancer research as it's often dysregulated in tumors and is a target for many cancer therapies. The function also sets rate parameters for the volume changes based on death parameters.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters that control the rate of volume changes
Definition at line 80 of file Ciclos_estandares.cpp.
References Muerte_parametros::citoplasma_tasa_de_cambio, Volumen::citoplasma_tasa_de_cambio, Volumen::fluido_tasa_de_cambio, Muerte_parametros::nucleo_tasa_de_cambio, Volumen::nucleo_tasa_de_cambio, Volumen::target_citoplasma_solido, Volumen::target_fraccion_fluido, Volumen::target_nucleo_solido, Volumen::target_relacion_citoplasma_nucleo, Muerte_parametros::tasa_de_calcificacion, Volumen::tasa_de_calcificacion, Muerte_parametros::tasa_de_cambio_fluido_lisado, Volumen::total, Volumen::volumen_de_ruptura, Muerte_parametros::volumen_de_ruptura_relativo, and Volumen::volumen_de_ruptura_relativo.
Referenced by crear_ciclo_apoptosis().
standard_lysis_funcion_de_entrada()
void standard_lysis_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Entry function for the lysis phase.
Called when a cell enters the lysed state. Adjusts volume parameters to simulate cellular breakdown after death.
Parameters
volumen Cell's volume parameters that will be modified
mp Death parameters used to control the lysis process
Entry function for the lysis phase.
When a cell enters the lysis phase (final breakdown after death), this function sets volume targets to simulate complete cellular degradation. This phase represents the final fate of dead cells within the tumor microenvironment before they are removed from the simulation.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters that control the rate of volume changes
Definition at line 155 of file Ciclos_estandares.cpp.
References Muerte_parametros::citoplasma_tasa_de_cambio, Volumen::citoplasma_tasa_de_cambio, Volumen::fluido_tasa_de_cambio, Muerte_parametros::nucleo_tasa_de_cambio, Volumen::nucleo_tasa_de_cambio, Volumen::target_citoplasma_solido, Volumen::target_fraccion_fluido, Volumen::target_nucleo_solido, Muerte_parametros::tasa_de_calcificacion, Volumen::tasa_de_calcificacion, Muerte_parametros::tasa_de_cambio_fluido_lisado, Volumen::total, Volumen::volumen_de_ruptura, and Volumen::volumen_de_ruptura_relativo.
Referenced by crear_ciclo_necrosis().
standard_necrosis_funcion_de_arrest()
bool standard_necrosis_funcion_de_arrest (Volumen & volumen, Muerte_parametros & mp)
Arrest function for the necrosis phase.
This function determines whether a necrotic cell should proceed to the next phase. The arrest occurs based on volume thresholds, representing cell bursting.
Parameters
volumen Cell's volume parameters
mp Death parameters
Returns
true if the cell should arrest (not transition), false otherwise
Arrest function for the necrosis phase.
This function checks if a necrotic cell has reached the volume threshold for bursting/rupture. In necrotic cell death, cells typically swell until they rupture, which this function models. This process is relevant for understanding tumor necrotic core formation and related inflammatory responses.
Parameters
volumen The cell's current volume parameters
mp Death parameters (unused in this function)
Returns
true if the cell should remain in current phase, false if it should transition
Definition at line 192 of file Ciclos_estandares.cpp.
References Volumen::total, and Volumen::volumen_de_ruptura.
Referenced by crear_ciclo_necrosis().
standard_necrosis_funcion_de_entrada()
void standard_necrosis_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Entry function for the necrosis phase.
Called when a cell becomes necrotic. Adjusts volume parameters to simulate cell swelling during necrotic death, which occurs in hypoxic/nutrient-deprived regions of tumors.
Parameters
volumen Cell's volume parameters that will be modified
mp Death parameters used to control the necrosis process
Entry function for the necrosis phase.
When a cell becomes necrotic (typically due to hypoxia or nutrient deprivation), this function sets volume targets to simulate cellular swelling that occurs during necrosis. In tumors, necrosis commonly occurs in poorly vascularized regions and is an important indicator of aggressive cancer. The function also sets various rate parameters for the volume changes.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters that control the rate of volume changes
Definition at line 117 of file Ciclos_estandares.cpp.
References Muerte_parametros::citoplasma_tasa_de_cambio, Volumen::citoplasma_tasa_de_cambio, Volumen::fluido_tasa_de_cambio, Muerte_parametros::nucleo_tasa_de_cambio, Volumen::nucleo_tasa_de_cambio, Volumen::target_citoplasma_solido, Volumen::target_fraccion_fluido, Volumen::target_nucleo_solido, Volumen::target_relacion_citoplasma_nucleo, Muerte_parametros::tasa_de_calcificacion, Volumen::tasa_de_calcificacion, Muerte_parametros::tasa_de_cambio_fluido_lisado, Volumen::total, Volumen::volumen_de_ruptura, Muerte_parametros::volumen_de_ruptura_relativo, and Volumen::volumen_de_ruptura_relativo.
Referenced by crear_ciclo_necrosis().
Variable Documentation
apoptosis
Ciclo_Modelo apoptosis
Definition at line 33 of file Ciclos_estandares.h.
apoptosis_parametros
Muerte_parametros apoptosis_parametros
Definition at line 36 of file Ciclos_estandares.h.
ciclo_celular_de_muerte_inicializado
bool ciclo_celular_de_muerte_inicializado extern
Definition at line 97 of file Main.cpp.
Referenced by crear_ciclo_de_muerte_estandar().
ciclo_celular_estandar_inicializado
bool ciclo_celular_estandar_inicializado extern
Flags indicating whether standard cycles have been initialized.
Definition at line 96 of file Main.cpp.
Referenced by crear_ciclo_celular_estandar().
Ki67
Ciclo_Modelo Ki67 extern
Global cell cycle model instances used throughout the simulation.
Definition at line 64 of file Main.cpp.
Referenced by main().
necrosis
Ciclo_Modelo necrosis
Definition at line 33 of file Ciclos_estandares.h.
necrosis_parametros
Muerte_parametros necrosis_parametros extern
Global death parameter instances used throughout the simulation.
Definition at line 65 of file Main.cpp.
vida
Ciclo_Modelo vida
Definition at line 33 of file Ciclos_estandares.h.