Cancer Cell Agent Simulation: Ciclos_estandares.cpp File Reference
Ciclos_estandares.cpp File Reference
Implementation of standard cell cycle models used in cancer simulation.
#include "Ciclos_estandares.h"
Functions
void Ki67_fase_positiva_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Implementation of entry function for Ki67 positive phase.
void fase_viva_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Implementation of entry function for basic life cycle phase.
void standard_apoptosis_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Implementation of entry function for apoptosis phase.
void standard_necrosis_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Implementation of entry function for necrosis phase.
void standard_lysis_funcion_de_entrada (Volumen &volumen, Muerte_parametros &mp)
Implementation of entry function for lysis phase.
bool standard_necrosis_funcion_de_arrest (Volumen &volumen, Muerte_parametros &mp)
Determines if a necrotic cell should transition to the lysed phase.
void crear_ciclo_ki67 (void)
Creates and initializes the Ki67-based cell cycle model.
void crear_ciclo_vida (void)
Creates and initializes the basic life cycle model.
void crear_ciclo_necrosis (void)
Creates and initializes the necrosis death cycle model.
void crear_ciclo_apoptosis (void)
Creates and initializes the apoptosis death cycle model.
bool crear_ciclo_celular_estandar (void)
Creates and initializes all standard cell cycles.
bool crear_ciclo_de_muerte_estandar (void)
Creates and initializes all standard death cycles.
Detailed Description
Implementation of standard cell cycle models used in cancer simulation.
Author
Luciana Melina Luque
This file implements several standard cell cycle models that are fundamental to cancer simulation: Ki67 (based on this proliferation marker), basic life cycle, necrosis (cell death due to nutrient deprivation/hypoxia), and apoptosis (programmed cell death). These models allow simulation of tumor growth dynamics and response to microenvironmental conditions.
Inbound Dependencies:
Ciclos_estandares.h - Function declarations
Volumen.h - Volume calculations for cells
Constantes.h - Phase constants
Outbound Dependencies:
None
@license Open Access - Creative Commons Attribution 4.0 International License (http://creativecommons.org/licenses/by/4.0/)
Definition in file Ciclos_estandares.cpp.
Function Documentation
crear_ciclo_apoptosis()
void crear_ciclo_apoptosis (void)
Creates and initializes the apoptosis death cycle model.
This function initializes the apoptosis model with its parameters and phases. Apoptosis is programmed cell death, characterized by cell shrinkage and fragmentation. It's a crucial process in cancer biology, as many cancers develop mechanisms to evade apoptosis, and many therapies aim to induce it. The model parameters are calibrated to match experimental observations of apoptotic cell death.
Definition at line 357 of file Ciclos_estandares.cpp.
References Ciclo_Modelo::agregar_fase(), Ciclo_Modelo::agregar_link(), apoptosis, apoptosis_parametros, Constantes::apoptotica, Constantes::ciclo_de_muerte_apoptosis, Muerte_parametros::citoplasma_tasa_de_cambio, Ciclo_Modelo::codigo, Constantes::debris, Fase_Link::duracion_fija, Ciclo_Modelo::fase_link(), Ciclo_Modelo::fases, Ciclo_Modelo::nombre, Muerte_parametros::nucleo_tasa_de_cambio, standard_apoptosis_funcion_de_entrada(), Muerte_parametros::tasa_de_calcificacion, Muerte_parametros::tasa_de_cambio_fluido_lisado, Muerte_parametros::tasa_de_cambio_fluido_no_lisado, Ciclo_Modelo::tasa_de_transicion(), Muerte_parametros::tiempo_unidades, and Muerte_parametros::volumen_de_ruptura_relativo.
Referenced by crear_ciclo_de_muerte_estandar().
crear_ciclo_celular_estandar()
bool crear_ciclo_celular_estandar (void)
Creates and initializes all standard cell cycles.
Creates and initializes standard cell cycles (Ki67, vida)
This function creates and initializes the standard proliferative cell cycles (Ki67 and basic life cycle). It only performs initialization if it hasn't been done already. These cell cycle models are essential for simulating tumor growth dynamics in cancer research.
Returns
true if initialization was successful, false if already initialized
Definition at line 408 of file Ciclos_estandares.cpp.
References ciclo_celular_estandar_inicializado, crear_ciclo_ki67(), and crear_ciclo_vida().
Referenced by main().
crear_ciclo_de_muerte_estandar()
bool crear_ciclo_de_muerte_estandar (void)
Creates and initializes all standard death cycles.
Creates and initializes standard death cycles (necrosis, apoptosis)
This function creates and initializes the standard cell death cycles (necrosis and apoptosis). It only performs initialization if it hasn't been done already. These death cycle models are crucial for simulating cell death processes in cancer research, including effects of hypoxia and response to therapies.
Returns
true if initialization was successful, false if already initialized
Definition at line 432 of file Ciclos_estandares.cpp.
References ciclo_celular_de_muerte_inicializado, crear_ciclo_apoptosis(), and crear_ciclo_necrosis().
Referenced by main().
crear_ciclo_ki67()
void crear_ciclo_ki67 (void)
Creates and initializes the Ki67-based cell cycle model.
This function initializes the Ki67 cell cycle model with three phases: Ki67 negative, Ki67 positive pre-mitotic, and Ki67 positive post-mitotic. The model is based on the Ki67 proliferation marker, which is widely used in cancer research to assess tumor growth rates and proliferation indices. It sets phase transition rates based on experimental data from cancer cell lines.
Definition at line 213 of file Ciclos_estandares.cpp.
References Ciclo_Modelo::agregar_fase(), Ciclo_Modelo::agregar_link(), Constantes::ciclo_Ki67, Ciclo_Modelo::codigo, Fase_Link::duracion_fija, Ciclo_Modelo::fase_link(), Ciclo_Modelo::fases, Ki67, Ki67_fase_positiva_funcion_de_entrada(), Constantes::Ki67_negativa, Constantes::Ki67_positiva_postmitotica, Constantes::Ki67_positiva_premitotica, Ciclo_Modelo::nombre, Ciclo_Modelo::tasa_de_transicion(), and Ciclo_Modelo::unidades_tiempo.
Referenced by crear_ciclo_celular_estandar().
crear_ciclo_necrosis()
void crear_ciclo_necrosis (void)
Creates and initializes the necrosis death cycle model.
This function initializes the necrosis model with its parameters and phases. Necrosis is a type of cell death that occurs when cells are deprived of oxygen or nutrients, which is common in the center of rapidly growing tumors. The model includes a swelling phase followed by lysis, with parameters calibrated to match experimental observations of necrotic cell death.
Definition at line 297 of file Ciclos_estandares.cpp.
References Ciclo_Modelo::agregar_fase(), Ciclo_Modelo::agregar_link(), Constantes::ciclo_de_muerte_necrosis, Muerte_parametros::citoplasma_tasa_de_cambio, Ciclo_Modelo::codigo, Constantes::debris, Fase_Link::duracion_fija, Ciclo_Modelo::fase_link(), Ciclo_Modelo::fases, necrosis, necrosis_parametros, Constantes::necrotica_hinchada, Constantes::necrotica_lisada, Ciclo_Modelo::nombre, Muerte_parametros::nucleo_tasa_de_cambio, standard_lysis_funcion_de_entrada(), standard_necrosis_funcion_de_arrest(), standard_necrosis_funcion_de_entrada(), Muerte_parametros::tasa_de_calcificacion, Muerte_parametros::tasa_de_cambio_fluido_lisado, Muerte_parametros::tasa_de_cambio_fluido_no_lisado, Ciclo_Modelo::tasa_de_transicion(), Muerte_parametros::tiempo_unidades, and Muerte_parametros::volumen_de_ruptura_relativo.
Referenced by crear_ciclo_de_muerte_estandar().
crear_ciclo_vida()
void crear_ciclo_vida (void)
Creates and initializes the basic life cycle model.
This function initializes a simplified cell cycle model with just one phase (living). This basic model is useful for simulations where detailed cell cycle phases are not needed. The model's division rate is calibrated to match the net birth rate of MCF10A cells, which are often used as normal breast epithelial cell controls in breast cancer research.
Definition at line 262 of file Ciclos_estandares.cpp.
References Ciclo_Modelo::agregar_fase(), Ciclo_Modelo::agregar_link(), Constantes::ciclo_vida, Ciclo_Modelo::codigo, Fase_Link::duracion_fija, Ciclo_Modelo::fase_link(), fase_viva_funcion_de_entrada(), Ciclo_Modelo::fases, Ciclo_Modelo::nombre, Ciclo_Modelo::tasa_de_transicion(), Ciclo_Modelo::unidades_tiempo, vida, and Constantes::viva.
Referenced by crear_ciclo_celular_estandar().
fase_viva_funcion_de_entrada()
void fase_viva_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Implementation of entry function for basic life cycle phase.
Entry function for the basic life phase.
Similar to the Ki67 positive phase, this function doubles volume targets when a cell enters the basic life phase. This is used for simpler cell cycle models where we don't distinguish between different proliferative phases.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters (unused in this function)
Definition at line 58 of file Ciclos_estandares.cpp.
References Volumen::target_citoplasma_solido, and Volumen::target_nucleo_solido.
Referenced by crear_ciclo_vida().
Ki67_fase_positiva_funcion_de_entrada()
void Ki67_fase_positiva_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Implementation of entry function for Ki67 positive phase.
Entry function for the Ki67 positive phase.
When a cell enters the Ki67 positive phase (indicating proliferation), this function doubles the target volumes for the cell's nucleus and cytoplasm. This simulates the growth process that occurs before cell division, which is a critical aspect of modeling tumor growth rates.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters (unused in this function)
Definition at line 39 of file Ciclos_estandares.cpp.
References Volumen::target_citoplasma_solido, and Volumen::target_nucleo_solido.
Referenced by crear_ciclo_ki67().
standard_apoptosis_funcion_de_entrada()
void standard_apoptosis_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Implementation of entry function for apoptosis phase.
Entry function for the apoptosis phase.
When a cell undergoes apoptosis (programmed cell death), this function sets volume targets to simulate cellular shrinkage. Apoptosis is a critical process in cancer research as it's often dysregulated in tumors and is a target for many cancer therapies. The function also sets rate parameters for the volume changes based on death parameters.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters that control the rate of volume changes
Definition at line 80 of file Ciclos_estandares.cpp.
References Muerte_parametros::citoplasma_tasa_de_cambio, Volumen::citoplasma_tasa_de_cambio, Volumen::fluido_tasa_de_cambio, Muerte_parametros::nucleo_tasa_de_cambio, Volumen::nucleo_tasa_de_cambio, Volumen::target_citoplasma_solido, Volumen::target_fraccion_fluido, Volumen::target_nucleo_solido, Volumen::target_relacion_citoplasma_nucleo, Muerte_parametros::tasa_de_calcificacion, Volumen::tasa_de_calcificacion, Muerte_parametros::tasa_de_cambio_fluido_lisado, Volumen::total, Volumen::volumen_de_ruptura, Muerte_parametros::volumen_de_ruptura_relativo, and Volumen::volumen_de_ruptura_relativo.
Referenced by crear_ciclo_apoptosis().
standard_lysis_funcion_de_entrada()
void standard_lysis_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Implementation of entry function for lysis phase.
Entry function for the lysis phase.
When a cell enters the lysis phase (final breakdown after death), this function sets volume targets to simulate complete cellular degradation. This phase represents the final fate of dead cells within the tumor microenvironment before they are removed from the simulation.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters that control the rate of volume changes
Definition at line 155 of file Ciclos_estandares.cpp.
References Muerte_parametros::citoplasma_tasa_de_cambio, Volumen::citoplasma_tasa_de_cambio, Volumen::fluido_tasa_de_cambio, Muerte_parametros::nucleo_tasa_de_cambio, Volumen::nucleo_tasa_de_cambio, Volumen::target_citoplasma_solido, Volumen::target_fraccion_fluido, Volumen::target_nucleo_solido, Muerte_parametros::tasa_de_calcificacion, Volumen::tasa_de_calcificacion, Muerte_parametros::tasa_de_cambio_fluido_lisado, Volumen::total, Volumen::volumen_de_ruptura, and Volumen::volumen_de_ruptura_relativo.
Referenced by crear_ciclo_necrosis().
standard_necrosis_funcion_de_arrest()
bool standard_necrosis_funcion_de_arrest (Volumen & volumen, Muerte_parametros & mp)
Determines if a necrotic cell should transition to the lysed phase.
Arrest function for the necrosis phase.
This function checks if a necrotic cell has reached the volume threshold for bursting/rupture. In necrotic cell death, cells typically swell until they rupture, which this function models. This process is relevant for understanding tumor necrotic core formation and related inflammatory responses.
Parameters
volumen The cell's current volume parameters
mp Death parameters (unused in this function)
Returns
true if the cell should remain in current phase, false if it should transition
Definition at line 192 of file Ciclos_estandares.cpp.
References Volumen::total, and Volumen::volumen_de_ruptura.
Referenced by crear_ciclo_necrosis().
standard_necrosis_funcion_de_entrada()
void standard_necrosis_funcion_de_entrada (Volumen & volumen, Muerte_parametros & mp)
Implementation of entry function for necrosis phase.
Entry function for the necrosis phase.
When a cell becomes necrotic (typically due to hypoxia or nutrient deprivation), this function sets volume targets to simulate cellular swelling that occurs during necrosis. In tumors, necrosis commonly occurs in poorly vascularized regions and is an important indicator of aggressive cancer. The function also sets various rate parameters for the volume changes.
Parameters
volumen The cell's volume parameters to be modified
mp Death parameters that control the rate of volume changes
Definition at line 117 of file Ciclos_estandares.cpp.
References Muerte_parametros::citoplasma_tasa_de_cambio, Volumen::citoplasma_tasa_de_cambio, Volumen::fluido_tasa_de_cambio, Muerte_parametros::nucleo_tasa_de_cambio, Volumen::nucleo_tasa_de_cambio, Volumen::target_citoplasma_solido, Volumen::target_fraccion_fluido, Volumen::target_nucleo_solido, Volumen::target_relacion_citoplasma_nucleo, Muerte_parametros::tasa_de_calcificacion, Volumen::tasa_de_calcificacion, Muerte_parametros::tasa_de_cambio_fluido_lisado, Volumen::total, Volumen::volumen_de_ruptura, Muerte_parametros::volumen_de_ruptura_relativo, and Volumen::volumen_de_ruptura_relativo.
Referenced by crear_ciclo_necrosis().