Cancer Cell Agent Simulation: Contenedor_de_Celulas Class Reference
Contenedor_de_Celulas Class Reference
Manages collections of cells within the spatial domain.
#include <Contenedor_de_Celulas.h>
Public Member Functions
Contenedor_de_Celulas ()
Default constructor.
void inicializar (double x_ini, double x_fin, double y_ini, double y_fin, double z_ini, double z_fin, double dx, double dy, double dz)
Initializes the spatial domain of the cell container.
void registrar_celula (Celula *celula)
Registers a cell in the container.
void agregar_celula_a_voxel (Celula *celula, int indice_de_voxel)
Adds a cell to a specific voxel.
void actualizar_todas_las_celulas (double tiempo_total, double dt_difusion, double dt_mecanico, double dt_ciclo)
Updates all cells for a simulation step.
bool contiene_alguna_celula (int indice_de_voxel)
Checks if a voxel contains any cells.
void sacar_celula_de_voxel (Celula *celula, int indice_de_voxel)
Removes a cell from a voxel.
void actualizar_voxeles_de_celulas ()
Updates voxel assignments for all cells.
void agregar_potenciales_cdc (Celula *celula, Celula *otra_celula)
Calculates mechanical forces between two cells.
Public Attributes
Grillado_Cartesiano grillado
std::vector< std::vector< Celula * > > celulas_en_voxel
std::vector< std::vector< Celula * > > celulas_fuera_del_domino
int num_de_divisiones_en_este_paso
int num_de_muertes_en_este_paso
int num_de_celulas
double tiempo_desde_la_ultima_mecanica
double hora_de_la_ultima_mecanica
Celula * celula
Detailed Description
Manages collections of cells within the spatial domain.
The cell container class organizes cells in a spatial grid (voxels), handles cell interactions, updates cell states, and manages mechanical forces between cells. It also coordinates cell lifecycle events like division and death.
Cancer Research Context: In cancer modeling, efficient cell organization and interaction handling is critical for simulating tumor growth, cell-cell interactions, and spatial organization. This container enables scaling to large numbers of cells while maintaining computational efficiency.
Definition at line 51 of file Contenedor_de_Celulas.h.
Constructor & Destructor Documentation
Contenedor_de_Celulas()
Contenedor_de_Celulas::Contenedor_de_Celulas ()
Default constructor.
Constructor for the cell container.
Initializes a new cell container with default values.
Initializes a new cell container with default values for tracking mechanical updates and division events. In cancer modeling, proper initialization ensures accurate tracking of tumor growth rates and mechanical interactions.
Definition at line 37 of file Contenedor_de_celulas.cpp.
References hora_de_la_ultima_mecanica, num_de_divisiones_en_este_paso, and tiempo_desde_la_ultima_mecanica.
Member Function Documentation
actualizar_todas_las_celulas()
void Contenedor_de_Celulas::actualizar_todas_las_celulas (double tiempo_total, double dt_difusion, double dt_mecanico, double dt_ciclo)
Updates all cells for a simulation step.
This is a key method that orchestrates the complete update sequence:
Updates cell secretion and consumption
Calculates and applies mechanical forces between cells
Updates cell positions
Advances cell phenotypes (cycle, death, etc.)
Processes division of cells ready to divide
Registers new cells in voxels
Removes cells marked for death
Parameters
tiempo_total Current simulation time
dt_difusion Time step for diffusion
dt_mecanico Time step for mechanics
dt_ciclo Time step for cell cycle
This is a key method that orchestrates the complete update sequence:
Updates cell secretion and consumption
Calculates and applies mechanical forces between cells
Updates cell positions
Advances cell phenotypes (cycle, death, etc.)
Processes division of cells ready to divide
Registers new cells in voxels
Removes cells marked for death
In cancer research, this method drives the entire simulation forward, capturing key tumor behaviors such as:
Tumor growth through cell division
Cell death through various mechanisms
Mechanical interactions within the tumor
Phenotypic evolution of cancer cells
Interaction with the microenvironment
Parameters
tiempo_total Current simulation time
dt_difusion Time step for diffusion
dt_mecanico Time step for mechanics
dt_ciclo Time step for cell cycle
Definition at line 279 of file Contenedor_de_celulas.cpp.
References agregar_potenciales_cdc(), celulas_en_voxel, celulas_listas_para_dividirse, celulas_listas_para_remover, celulas_para_registrar_en_voxeles, grillado, hora_de_la_ultima_mecanica, Grillado_Cartesiano::indices_de_voxeles_conectados_tipo_moore, num_de_divisiones_en_este_paso, num_de_muertes_en_este_paso, registrar_celula(), sacar_celula_de_voxel(), tiempo_desde_la_ultima_mecanica, todas_las_celulas, and Grillado_General::voxeles.
Referenced by main().
actualizar_voxeles_de_celulas()
void Contenedor_de_Celulas::actualizar_voxeles_de_celulas ()
Updates voxel assignments for all cells.
Checks each cell's position and moves it to the correct voxel if it has moved to a different voxel. This is typically called periodically rather than after every position update for efficiency.
Checks each cell's position and moves it to the correct voxel if it has moved to a different voxel. This is typically called periodically rather than after every position update for efficiency.
In cancer modeling, this method ensures proper spatial organization of cells, which is critical for accurate simulation of:
Cell migration through tissue
Tumor invasion into surrounding tissue
Spatial heterogeneity within tumors
Local interactions between cancer and immune cells
Definition at line 518 of file Contenedor_de_celulas.cpp.
References agregar_celula_a_voxel(), Grillado_General::es_valida_la_posicion(), grillado, Grillado_Cartesiano::indice_del_voxel_mas_cercano(), sacar_celula_de_voxel(), and todas_las_celulas.
Referenced by main().
agregar_celula_a_voxel()
void Contenedor_de_Celulas::agregar_celula_a_voxel (Celula * celula, int indice_de_voxel)
Adds a cell to a specific voxel.
Parameters
celula Pointer to the cell to add
indice_de_voxel Index of the voxel to add the cell to
Updates the spatial data structure to include the cell in the specified voxel. Efficient voxel-based organization is critical for cancer simulations as it allows for quick identification of neighboring cells for interaction calculations.
Parameters
celula Pointer to the cell to add
indice_de_voxel Index of the voxel to add the cell to
Definition at line 120 of file Contenedor_de_celulas.cpp.
References celula, and celulas_en_voxel.
Referenced by actualizar_voxeles_de_celulas(), and registrar_celula().
agregar_potenciales_cdc()
void Contenedor_de_Celulas::agregar_potenciales_cdc (Celula * celula, Celula * otra_celula)
Calculates mechanical forces between two cells.
Computes repulsive and adhesive forces between cells based on their distance, size, and mechanical properties. Updates velocity vectors for both cells accordingly.
Parameters
celula Pointer to the first cell
otra_celula Pointer to the second cell
Computes repulsive and adhesive forces between cells based on their distance, size, and mechanical properties. Updates velocity vectors for both cells accordingly.
In cancer research, these mechanical interactions are critical for modeling:
Cell crowding effects in tumors
Differential adhesion hypothesis in tumor organization
Mechanical pressure effects on cancer cell behavior
Tumor compaction and invasion mechanics
Parameters
celula Pointer to the first cell
otra_celula Pointer to the second cell
Definition at line 142 of file Contenedor_de_celulas.cpp.
References celula, Celula::desplazamiento, Mecanica::distancia_de_adhesion_maxima_relativa, Celula::fenotipo, Mecanica::fuerza_de_adhesion_cc, Mecanica::fuerza_de_adhesion_co, Mecanica::fuerza_de_repulsion_cc, Mecanica::fuerza_de_repulsion_co, Fenotipo::geometria, Celula::id, Fenotipo::mecanica, pg, Celula::posicion, Geometria::radio, Parametros_globales::rango_en_X, Parametros_globales::rango_en_Y, Parametros_globales::rango_en_Z, Celula::tipo, Celula::velocidad, Vector::x, Vector::y, and Vector::z.
Referenced by actualizar_todas_las_celulas().
contiene_alguna_celula()
bool Contenedor_de_Celulas::contiene_alguna_celula (int indice_de_voxel)
Checks if a voxel contains any cells.
Parameters
indice_de_voxel Index of the voxel to check
Returns
true if the voxel contains at least one cell, false otherwise
Determines whether the specified voxel contains at least one cell. This is used to optimize mechanical calculations by only processing voxels that contain cells. In cancer simulations, this helps improve performance when modeling sparse regions of the tumor.
Parameters
indice_de_voxel Index of the voxel to check
Returns
true if the voxel contains at least one cell, false otherwise
Definition at line 472 of file Contenedor_de_celulas.cpp.
References celulas_en_voxel.
inicializar()
void Contenedor_de_Celulas::inicializar (double x_ini, double x_fin, double y_ini, double y_fin, double z_ini, double z_fin, double dx, double dy, double dz)
Initializes the spatial domain of the cell container.
Sets up the Cartesian grid with the specified dimensions and creates the data structures needed to track cells within voxels.
Parameters
x_ini Minimum x-coordinate
x_fin Maximum x-coordinate
y_ini Minimum y-coordinate
y_fin Maximum y-coordinate
z_ini Minimum z-coordinate
z_fin Maximum z-coordinate
dx Size of voxel in x-direction
dy Size of voxel in y-direction
dz Size of voxel in z-direction
Sets up the Cartesian grid with the specified dimensions and creates the data structures needed to track cells within voxels. For cancer modeling, this defines the tissue domain within which tumor growth can occur and determines the spatial resolution of the simulation.
Parameters
x_ini Minimum x-coordinate
x_fin Maximum x-coordinate
y_ini Minimum y-coordinate
y_fin Maximum y-coordinate
z_ini Minimum z-coordinate
z_fin Maximum z-coordinate
dx Size of voxel in x-direction
dy Size of voxel in y-direction
dz Size of voxel in z-direction
Definition at line 68 of file Contenedor_de_celulas.cpp.
References celulas_en_voxel, grillado, Grillado_Cartesiano::redimensionar(), v, and Grillado_General::voxeles.
Referenced by Tejido::inicializar_tejido().
registrar_celula()
void Contenedor_de_Celulas::registrar_celula (Celula * celula)
Registers a cell in the container.
Places the cell in the appropriate voxel based on its position. If the position is invalid, the cell is marked as outside the domain.
Parameters
celula Pointer to the cell to register
Places the cell in the appropriate voxel based on its position. If the position is invalid, the cell is marked as outside the domain. This function is essential for maintaining spatial organization in tumor simulations, especially when tracking cells that migrate to different regions of the tissue.
Parameters
celula Pointer to the cell to register
Definition at line 92 of file Contenedor_de_celulas.cpp.
References agregar_celula_a_voxel(), celula, Grillado_General::es_valida_la_posicion(), grillado, Celula::id, Grillado_Cartesiano::indice_del_voxel_mas_cercano(), Celula::posicion, Celula::voxel, Vector::x, Vector::y, and Vector::z.
Referenced by actualizar_todas_las_celulas(), Tejido::inicializar_tejido(), Tejido::introducir_linfocitos(), and Tejido::introducir_linfocitos_aleatorios().
sacar_celula_de_voxel()
void Contenedor_de_Celulas::sacar_celula_de_voxel (Celula * celula, int indice_de_voxel)
Removes a cell from a voxel.
Used when cells move between voxels or when they die.
Parameters
celula Pointer to the cell to remove
indice_de_voxel Index of the voxel containing the cell
Used when cells move between voxels or when they die. The method updates the spatial data structure by removing the reference to the cell from the voxel. In cancer modeling, this is essential for tracking cell migration, division, and death.
Parameters
celula Pointer to the cell to remove
indice_de_voxel Index of the voxel containing the cell
Definition at line 487 of file Contenedor_de_celulas.cpp.
References celula, celulas_en_voxel, and Celula::voxel.
Referenced by actualizar_todas_las_celulas(), and actualizar_voxeles_de_celulas().
Member Data Documentation
celula
Celula* Contenedor_de_Celulas::celula
Definition at line 63 of file Contenedor_de_Celulas.h.
Referenced by agregar_celula_a_voxel(), agregar_potenciales_cdc(), Tejido::crear_esfera_de_celulas(), Tejido::crear_planos_de_celulas_sanas_en_Z(), Tejido::inicializar_tejido(), registrar_celula(), and sacar_celula_de_voxel().
celulas_en_voxel
std::vector<std::vector<Celula*> > Contenedor_de_Celulas::celulas_en_voxel
Definition at line 56 of file Contenedor_de_Celulas.h.
Referenced by actualizar_todas_las_celulas(), agregar_celula_a_voxel(), contiene_alguna_celula(), inicializar(), and sacar_celula_de_voxel().
celulas_fuera_del_domino
std::vector<std::vector<Celula*> > Contenedor_de_Celulas::celulas_fuera_del_domino
Definition at line 57 of file Contenedor_de_Celulas.h.
grillado
Grillado_Cartesiano Contenedor_de_Celulas::grillado
Definition at line 55 of file Contenedor_de_Celulas.h.
Referenced by actualizar_todas_las_celulas(), actualizar_voxeles_de_celulas(), inicializar(), and registrar_celula().
hora_de_la_ultima_mecanica
double Contenedor_de_Celulas::hora_de_la_ultima_mecanica
Definition at line 62 of file Contenedor_de_Celulas.h.
Referenced by actualizar_todas_las_celulas(), and Contenedor_de_Celulas().
num_de_celulas
int Contenedor_de_Celulas::num_de_celulas
Definition at line 60 of file Contenedor_de_Celulas.h.
num_de_divisiones_en_este_paso
int Contenedor_de_Celulas::num_de_divisiones_en_este_paso
Definition at line 58 of file Contenedor_de_Celulas.h.
Referenced by actualizar_todas_las_celulas(), and Contenedor_de_Celulas().
num_de_muertes_en_este_paso
int Contenedor_de_Celulas::num_de_muertes_en_este_paso
Definition at line 59 of file Contenedor_de_Celulas.h.
Referenced by actualizar_todas_las_celulas().
tiempo_desde_la_ultima_mecanica
double Contenedor_de_Celulas::tiempo_desde_la_ultima_mecanica
Definition at line 61 of file Contenedor_de_Celulas.h.
Referenced by actualizar_todas_las_celulas(), and Contenedor_de_Celulas().
The documentation for this class was generated from the following files:
Contenedor_de_Celulas.h
Contenedor_de_celulas.cpp