Cancer Cell Agent Simulation: Ciclo_Modelo Class Reference
Ciclo_Modelo Class Reference
Models the cell cycle with phases and transitions.
#include <Ciclo_Modelo.h>
Public Member Functions
Ciclo_Modelo ()
Default constructor.
int agregar_fase (int codigo, std::string nombre)
Adds a new phase to the cell cycle model.
int agregar_link (int indice_fase_inicial, int indice_fase_final, bool(*funcion_arrest)(Volumen &volumen, Muerte_parametros &mp))
Creates a link between two phases.
double & tasa_de_transicion (int indice_fase_inicial, int indice_fase_final)
Gets reference to the transition rate between phases.
Fase_Link & fase_link (int indice_fase_inicial, int indice_fase_final)
Gets the phase link between two phases.
std::ostream & mostrar_ciclo (std::ostream &os)
Displays the cell cycle model structure.
void avanzar_en_el_modelo (bool &flagged_para_remover, bool &flagged_para_dividirse, int &indice_de_la_fase_actual, double &tiempo_acumulado_en_la_fase, Volumen &volumen, double dt, std::vector< std::vector< double > > &c_tasas_de_transicion, Muerte_parametros &mp)
Advances the cell in its current cell cycle phase.
double get_tasa_de_transicion (int indice_fase_inicial)
Gets the transition rate for a phase.
bool get_actualizar_volumen (int indice_fase_inicial)
Checks if volume should be updated in the given phase.
int encontrar_indice_de_la_fase (int codigo)
Finds the index of a phase by its code.
int get_indice_de_mapa_inverso (int fase_uno, int fase_dos)
Gets the inverse map index for a phase transition.
Public Attributes
std::string nombre
Name of the cell cycle model.
std::string unidades_tiempo
Time units used for transition rates (e.g., "min")
int codigo
Unique identifier code for the model.
std::vector< Fase > fases
Collection of all phases in the cell cycle.
std::vector< std::vector< Fase_Link > > fase_links
Collection of links between phases.
std::vector< std::vector< double > > tasas_de_transicion
Transition rates between phases.
Private Attributes
std::vector< std::unordered_map< int, int > > mapas_de_indice_inverso
Maps to find the correct index for phase transitions.
Detailed Description
Models the cell cycle with phases and transitions.
The Ciclo_Modelo class implements a finite state machine representing the cell cycle with multiple phases and transitions between phases.
In cancer research, this model is critical for:
Representing heterogeneous cell cycle dynamics in tumor populations
Modeling different proliferation rates across tumor regions
Simulating the effects of drugs targeting specific cell cycle phases
Capturing growth arrest in response to environmental factors like hypoxia
Each phase is represented by a Fase object, and transitions between phases are governed by transition rates and optional arrest functions that can halt transitions based on cell volume or death parameters.
Definition at line 55 of file Ciclo_Modelo.h.
Constructor & Destructor Documentation
Ciclo_Modelo()
Ciclo_Modelo::Ciclo_Modelo ()
Default constructor.
Default constructor for the Ciclo_Modelo class.
Initializes an empty cell cycle model with default name and units
Initializes a new cell cycle model with:
Empty phase collections
Default name "Sin nombre"
Default time units "min"
Default code 9999
The model is not functional until phases and transitions are added.
Definition at line 39 of file Ciclo_Modelo.cpp.
References codigo, fase_links, fases, mapas_de_indice_inverso, nombre, tasas_de_transicion, and unidades_tiempo.
Member Function Documentation
agregar_fase()
int Ciclo_Modelo::agregar_fase (int codigo, std::string nombre)
Adds a new phase to the cell cycle model.
Parameters
codigo Unique identifier for the phase
nombre Descriptive name of the phase
Returns
Index of the newly added phase
Creates a new phase in the model and initializes all related data structures. In cancer modeling, phases typically represent key cell cycle stages like:
G0 (quiescence)
G1 (growth and preparation for DNA synthesis)
S (DNA synthesis)
G2 (preparation for mitosis)
M (mitosis/cell division)
Parameters
codigo Unique identifier for the phase
nombre Descriptive name of the phase
Returns
Index of the newly added phase
Definition at line 71 of file Ciclo_Modelo.cpp.
References codigo, fase_links, fases, mapas_de_indice_inverso, nombre, and tasas_de_transicion.
Referenced by crear_ciclo_apoptosis(), crear_ciclo_ki67(), crear_ciclo_necrosis(), and crear_ciclo_vida().
agregar_link()
int Ciclo_Modelo::agregar_link (int indice_fase_inicial, int indice_fase_final, bool(*)(Volumen &volumen, Muerte_parametros &mp) funcion_arrest)
Creates a link between two phases.
Creates a link between two phases in the cell cycle.
Parameters
indice_fase_inicial Index of the source phase
indice_fase_final Index of the destination phase
funcion_arrest Optional function that can arrest the transition
Returns
Index of the newly created link
In cancer modeling, arrest functions can represent growth controls like contact inhibition or environmental stress responses
Establishes a transition pathway between phases and assigns an optional arrest function that can block the transition under certain conditions.
In cancer research, phase transitions can be modulated by:
Growth factors in the microenvironment
Stress conditions like hypoxia
Checkpoint proteins like p53
Drug effects on specific cycle phases
Parameters
indice_fase_inicial Index of the source phase
indice_fase_final Index of the destination phase
funcion_arrest Function pointer to a condition that can arrest the transition
Returns
Index of the newly created link
Definition at line 111 of file Ciclo_Modelo.cpp.
References fase_links, mapas_de_indice_inverso, and tasas_de_transicion.
Referenced by crear_ciclo_apoptosis(), crear_ciclo_ki67(), crear_ciclo_necrosis(), and crear_ciclo_vida().
avanzar_en_el_modelo()
void Ciclo_Modelo::avanzar_en_el_modelo (bool & flagged_para_remover, bool & flagged_para_dividirse, int & indice_de_la_fase_actual, double & tiempo_acumulado_en_la_fase, Volumen & volumen, double dt, std::vector< std::vector< double > > & c_tasas_de_transicion, Muerte_parametros & mp)
Advances the cell in its current cell cycle phase.
Advances a cell through its current cycle phase.
Parameters
flagged_para_remover Set to true if cell should be removed
flagged_para_dividirse Set to true if cell should divide
indice_de_la_fase_actual Current phase index (updated if phase changes)
tiempo_acumulado_en_la_fase Time spent in current phase (updated)
volumen Cell volume parameters
dt Time step for simulation
c_tasas_de_transicion Current transition rates (possibly modified by microenvironment)
mp Death parameters for the cell
This is a key method for cancer simulation as it determines:
When and if cells divide (tumor growth)
When cells transition between phases (affecting drug sensitivity)
How microenvironmental factors affect cycle progression
This is the core method that handles cell cycle progression. It:
Updates time spent in the current phase
Checks for possible transitions to other phases
Applies arrest functions that might block transitions
Handles cell division/removal events when phases end
Executes phase entry functions when transitioning
In cancer research, this method is critical as it models:
Differential proliferation rates across tumor regions
Cell cycle responses to microenvironmental conditions
Cell division events that drive tumor growth
Effects of cycle-specific drugs and treatments
Parameters
flagged_para_remover Flag set if cell should be removed
flagged_para_dividirse Flag set if cell should divide
indice_de_la_fase_actual Current phase index (updated if changed)
tiempo_acumulado_en_la_fase Time in current phase (updated)
volumen Cell volume parameters
dt Time step for simulation
c_tasas_de_transicion Current transition rates
mp Cell death parameters
Definition at line 267 of file Ciclo_Modelo.cpp.
References fase_links, fases, RNG::RandomNumber(), and rng.
Referenced by Ciclo::avanzar_en_el_ciclo().
encontrar_indice_de_la_fase()
int Ciclo_Modelo::encontrar_indice_de_la_fase (int codigo)
Finds the index of a phase by its code.
Parameters
codigo The code to search for
Returns
Index of the phase with the given code
Searches through all phases to find one with the specified code. This is useful when initializing cells with specific cycle phases or when transitioning between different cycle models.
In cancer research, this helps identify particular phases that might be targeted by treatments or affected by mutations.
Parameters
codigo The code to search for
Returns
Index of the phase with the given code, or 0 if not found
Definition at line 351 of file Ciclo_Modelo.cpp.
References codigo, and fases.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), Celula::inicializar_celula_sana(), and Linfocito::Linfocito().
fase_link()
Fase_Link & Ciclo_Modelo::fase_link (int indice_fase_inicial, int indice_fase_final)
Gets the phase link between two phases.
Gets the phase link object between two phases.
Parameters
indice_fase_inicial Index of the source phase
indice_fase_final Index of the destination phase
Returns
Reference to the phase link
Retrieves the link object that contains transition properties between phases. This allows access to arrest functions and other properties of the transition.
Parameters
indice_fase_inicial Index of the source phase
indice_fase_final Index of the destination phase
Returns
Reference to the phase link object
Definition at line 200 of file Ciclo_Modelo.cpp.
References fase_links, and mapas_de_indice_inverso.
Referenced by crear_ciclo_apoptosis(), crear_ciclo_ki67(), crear_ciclo_necrosis(), and crear_ciclo_vida().
get_actualizar_volumen()
bool Ciclo_Modelo::get_actualizar_volumen (int indice_fase_inicial)
Checks if volume should be updated in the given phase.
Checks if volume should be updated in a specific phase.
Parameters
indice_fase_inicial Index of the phase to check
Returns
True if volume should be updated, false otherwise
Some cell cycle phases involve volume changes (like growth in G1), while others don't. This method checks if the specified phase should update cell volume parameters.
In cancer modeling, modified growth rates in specific phases can represent abnormal proliferation characteristics.
Parameters
indice_fase_inicial Index of the phase to check
Returns
True if volume should be updated, false otherwise
Definition at line 185 of file Ciclo_Modelo.cpp.
References fases.
Referenced by Ciclo::actualizar_volumen().
get_indice_de_mapa_inverso()
int Ciclo_Modelo::get_indice_de_mapa_inverso (int fase_uno, int fase_dos)
Gets the inverse map index for a phase transition.
Parameters
fase_uno Source phase index
fase_dos Destination phase index
Returns
Index in the internal map
Retrieves the internal index mapping for a transition between phases. This is used internally to access the correct transition rate and link objects.
Parameters
fase_uno Source phase index
fase_dos Destination phase index
Returns
Internal index for the phase transition
Definition at line 372 of file Ciclo_Modelo.cpp.
References mapas_de_indice_inverso.
Referenced by Ciclo::actualizar_mis_tasas_de_transicion().
get_tasa_de_transicion()
double Ciclo_Modelo::get_tasa_de_transicion (int indice_fase_inicial)
Gets the transition rate for a phase.
Gets the transition rate for a specific phase.
Parameters
indice_fase_inicial Index of the phase
Returns
Transition rate from the specified phase
Retrieves the total transition rate from a specific phase, which determines how quickly cells exit this phase. In cancer modeling, slower phases like G1 or G0 often have lower rates, while faster phases have higher rates.
Parameters
indice_fase_inicial Index of the phase
Returns
Transition rate from the specified phase
Definition at line 161 of file Ciclo_Modelo.cpp.
References fase_links, and tasas_de_transicion.
Referenced by Ciclo::tasa_de_transicion().
mostrar_ciclo()
std::ostream & Ciclo_Modelo::mostrar_ciclo (std::ostream & os)
Displays the cell cycle model structure.
Parameters
os Output stream to write to
Returns
Reference to the output stream
Creates a text representation of the cell cycle model showing all phases, their connections, and transition rates. Phases that lead to cell division are marked with an asterisk (*).
This is useful for debugging and verifying the correct structure of cancer-specific cell cycle implementations.
Parameters
os Output stream to write to
Returns
Reference to the output stream
Definition at line 219 of file Ciclo_Modelo.cpp.
References codigo, fase_links, fases, nombre, tasa_de_transicion(), and unidades_tiempo.
Referenced by Celula::mostrar_informacion_de_la_celula().
tasa_de_transicion()
double & Ciclo_Modelo::tasa_de_transicion (int indice_fase_inicial, int indice_fase_final)
Gets reference to the transition rate between phases.
Gets a reference to the transition rate between two phases.
Parameters
indice_fase_inicial Index of the source phase
indice_fase_final Index of the destination phase
Returns
Reference to the transition rate value
Retrieves the rate at which cells transition from one phase to another. These rates determine the tumor growth kinetics and can be adjusted to model different cancer types or responses to treatment.
Parameters
indice_fase_inicial Index of the source phase
indice_fase_final Index of the destination phase
Returns
Reference to the transition rate value
Definition at line 145 of file Ciclo_Modelo.cpp.
References mapas_de_indice_inverso, and tasas_de_transicion.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), crear_ciclo_apoptosis(), crear_ciclo_ki67(), crear_ciclo_necrosis(), crear_ciclo_vida(), Celula::inicializar_celula_sana(), and mostrar_ciclo().
Member Data Documentation
codigo
int Ciclo_Modelo::codigo
Unique identifier code for the model.
Definition at line 66 of file Ciclo_Modelo.h.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), agregar_fase(), Ciclo_Modelo(), crear_ciclo_apoptosis(), crear_ciclo_ki67(), crear_ciclo_necrosis(), crear_ciclo_vida(), encontrar_indice_de_la_fase(), mostrar_ciclo(), and Celula::mostrar_informacion_de_la_celula().
fase_links
std::vector< std::vector<Fase_Link> > Ciclo_Modelo::fase_links
Collection of links between phases.
Definition at line 70 of file Ciclo_Modelo.h.
Referenced by agregar_fase(), agregar_link(), avanzar_en_el_modelo(), Ciclo_Modelo(), fase_link(), get_tasa_de_transicion(), and mostrar_ciclo().
fases
std::vector<Fase> Ciclo_Modelo::fases
Collection of all phases in the cell cycle.
Definition at line 68 of file Ciclo_Modelo.h.
Referenced by agregar_fase(), avanzar_en_el_modelo(), Ciclo_Modelo(), crear_ciclo_apoptosis(), crear_ciclo_ki67(), crear_ciclo_necrosis(), crear_ciclo_vida(), encontrar_indice_de_la_fase(), Ciclo::fase_actual(), get_actualizar_volumen(), and mostrar_ciclo().
mapas_de_indice_inverso
std::vector< std::unordered_map<int,int> > Ciclo_Modelo::mapas_de_indice_inverso private
Maps to find the correct index for phase transitions.
Definition at line 58 of file Ciclo_Modelo.h.
Referenced by agregar_fase(), agregar_link(), Ciclo_Modelo(), fase_link(), get_indice_de_mapa_inverso(), and tasa_de_transicion().
nombre
std::string Ciclo_Modelo::nombre
Name of the cell cycle model.
Definition at line 62 of file Ciclo_Modelo.h.
Referenced by agregar_fase(), Ciclo_Modelo(), crear_ciclo_apoptosis(), crear_ciclo_ki67(), crear_ciclo_necrosis(), crear_ciclo_vida(), mostrar_ciclo(), and Celula::mostrar_informacion_de_la_celula().
tasas_de_transicion
std::vector< std::vector<double> > Ciclo_Modelo::tasas_de_transicion
Transition rates between phases.
Definition at line 72 of file Ciclo_Modelo.h.
Referenced by agregar_fase(), agregar_link(), Ciclo_Modelo(), get_tasa_de_transicion(), Celula::inicializar_celula_sana(), Ciclo::sync_con_ciclo_modelo(), and tasa_de_transicion().
unidades_tiempo
std::string Ciclo_Modelo::unidades_tiempo
Time units used for transition rates (e.g., "min")
Definition at line 64 of file Ciclo_Modelo.h.
Referenced by Ciclo_Modelo(), crear_ciclo_ki67(), crear_ciclo_vida(), and mostrar_ciclo().
The documentation for this class was generated from the following files:
Ciclo_Modelo.h
Ciclo_Modelo.cpp