Cancer Cell Agent Simulation: Tejido Class Reference
Tejido Class Reference
Models a tissue structure containing cells and microenvironment.
#include <Tejido.h>
Public Member Functions
Tejido ()
Default constructor for the Tejido class.
void inicializar_tejido ()
Initializes the tissue structure with cells and microenvironment.
std::vector< Vector > crear_planos_de_celulas_sanas_en_Z (int cantidad, double posicion_en_z_del_primer_plano)
Creates planes of healthy cells along the Z-axis.
std::vector< Vector > crear_esfera_de_celulas (double radio_de_la_esfera)
Creates a spherical arrangement of cells.
void introducir_linfocitos (int cantidad)
Introduces lymphocytes around the tumor periphery.
void introducir_linfocitos_aleatorios (int cantidad)
Introduces lymphocytes randomly in the domain.
void geometria_del_tumor ()
Calculates geometric properties of the tumor.
Public Attributes
Microambiente microambiente
Contenedor_de_Celulas cdc
double radio_del_tumor
double volumen_del_tumor
double volumen_del_tumor2
int celulas_tumorales
int celulas_muertas
Detailed Description
Models a tissue structure containing cells and microenvironment.
The Tejido (Tissue) class serves as the primary organizational structure in the simulation, containing both the microenvironment and the cell container. It provides methods for initializing tissue structure, creating spatial arrangements of cells, introducing immune cells, and calculating tumor geometry.
Cancer Research Context: In cancer research, the tissue organization is critical for studying tumor growth, infiltration, and interaction with surrounding healthy tissue. This class enables realistic spatial modeling of tumor development within host tissue.
Definition at line 57 of file Tejido.h.
Constructor & Destructor Documentation
Tejido()
Tejido::Tejido ()
Default constructor for the Tejido class.
Constructor for the Tejido class.
Cancer Research Context: Initializes a tissue object that serves as the foundation for cancer simulations. The tissue integrates cellular components with the biochemical microenvironment, providing the structural framework for modeling tumor development, invasion, and interactions with surrounding normal tissue.
Definition at line 40 of file Tejido.cpp.
Member Function Documentation
crear_esfera_de_celulas()
std::vector< Vector > Tejido::crear_esfera_de_celulas (double radio_de_la_esfera)
Creates a spherical arrangement of cells.
Creates a sphere of cell positions with specified radius.
Parameters
radio_de_la_esfera Radius of the sphere
Returns
Vector of cell positions
Parameters
radio_de_la_esfera Radius of the sphere to create
Returns
std::vector<Vector> Vector of 3D positions for cells
Cancer Research Context: This method generates a spherical arrangement of cell positions that can be used to create realistic 3D tumor geometries. Spherical tumor models are important in cancer research for studying:
Diffusion gradients of oxygen and nutrients from the periphery to the core
Development of hypoxic and necrotic regions in the tumor center
Spatial heterogeneity in proliferation rates and phenotypes
Mechanical constraints on tumor growth and invasion
The method creates a hexagonal close-packed (HCP) lattice structure that efficiently fills 3D space while maintaining realistic cell-cell spacing.
Definition at line 173 of file Tejido.cpp.
References cdc, Contenedor_de_Celulas::celula, Celula::fenotipo, Fenotipo::geometria, Geometria::radio, Vector::x, Vector::y, and Vector::z.
Referenced by inicializar_tejido().
crear_planos_de_celulas_sanas_en_Z()
std::vector< Vector > Tejido::crear_planos_de_celulas_sanas_en_Z (int cantidad, double posicion_en_z_del_primer_plano)
Creates planes of healthy cells along the Z-axis.
Parameters
cantidad Number of planes to create
posicion_en_z_del_primer_plano Z-position of the first plane
Returns
Vector of cell positions
Parameters
cantidad Number of planes to create
posicion_en_z_del_primer_plano Z-position of the first plane
Returns
std::vector<Vector> Vector of 3D positions for cells
Cancer Research Context: This method generates organized layers of healthy cells that can represent normal tissue surrounding a tumor. This arrangement is valuable for studying:
Tumor-stroma interactions at the invasion front
Mechanical constraints imposed by surrounding tissue
Diffusion of nutrients and drugs through layered tissue
Patterns of cancer invasion into structured normal tissue
The hexagonal arrangement within each plane mimics the efficient packing often seen in epithelial tissues, providing a biologically relevant environment for cancer growth and invasion studies.
Definition at line 124 of file Tejido.cpp.
References cdc, Contenedor_de_Celulas::celula, Celula::fenotipo, Fenotipo::geometria, pg, Geometria::radio, Parametros_globales::rango_en_X, Parametros_globales::rango_en_Y, Vector::x, Vector::y, and Vector::z.
geometria_del_tumor()
void Tejido::geometria_del_tumor ()
Calculates geometric properties of the tumor.
Calculates and updates tumor geometry metrics.
Computes the tumor radius, volume, cell count, and other geometric metrics to track tumor progression over time.
Cancer Research Context: This method analyzes the current state of the tumor to calculate key metrics that are essential for quantitative cancer research:
Tumor radius: Indicates the extent of tumor spread and invasion
Tumor volume: Critical measure for assessing tumor growth kinetics
Cell counts: Quantifies tumor cellularity and death rates
These metrics enable quantitative analysis of:
Tumor growth rates under different conditions
Effects of treatments on tumor size and composition
Correlation between tumor geometry and microenvironmental factors
Validation of computational models against experimental data
The method uses efficient computational approaches (calculating norm squared before taking square root) to optimize performance for large cell populations.
Definition at line 366 of file Tejido.cpp.
References celulas_muertas, celulas_tumorales, norm_squared(), radio_del_tumor, todas_las_celulas, volumen_del_tumor, and volumen_del_tumor2.
Referenced by main().
inicializar_tejido()
void Tejido::inicializar_tejido ()
Initializes the tissue structure with cells and microenvironment.
Initializes the tissue with cells and microenvironment.
Sets up the microenvironment, cell container, and creates the initial spherical arrangement of cells for the simulation.
Cancer Research Context: This method establishes the initial conditions for cancer simulation by:
Setting up the biochemical microenvironment (oxygen, nutrients, signaling molecules)
Initializing the spatial cell container for efficient cell interactions
Creating and placing the initial cancer cell
Generating a sphere of normal cells surrounding the tumor
This initialization creates a controlled environment for studying early tumor development, cellular interactions, and the influence of spatial organization on cancer progression.
Definition at line 61 of file Tejido.cpp.
References Parametros_globales::c_dx, Parametros_globales::c_dy, Parametros_globales::c_dz, cdc, Contenedor_de_Celulas::celula, celulas_para_registrar_en_voxeles, crear_celula(), crear_esfera_de_celulas(), Celula::fenotipo, Parametros_globales::imm_mean, Parametros_globales::imm_sd, Contenedor_de_Celulas::inicializar(), Celula::inicializar_celula(), Microambiente::inicializar_microambiente(), microambiente, RNG::NormalRandom_CM(), Secrecion::oncoproteina, pg, Parametros_globales::rango_en_X, Parametros_globales::rango_en_Y, Parametros_globales::rango_en_Z, Contenedor_de_Celulas::registrar_celula(), rng, Fenotipo::secrecion, and Celula::set_posicion().
Referenced by main().
introducir_linfocitos()
void Tejido::introducir_linfocitos (int cantidad)
Introduces lymphocytes around the tumor periphery.
Introduces lymphocytes (immune cells) around the tumor periphery.
Adds immune cells (lymphocytes) in a shell around the tumor at a specified distance from the tumor edge.
Parameters
cantidad Number of lymphocytes to introduce
cantidad Number of lymphocytes to introduce
Cancer Research Context: This method models the immune response to cancer by introducing lymphocytes in a ring-like region surrounding the tumor. This approach is critical for studying:
Tumor-immune interactions at the invasion front
Immune surveillance and its role in controlling tumor growth
Immune cell infiltration patterns into solid tumors
Potential for immunotherapy efficacy in different tumor microenvironments
The method calculates the current tumor radius and places lymphocytes at a specified distance from the tumor boundary, mimicking the immune infiltration patterns observed in many solid tumors.
Definition at line 223 of file Tejido.cpp.
References cdc, celulas_para_registrar_en_voxeles, Celula::indice, norm_squared(), RNG::NormalRandom_CM(), RNG::RandomNumber(), Contenedor_de_Celulas::registrar_celula(), rng, Celula::set_posicion(), and todas_las_celulas.
introducir_linfocitos_aleatorios()
void Tejido::introducir_linfocitos_aleatorios (int cantidad)
Introduces lymphocytes randomly in the domain.
Introduces lymphocytes (immune cells) randomly throughout the domain.
Adds immune cells (lymphocytes) at random positions in the simulation domain, outside a minimum distance from the tumor.
Parameters
cantidad Number of lymphocytes to introduce
cantidad Number of lymphocytes to introduce
Cancer Research Context: This method models a different pattern of immune cell distribution by randomly placing lymphocytes throughout the simulation domain, but outside the tumor. This approach is valuable for studying:
Stochastic immune surveillance mechanisms
Heterogeneous immune infiltration patterns
Immune cell recruitment from distant sites
Differences between localized and systemic immune responses
The random distribution creates a more realistic representation of the variability in immune cell positioning observed in some tumor types, particularly those with less structured immune infiltration patterns.
Definition at line 293 of file Tejido.cpp.
References cdc, celulas_para_registrar_en_voxeles, Celula::indice, norm_squared(), pg, RNG::RandomNumber(), Parametros_globales::rango_en_X, Parametros_globales::rango_en_Y, Parametros_globales::rango_en_Z, Contenedor_de_Celulas::registrar_celula(), rng, Celula::set_posicion(), todas_las_celulas, Vector::x, Vector::y, and Vector::z.
Referenced by main().
Member Data Documentation
cdc
Contenedor_de_Celulas Tejido::cdc
Definition at line 61 of file Tejido.h.
Referenced by crear_esfera_de_celulas(), crear_planos_de_celulas_sanas_en_Z(), inicializar_tejido(), introducir_linfocitos(), introducir_linfocitos_aleatorios(), and main().
celulas_muertas
int Tejido::celulas_muertas
Definition at line 66 of file Tejido.h.
Referenced by geometria_del_tumor(), and main().
celulas_tumorales
int Tejido::celulas_tumorales
Definition at line 65 of file Tejido.h.
Referenced by geometria_del_tumor(), and main().
microambiente
Microambiente Tejido::microambiente
Definition at line 60 of file Tejido.h.
Referenced by inicializar_tejido(), and main().
radio_del_tumor
double Tejido::radio_del_tumor
Definition at line 62 of file Tejido.h.
Referenced by geometria_del_tumor(), and main().
volumen_del_tumor
double Tejido::volumen_del_tumor
Definition at line 63 of file Tejido.h.
Referenced by geometria_del_tumor(), and main().
volumen_del_tumor2
double Tejido::volumen_del_tumor2
Definition at line 64 of file Tejido.h.
Referenced by geometria_del_tumor(), and main().
The documentation for this class was generated from the following files:
Tejido.h
Tejido.cpp