Cancer Cell Agent Simulation: Ciclo Class Reference
Ciclo Class Reference
Tracks and manages an individual cell's progression through its cell cycle.
#include <Ciclo.h>
Public Member Functions
Ciclo ()
Default constructor.
void sync_con_ciclo_modelo (Ciclo_Modelo &cm)
Synchronizes this cycle instance with a cycle model.
void avanzar_en_el_ciclo (Volumen &volumen, double dt, std::vector< std::vector< double > > &c_tasas_de_transicion, Muerte_parametros &mp)
Advances the cell through its cycle for a time step.
bool actualizar_volumen ()
Checks if volume should be updated in current phase.
double tasa_de_transicion ()
Gets the current phase's transition rate.
double & actualizar_mis_tasas_de_transicion (int fase_actual, int fase_siguiente)
Updates transition rate between specified phases.
Fase & fase_actual ()
Gets reference to the current phase object.
Public Attributes
Ciclo_Modelo * pCiclo_Modelo
Pointer to the cycle model defining structure and rules.
int indice_de_la_fase_actual
Current phase index within the cell cycle.
double tiempo_acumulado_en_la_fase
Time accumulated in the current phase.
bool flagged_para_dividirse
Flag indicating if cell is ready to divide.
bool flagged_para_remover
Flag indicating if cell should be removed.
std::vector< std::vector< double > > tasas_de_transicion
Transition rates between cell cycle phases.
double tasa_aleatoria
Random rate value used in stochastic transitions.
Detailed Description
Tracks and manages an individual cell's progression through its cell cycle.
The Ciclo class represents the current state of an individual cell's progression through the cell cycle. It maintains a pointer to a Ciclo_Modelo that defines the structure of the cycle (phases, transitions), while tracking the cell's current phase, time spent in that phase, and flags for important state changes like division or death.
In cancer research, this class enables modeling of:
Individual cell cycle dysregulation in cancer
Heterogeneous cell cycle rates in tumors
Cell cycle arrests in response to therapy
Proliferation-quiescence decisions at the single-cell level
Death pathway integration with cell cycle state
Definition at line 52 of file Ciclo.h.
Constructor & Destructor Documentation
Ciclo()
Ciclo::Ciclo ()
Default constructor.
Default constructor for the Ciclo class.
Creates a new cycle instance with NULL model pointer and default values. Must be followed by sync_con_ciclo_modelo() to connect to a specific model.
Initializes a new cycle instance with NULL model pointer and default values for all tracking variables. The cycle must be connected to a specific model using sync_con_ciclo_modelo() before use.
In cancer modeling, this initialization creates the foundation for tracking an individual cancer cell's progression through its life cycle, with appropriate flags for monitoring division and death events.
Returns
void
Definition at line 55 of file Ciclo.cpp.
References flagged_para_dividirse, flagged_para_remover, indice_de_la_fase_actual, pCiclo_Modelo, tasa_aleatoria, and tiempo_acumulado_en_la_fase.
Member Function Documentation
actualizar_mis_tasas_de_transicion()
double & Ciclo::actualizar_mis_tasas_de_transicion (int fase_actual, int fase_siguiente)
Updates transition rate between specified phases.
Parameters
fase_actual Current phase index
fase_siguiente Target phase index
Returns
Reference to the specific transition rate
Provides access to modify specific transition rates based on environmental conditions. In cancer models, enables representing how hypoxia, acidosis, or therapeutics alter specific cycle transitions.
Parameters
fase_actual Current phase index
fase_siguiente Target phase index
Returns
Reference to the specific transition rate
Provides direct access to modify a specific transition rate between the given phases. Uses the model's inverse mapping to find the correct index.
In cancer research, enables representing environmental influences on specific transition rates, such as hypoxia-induced slowing of G1/S transition or acidosis effects on mitotic entry, critical for modeling tumor microenvironment effects on cancer growth dynamics.
Definition at line 162 of file Ciclo.cpp.
References fase_actual(), Ciclo_Modelo::get_indice_de_mapa_inverso(), pCiclo_Modelo, and tasas_de_transicion.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), Celula::dividir(), Celula::inicializar_celula(), and Linfocito::Linfocito().
actualizar_volumen()
bool Ciclo::actualizar_volumen ()
Checks if volume should be updated in current phase.
Returns
Boolean indicating if volume update is needed
Different cycle phases may have different volume update requirements. In cancer modeling, reflects how growth patterns vary across cell cycle phases, with cancer cells often showing dysregulated growth in specific phases.
Returns
Boolean indicating if volume update is needed
Queries the cycle model to determine if the current phase requires volume updates. Different phases may have different growth requirements.
In cancer modeling, reflects how cell growth varies across cycle phases, with cancer cells often showing altered growth patterns in specific phases due to oncogenic signaling or metabolic reprogramming.
Definition at line 126 of file Ciclo.cpp.
References Ciclo_Modelo::get_actualizar_volumen(), indice_de_la_fase_actual, and pCiclo_Modelo.
Referenced by Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), and Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina().
avanzar_en_el_ciclo()
void Ciclo::avanzar_en_el_ciclo (Volumen & volumen, double dt, std::vector< std::vector< double > > & c_tasas_de_transicion, Muerte_parametros & mp)
Advances the cell through its cycle for a time step.
Parameters
volumen Reference to the cell's volume
dt Time step size
c_tasas_de_transicion Current transition rates, potentially modified by conditions
mp Death parameters affecting cycle progression
Progresses the cell through its cycle for the given time step, updating phase, time accumulated, and potentially setting flags for division or death. In cancer research, models how cancer cells progress through aberrant cycles and respond to microenvironmental conditions or therapies.
Parameters
volumen Reference to the cell's volume
dt Time step size
c_tasas_de_transicion Current transition rates, potentially modified by conditions
mp Death parameters affecting cycle progression
Progresses the cell through its cycle for the given time step by delegating to the linked cycle model. Updates the phase, accumulated time, and potentially sets flags for division or removal.
In cancer research, this method simulates how cancer cells progress through altered cell cycles, responding to various microenvironmental conditions that may affect transition rates, growth patterns, and susceptibility to death pathways.
Returns
void
Definition at line 110 of file Ciclo.cpp.
References Ciclo_Modelo::avanzar_en_el_modelo(), flagged_para_dividirse, flagged_para_remover, indice_de_la_fase_actual, pCiclo_Modelo, and tiempo_acumulado_en_la_fase.
Referenced by Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), and Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina().
fase_actual()
Fase & Ciclo::fase_actual ()
Gets reference to the current phase object.
Returns
Reference to current Fase object
Provides access to the detailed properties of the current cell cycle phase. In cancer research, allows examination of phase-specific behaviors that may be dysregulated or targeted by therapies.
Returns
Reference to current Fase object
Provides access to the detailed properties of the current cell cycle phase from the linked cycle model. Allows examination and modification of phase-specific properties.
In cancer research, allows access to phase-specific behaviors that may be dysregulated in cancer cells or targeted by phase-specific therapeutics, such as S-phase specific chemotherapies or mitotic inhibitors.
Definition at line 180 of file Ciclo.cpp.
References Ciclo_Modelo::fases, indice_de_la_fase_actual, and pCiclo_Modelo.
Referenced by actualizar_mis_tasas_de_transicion(), Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), and Celula::comenzar_muerte().
sync_con_ciclo_modelo()
void Ciclo::sync_con_ciclo_modelo (Ciclo_Modelo & cm)
Synchronizes this cycle instance with a cycle model.
Parameters
cm Reference to the cycle model to be used
Links this cycle instance to a specific model and copies transition rates. In cancer modeling, allows assignment of specific cycle types to different cancer cell populations.
Parameters
cm Reference to the cycle model to be used
Links this cycle instance to a specific model and copies the transition rates from the model to this instance. This connection allows the cycle to follow the rules defined by the model while maintaining its own state.
In cancer research, this enables attaching different cycle models (like Ki67 cycle vs basic live/dead cycle) to different cell populations, supporting heterogeneous modeling of cancer cells with diverse proliferation characteristics.
Returns
void
Definition at line 80 of file Ciclo.cpp.
References pCiclo_Modelo, tasas_de_transicion, and Ciclo_Modelo::tasas_de_transicion.
Referenced by Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Celula::comenzar_muerte(), Celula::inicializar_celula(), Celula::inicializar_celula_sana(), and Linfocito::Linfocito().
tasa_de_transicion()
double Ciclo::tasa_de_transicion ()
Gets the current phase's transition rate.
Returns
Transition rate from current phase
Retrieves the base transition rate for the current phase. In cancer models, these rates often reflect oncogenic alterations that accelerate specific phase transitions.
Returns
Transition rate from current phase
Retrieves the base transition rate for the current phase from the cycle model. This rate determines how quickly cells move through this phase.
In cancer models, transition rates often reflect oncogenic alterations that accelerate specific phase transitions, such as dysregulated G1/S transitions due to Rb/E2F pathway mutations common in many cancers.
Definition at line 142 of file Ciclo.cpp.
References Ciclo_Modelo::get_tasa_de_transicion(), indice_de_la_fase_actual, and pCiclo_Modelo.
Member Data Documentation
flagged_para_dividirse
bool Ciclo::flagged_para_dividirse
Flag indicating if cell is ready to divide.
Set to true when a cell completes all cycle phases and is ready to divide. In cancer modeling, tracks proliferation events and controls tumor growth rates.
Definition at line 85 of file Ciclo.h.
Referenced by avanzar_en_el_ciclo(), Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), and Ciclo().
flagged_para_remover
bool Ciclo::flagged_para_remover
Flag indicating if cell should be removed.
Set to true when a cell is committed to a death pathway and should be removed. Critical for modeling cancer cell death due to therapy, stress, or immune killing.
Definition at line 92 of file Ciclo.h.
Referenced by avanzar_en_el_ciclo(), Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), and Ciclo().
indice_de_la_fase_actual
int Ciclo::indice_de_la_fase_actual
Current phase index within the cell cycle.
Tracks which phase (e.g., G0/G1, S, G2, M) the cell is currently in. In cancer research, phase distribution analysis reveals proliferation status of tumor populations and potential therapeutic vulnerabilities.
Definition at line 70 of file Ciclo.h.
Referenced by actualizar_volumen(), avanzar_en_el_ciclo(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Ciclo(), Celula::comenzar_muerte(), fase_actual(), and tasa_de_transicion().
pCiclo_Modelo
Ciclo_Modelo* Ciclo::pCiclo_Modelo
Pointer to the cycle model defining structure and rules.
Links to the specific cycle model (e.g., Ki67 cycle, live/dead cycle) that defines the phases and transition rules. In cancer, different models can represent various cancer types or states (e.g., highly proliferative vs. dormant cancer cells).
Definition at line 62 of file Ciclo.h.
Referenced by actualizar_mis_tasas_de_transicion(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), actualizar_volumen(), avanzar_en_el_ciclo(), Ciclo(), fase_actual(), Celula::inicializar_celula_sana(), Celula::mostrar_informacion_de_la_celula(), sync_con_ciclo_modelo(), and tasa_de_transicion().
tasa_aleatoria
double Ciclo::tasa_aleatoria
Random rate value used in stochastic transitions.
Used for probabilistic phase transitions, adding cell-to-cell variability. Enables modeling of heterogeneous division rates observed in cancer cell populations.
Definition at line 108 of file Ciclo.h.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), Ciclo(), Celula::dividir(), and Celula::inicializar_celula().
tasas_de_transicion
std::vector< std::vector<double> > Ciclo::tasas_de_transicion
Transition rates between cell cycle phases.
Matrix of transition rates between phases, potentially modified by microenvironmental factors. In cancer, these rates are often dysregulated due to oncogenic mutations or microenvironmental stressors.
Definition at line 100 of file Ciclo.h.
Referenced by actualizar_mis_tasas_de_transicion(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Celula::inicializar_celula_sana(), and sync_con_ciclo_modelo().
tiempo_acumulado_en_la_fase
double Ciclo::tiempo_acumulado_en_la_fase
Time accumulated in the current phase.
Tracks how long the cell has been in its current phase, critical for determining phase transitions. Cancer cells often show altered phase durations, particularly shortened G1 phases or prolonged S phases.
Definition at line 78 of file Ciclo.h.
Referenced by avanzar_en_el_ciclo(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Ciclo(), and Celula::comenzar_muerte().
The documentation for this class was generated from the following files:
Ciclo.h
Ciclo.cpp