Cancer Cell Agent Simulation: Fase Class Reference
Fase Class Reference
Class representing a cell cycle phase.
#include <Fase.h>
Public Member Functions
Fase ()
Default constructor.
Public Attributes
int indice
Index of the phase in the cell cycle model.
int codigo
Code identifying the specific phase type.
std::string nombre
Name of the phase (e.g., "G0", "G1", "S", "G2", "M", "Apoptotic")
bool division_al_final_de_la_fase
Flag indicating if cell division occurs at the end of this phase.
bool remover_al_final_de_la_fase
Flag indicating if the cell should be removed at the end of this phase.
bool actualizar_volumen
Flag indicating if cell volume should be updated during this phase.
void(* funcion_de_entrada)(Volumen &volumen, Muerte_parametros &mp)
Function pointer to phase entry function.
Detailed Description
Class representing a cell cycle phase.
The Fase class models a distinct phase in a cell's life cycle. In cancer research and simulation, cell phases are crucial for understanding tumor growth, as dysregulation of phase transitions is a hallmark of cancer. This class enables modeling various aspects of cell behavior during specific phases, including division, volume changes, and death processes.
Definition at line 43 of file Fase.h.
Constructor & Destructor Documentation
Fase()
Fase::Fase ()
Default constructor.
Constructor for the Fase class.
Initializes a new phase with default values. All cancer cell cycle models start by constructing phases and then configuring them accordingly.
Initializes a new phase with default values. In cancer modeling, phases are typically constructed and then configured with specific properties based on their role in the cell cycle or death process.
The default initialization creates a "neutral" phase that does not cause division, removal, or volume updates. These properties must be set specifically for each phase type (e.g., mitotic phases for division, apoptotic phases for removal).
Default values:
Index and code set to 0
Name set to "Sin nombre" (No name)
No entry function
No division, removal, or volume updates
Definition at line 43 of file Fase.cpp.
References actualizar_volumen, codigo, division_al_final_de_la_fase, funcion_de_entrada, indice, nombre, and remover_al_final_de_la_fase.
Member Data Documentation
actualizar_volumen
bool Fase::actualizar_volumen
Flag indicating if cell volume should be updated during this phase.
Volume changes are important in cancer modeling, as different phases involve cell growth or shrinkage depending on the phase type.
Definition at line 77 of file Fase.h.
Referenced by Fase().
codigo
int Fase::codigo
Code identifying the specific phase type.
In cancer research, specific phase codes allow tracking cell populations in different cycle phases, important for analyzing tumor composition.
Definition at line 53 of file Fase.h.
Referenced by Fase().
division_al_final_de_la_fase
bool Fase::division_al_final_de_la_fase
Flag indicating if cell division occurs at the end of this phase.
This is crucial for modeling tumor growth, as it determines when new cancer cells are generated in the simulation.
Definition at line 63 of file Fase.h.
Referenced by Fase().
funcion_de_entrada
void(* Fase::funcion_de_entrada) (Volumen &volumen, Muerte_parametros &mp)
Function pointer to phase entry function.
This function is called when a cell enters this phase. It can modify cell volume and other parameters based on the specific phase behavior required.
Parameters
volumen Reference to cell volume parameters to be modified
mp Reference to death parameters that may be used
Definition at line 88 of file Fase.h.
Referenced by Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Celula::comenzar_muerte(), and Fase().
indice
int Fase::indice
Index of the phase in the cell cycle model.
Definition at line 46 of file Fase.h.
Referenced by Fase().
nombre
std::string Fase::nombre
Name of the phase (e.g., "G0", "G1", "S", "G2", "M", "Apoptotic")
Definition at line 56 of file Fase.h.
Referenced by Fase().
remover_al_final_de_la_fase
bool Fase::remover_al_final_de_la_fase
Flag indicating if the cell should be removed at the end of this phase.
Used for modeling cell death processes (e.g., apoptosis, necrosis), which are important aspects of tumor dynamics and response to therapy.
Definition at line 70 of file Fase.h.
Referenced by Fase().
The documentation for this class was generated from the following files:
Fase.h
Fase.cpp