Cancer Cell Agent Simulation: Linfocito Class Reference
Linfocito Class Reference
Specialized cell class representing a lymphocyte (immune cell)
#include <Celula.h>
Public Member Functions
Linfocito ()
Constructor for Lymphocyte.
void es_movil (bool valor)
Sets the lymphocyte's mobility.
void actualizar_vector_de_motilidad (double dt, std::vector< Celula * > celulas_en_mi_voxel)
Updates the lymphocyte's motility vector.
void motilidad_de_linfocito (double dt, std::vector< Celula * > celulas_en_mi_voxel)
Processes lymphocyte motility behavior.
void avanzar_linfocito (double dt, std::vector< Celula * > celulas_en_mi_voxel)
Advances lymphocyte-specific behaviors.
bool intento_de_apoptosis (Celula *celula_adherida, double dt)
Attempts to trigger apoptosis in an attached cell.
bool desencadenar_apoptosis (Celula *celula_adherida)
Triggers apoptosis in an attached cell.
void adherir_celula (Celula *celula_objetivo)
Adheres to a target cell.
void soltar_celula (Celula *celula_objetivo)
Releases an attached cell.
bool chequear_vecinos_para_adherirse (std::vector< Celula * > celulas_en_mi_voxel, double dt)
Checks neighboring cells for potential adhesion.
bool intentar_adherirse (Celula *celula_objetivo, double dt)
Attempts to adhere to a target cell.
virtual ~Linfocito ()
Virtual destructor.
Public Member Functions inherited from Celula
Celula ()
Default constructor for Cell.
void actualizar_volumen (Fenotipo &fenotipo, double dt)
Updates the cell volume based on growth/shrinkage rates.
void actualizar_parametros_de_celula_y_muerte_con_o2 (Fenotipo &fenotipo, double dt)
Updates cell and death parameters based on oxygen concentration.
void actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina (Fenotipo &fenotipo, double dt)
Updates cell and death parameters based on oxygen and oncoprotein.
void avanzar_funciones_del_fenotipo (double hora_global, double dt_ciclo)
Advances the cell's phenotypic functions over time.
void avanzar_funciones_del_fenotipo_con_O2 (double hora_global, double dt_ciclo)
Advances the cell's phenotypic functions considering oxygen.
void avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina (double hora_global, double dt_ciclo)
Advances phenotypic functions considering oxygen and oncoprotein.
Celula * dividir ()
Creates a daughter cell through division.
void morir (int indice)
Initiates cell death process.
bool set_posicion (double x, double y, double z)
Sets the cell's position using coordinates.
bool set_posicion (Vector posicion)
Sets the cell's position using a Vector.
void agregar_potenciales (Celula *otra_celula)
Adds mechanical potentials from another cell.
void agregar_potenciales_mb ()
Adds mechanical potentials from microenvironment boundary.
void agregar_potenciales_mb_2 ()
Alternative implementation for boundary potentials.
void actualizar_posicion (double dt)
Updates cell position based on velocity.
void comenzar_muerte (int indice_del_ciclo_de_muerte)
Starts the cell death process.
void registrar_microambiente (Microambiente *)
Registers the microenvironment with the cell.
void actualizar_voxel_del_microambiente ()
Updates the microenvironment voxel containing the cell.
void set_constantes_de_consumo_interno (double dt)
Sets constants for internal consumption.
Microambiente * get_microambiente (void)
Gets the microenvironment associated with this cell.
void simular_secrecion_y_consumo (double dt)
Simulates secretion and consumption of microenvironment substrates.
int get_indice_del_voxel_del_microambiente ()
Gets the index of the microenvironment voxel.
std::vector< double > & vector_de_densidades_mas_cercano (void)
Gets the closest density vector from the microenvironment.
std::vector< double > & gradiente_mas_cercano (int substrate_index)
Gets the gradient of a specific substrate.
void inicializar_celula ()
Initializes a cell with default properties.
void inicializar_celula_sana ()
Initializes a cell with healthy properties.
void mostrar_informacion_de_la_celula (std::ostream &os)
Outputs detailed cell information.
virtual ~Celula ()
Virtual destructor for proper inheritance.
Public Attributes
Motilidad motilidad
double tasa_de_asesinato
double tiempo_de_adhesion
double tasa_de_adhesion
double constante_elastica
double distancia_de_adhesion_maxima
double distancia_de_adhesion_minima
double saturacion_de_oncoproteina
double limite_de_oncoproteina
double diferencia_de_oncoproteina
double diferencia_de_adhesion
Public Attributes inherited from Celula
int voxel_del_microambiente
int voxel
std::string nombre
int tipo
int id
int indice
int madre
double tiempo_desde_el_ultimo_ciclo
double tiempo_desde_la_ultima_mecanica
double hora_del_ultimo_ciclo
double hora_de_la_ultima_mecanica
double hora_global
double tasa
bool adherida
Fenotipo fenotipo
Parametros parametros
Vector posicion
Vector velocidad
Vector desplazamiento
Celula * celula_adherida
Additional Inherited Members
Protected Attributes inherited from Celula
std::vector< double > temp_celula_fuente_sumidero_solver1
std::vector< double > temp_celula_fuente_sumidero_solver2
std::vector< double > temp_celula_fuente_sumidero_exportacion_solver1
std::vector< double > temp_celula_fuente_sumidero_exportacion_solver2
Vector velocidad_anterior
bool es_activa
Detailed Description
Specialized cell class representing a lymphocyte (immune cell)
Extends the base Celula class with immune-specific properties and behaviors, such as directed motility, cell adhesion, and the ability to trigger apoptosis in other cells (immune killing).
Cancer Research Context: This class enables modeling immune responses against cancer cells, including natural killer (NK) cell activity and T-cell responses. Lymphocytes can detect, adhere to, and potentially eliminate cancer cells, allowing researchers to study immune surveillance and cancer immunotherapy.
Definition at line 335 of file Celula.h.
Constructor & Destructor Documentation
Linfocito()
Linfocito::Linfocito ()
Constructor for Lymphocyte.
Constructor for the Linfocito (Lymphocyte) class.
Initializes a lymphocyte immune cell with specialized parameters for:
Migration behavior (motility)
Cell-cell adhesion and interaction
Cytotoxic activity against tumor cells
Limited lifespan
In cancer research, this class is crucial for modeling:
Anti-tumor immune responses
Immunotherapy mechanisms
Tumor immune evasion
Immune cell trafficking and infiltration
The lymphocyte maintains specialized parameters for detecting and killing tumor cells based on their oncoprotein expression levels.
Definition at line 1443 of file Celula.cpp.
References Ciclo::actualizar_mis_tasas_de_transicion(), Celula::actualizar_voxel_del_microambiente(), Muerte::agregar_ciclo_de_muerte(), apoptosis, apoptosis_parametros, Motilidad::bias_de_la_migracion, c, Fenotipo::ciclo, constante_elastica, diferencia_de_adhesion, diferencia_de_oncoproteina, distancia_de_adhesion_maxima, distancia_de_adhesion_minima, Constantes::dt_ciclo, Microambiente::encontrar_indice_de_densidad(), Ciclo_Modelo::encontrar_indice_de_la_fase(), Motilidad::es_movil, Celula::fenotipo, Mecanica::fuerza_de_adhesion_cc, Mecanica::fuerza_de_adhesion_co, Mecanica::fuerza_de_adhesion_mb, Mecanica::fuerza_de_repulsion_cc, Mecanica::fuerza_de_repulsion_co, Celula::get_microambiente(), Celula::hora_de_la_ultima_mecanica, Celula::hora_del_ultimo_ciclo, limite_de_oncoproteina, Fenotipo::mecanica, motilidad, Fenotipo::muerte, Celula::nombre, Parametros_globales::numero_id, pg, saturacion_de_oncoproteina, Fenotipo::secrecion, Ciclo::sync_con_ciclo_modelo(), tasa_de_adhesion, tasa_de_asesinato, Secrecion::tasas_de_consumo, Secrecion::tasas_de_secrecion, tiempo_de_adhesion, Motilidad::tiempo_de_persistencia, Parametros_globales::tiempo_total, Celula::tipo, Motilidad::velocidad_de_migracion, vida, and Constantes::viva.
~Linfocito()
virtual Linfocito::~Linfocito () inline virtual
Virtual destructor.
Definition at line 438 of file Celula.h.
Member Function Documentation
actualizar_vector_de_motilidad()
void Linfocito::actualizar_vector_de_motilidad (double dt, std::vector< Celula * > celulas_en_mi_voxel) virtual
Updates the lymphocyte's motility vector.
Parameters
dt Time step
celulas_en_mi_voxel Cells in the same voxel
Calculates a new migration direction based on:
Random motion component
Chemotactic bias (toward immunostimulatory factors)
Current motility state
Time persistence
In cancer research, this models:
Immune cell chemotaxis toward tumor sites
Scanning behavior within the tumor microenvironment
Lymphocyte trafficking and infiltration dynamics
Parameters
dt Time step size
celulas_en_mi_voxel Vector of cell pointers sharing the same voxel
Reimplemented from Celula.
Definition at line 1535 of file Celula.cpp.
References axpy(), Motilidad::bias_de_la_migracion, Motilidad::bias_de_la_migracion_direccion, Motilidad::es_movil, motilidad, motilidad_de_linfocito(), Vector::normalizame(), RNG::RandomNumber(), rng, Motilidad::tiempo_de_persistencia, v, Motilidad::vector_de_motilidad, Celula::velocidad, Motilidad::velocidad_de_migracion, Vector::x, Vector::y, and Vector::z.
adherir_celula()
void Linfocito::adherir_celula (Celula * celula_objetivo)
Adheres to a target cell.
Creates an attachment between the lymphocyte and a target cell.
Parameters
celula_objetivo Target cell
Establishes a bidirectional link between the lymphocyte and its target, setting the adherida (attached) flag in both cells and cross-referencing them.
In cancer research, this models:
Immune synapse formation
T-cell engagement with tumor cells
Physical coupling preceding cytotoxic action
Parameters
celula_objetivo Pointer to the target cell to attach to
Definition at line 1812 of file Celula.cpp.
References Celula::adherida, and Celula::celula_adherida.
Referenced by intentar_adherirse().
avanzar_linfocito()
void Linfocito::avanzar_linfocito (double dt, std::vector< Celula * > celulas_en_mi_voxel) virtual
Advances lymphocyte-specific behaviors.
Controls lymphocyte behavior including attachment, detachment, and killing.
Parameters
dt Time step
celulas_en_mi_voxel Cells in the same voxel
Main method governing lymphocyte interaction with target cells, including:
Force-based movement toward attached cells
Attempts to induce apoptosis in tumor cells
Detachment after killing or timeout
Seeking new target cells
In cancer research, this models:
Cytotoxic T-cell killing mechanisms
Immune synapse formation and dynamics
Immune cell serial killing behavior
Tumor cell-immune cell interactions
Parameters
dt Time step size
celulas_en_mi_voxel Vector of cell pointers sharing the same voxel
Reimplemented from Celula.
Definition at line 1653 of file Celula.cpp.
References Celula::adherida, axpy(), Celula::celula_adherida, chequear_vecinos_para_adherirse(), constante_elastica, desencadenar_apoptosis(), Celula::desplazamiento, Motilidad::es_movil, Celula::fenotipo, intento_de_apoptosis(), motilidad, Muerte::muerta, Fenotipo::muerte, Celula::posicion, RNG::RandomNumber(), rng, soltar_celula(), tiempo_de_adhesion, Celula::tipo, and Celula::velocidad.
chequear_vecinos_para_adherirse()
bool Linfocito::chequear_vecinos_para_adherirse (std::vector< Celula * > celulas_en_mi_voxel, double dt)
Checks neighboring cells for potential adhesion.
Scans neighboring cells for potential targets to attach to.
Parameters
celulas_en_mi_voxel Cells in the same voxel
dt Time step
Returns
Success status
Evaluates cells in the same voxel as candidates for attachment, based on oncoprotein expression levels and proximity.
In cancer research, this models:
Immune cell surveillance
Target recognition based on tumor-associated antigens
Local scanning behavior of immune cells
Parameters
celulas_en_mi_voxel Vector of cell pointers sharing the same voxel
dt Time step size
Returns
Boolean indicating whether attachment was successful
Definition at line 1863 of file Celula.cpp.
References Celula::adherida, and intentar_adherirse().
Referenced by avanzar_linfocito().
desencadenar_apoptosis()
bool Linfocito::desencadenar_apoptosis (Celula * celula_adherida)
Triggers apoptosis in an attached cell.
Initiates apoptosis in a target cell.
Parameters
celula_adherida Attached cell
Returns
Success status
Activates the apoptosis death pathway in the target cell.
In cancer research, this models:
Cytotoxic T-cell induced tumor cell death
Immune-mediated tumor control
Programmed cell death mechanisms
Parameters
celula_adherida Pointer to the target cell
Returns
Boolean indicating success of apoptosis initiation
Definition at line 1784 of file Celula.cpp.
References Celula::celula_adherida, Celula::comenzar_muerte(), Muerte::encontrar_indice_del_ciclo_de_muerte(), Celula::fenotipo, Muerte::muerta, and Fenotipo::muerte.
Referenced by avanzar_linfocito().
es_movil()
void Linfocito::es_movil (bool valor) virtual
Sets the lymphocyte's mobility.
Sets the motility state of the lymphocyte.
Parameters
valor Mobility flag
Controls whether the lymphocyte can actively migrate or not. This is used when lymphocytes are attached to target cells or during other states where movement should be restricted.
In cancer research, this enables modeling:
Immune cell arrest during engagement with tumor cells
Transition between scanning and effector functions
Parameters
valor Boolean value indicating whether the cell should be motile
Reimplemented from Celula.
Definition at line 1514 of file Celula.cpp.
References Motilidad::es_movil, and motilidad.
intentar_adherirse()
bool Linfocito::intentar_adherirse (Celula * celula_objetivo, double dt)
Attempts to adhere to a target cell.
Attempts to adhere to a specific target cell.
Parameters
celula_objetivo Target cell
dt Time step
Returns
Success status
Determines whether attachment should occur based on:
Target cell's oncoprotein expression level
Distance between the cells
Random chance modulated by adhesion rate
In cancer research, this models:
Antigen-dependent recognition of tumor cells
Spatial constraints in immune-tumor interaction
Probabilistic nature of immune synapse formation
Parameters
celula_objetivo Pointer to the potential target cell
dt Time step size
Returns
Boolean indicating whether attachment was successful
Definition at line 1902 of file Celula.cpp.
References Celula::adherida, adherir_celula(), Celula::desplazamiento, diferencia_de_adhesion, diferencia_de_oncoproteina, distancia_de_adhesion_maxima, Celula::fenotipo, limite_de_oncoproteina, Muerte::muerta, Fenotipo::muerte, norma(), Secrecion::oncoproteina, Celula::posicion, RNG::RandomNumber(), rng, Fenotipo::secrecion, and tasa_de_adhesion.
Referenced by chequear_vecinos_para_adherirse().
intento_de_apoptosis()
bool Linfocito::intento_de_apoptosis (Celula * celula_adherida, double dt)
Attempts to trigger apoptosis in an attached cell.
Determines if a lymphocyte should induce apoptosis in a target cell.
Parameters
celula_adherida Attached cell
dt Time step
Returns
Success status
Makes a probabilistic decision to kill a target cell based on:
Target cell's oncoprotein expression level
Lymphocyte's killing rate
Time step size
In cancer research, this models:
Immune recognition of cancer cells
Stochastic nature of cytotoxic activity
Tumor immunogenicity and immune evasion
Tumor antigen threshold effects
Parameters
celula_adherida Pointer to the attached target cell
dt Time step size
Returns
Boolean indicating whether killing should occur
Definition at line 1738 of file Celula.cpp.
References Celula::celula_adherida, diferencia_de_oncoproteina, Celula::fenotipo, limite_de_oncoproteina, Secrecion::oncoproteina, RNG::RandomNumber(), rng, Fenotipo::secrecion, and tasa_de_asesinato.
Referenced by avanzar_linfocito().
motilidad_de_linfocito()
void Linfocito::motilidad_de_linfocito (double dt, std::vector< Celula * > celulas_en_mi_voxel)
Processes lymphocyte motility behavior.
Determines the lymphocyte's chemotactic response.
Parameters
dt Time step
celulas_en_mi_voxel Cells in the same voxel
Sets the direction of biased migration based on:
Gradients of immunostimulatory factors
Presence of nearby cells
Cell type in the current voxel
In cancer research, this models:
Directed migration toward inflammatory signals
Immune cell arrest during target cell engagement
Lymphocyte behavior in different tumor regions
Parameters
dt Time step size
celulas_en_mi_voxel Vector of cell pointers sharing the same voxel
Definition at line 1594 of file Celula.cpp.
References Motilidad::bias_de_la_migracion_direccion, Microambiente::encontrar_indice_de_densidad(), Motilidad::es_movil, Celula::get_microambiente(), Celula::gradiente_mas_cercano(), motilidad, Vector::normalizame(), Celula::tipo, v, Vector::x, Vector::y, and Vector::z.
Referenced by actualizar_vector_de_motilidad().
soltar_celula()
void Linfocito::soltar_celula (Celula * celula_objetivo)
Releases an attached cell.
Breaks the attachment between the lymphocyte and a target cell.
Parameters
celula_objetivo Cell to release
Releases the bidirectional link between the lymphocyte and its target, clearing the adherida (attached) flag and references in both cells.
In cancer research, this models:
Immune synapse dissolution
T-cell detachment after killing or unsuccessful engagement
Serial killing behavior of cytotoxic T-cells
Parameters
celula_objetivo Pointer to the target cell to detach from
Definition at line 1836 of file Celula.cpp.
References Celula::adherida, and Celula::celula_adherida.
Referenced by avanzar_linfocito().
Member Data Documentation
constante_elastica
double Linfocito::constante_elastica
Definition at line 342 of file Celula.h.
Referenced by avanzar_linfocito(), and Linfocito().
diferencia_de_adhesion
double Linfocito::diferencia_de_adhesion
Definition at line 348 of file Celula.h.
Referenced by intentar_adherirse(), and Linfocito().
diferencia_de_oncoproteina
double Linfocito::diferencia_de_oncoproteina
Definition at line 347 of file Celula.h.
Referenced by intentar_adherirse(), intento_de_apoptosis(), and Linfocito().
distancia_de_adhesion_maxima
double Linfocito::distancia_de_adhesion_maxima
Definition at line 343 of file Celula.h.
Referenced by intentar_adherirse(), and Linfocito().
distancia_de_adhesion_minima
double Linfocito::distancia_de_adhesion_minima
Definition at line 344 of file Celula.h.
Referenced by Linfocito().
limite_de_oncoproteina
double Linfocito::limite_de_oncoproteina
Definition at line 346 of file Celula.h.
Referenced by intentar_adherirse(), intento_de_apoptosis(), and Linfocito().
motilidad
Motilidad Linfocito::motilidad
Definition at line 338 of file Celula.h.
Referenced by actualizar_vector_de_motilidad(), avanzar_linfocito(), es_movil(), Linfocito(), and motilidad_de_linfocito().
saturacion_de_oncoproteina
double Linfocito::saturacion_de_oncoproteina
Definition at line 345 of file Celula.h.
Referenced by Linfocito().
tasa_de_adhesion
double Linfocito::tasa_de_adhesion
Definition at line 341 of file Celula.h.
Referenced by intentar_adherirse(), and Linfocito().
tasa_de_asesinato
double Linfocito::tasa_de_asesinato
Definition at line 339 of file Celula.h.
Referenced by intento_de_apoptosis(), and Linfocito().
tiempo_de_adhesion
double Linfocito::tiempo_de_adhesion
Definition at line 340 of file Celula.h.
Referenced by avanzar_linfocito(), and Linfocito().
The documentation for this class was generated from the following files:
Celula.h
Celula.cpp