Cancer Cell Agent Simulation: Celula Class Reference
Celula Class Reference
Base class for cell agents in the simulation.
#include <Celula.h>
Public Member Functions
Celula ()
Default constructor for Cell.
void actualizar_volumen (Fenotipo &fenotipo, double dt)
Updates the cell volume based on growth/shrinkage rates.
void actualizar_parametros_de_celula_y_muerte_con_o2 (Fenotipo &fenotipo, double dt)
Updates cell and death parameters based on oxygen concentration.
void actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina (Fenotipo &fenotipo, double dt)
Updates cell and death parameters based on oxygen and oncoprotein.
void avanzar_funciones_del_fenotipo (double hora_global, double dt_ciclo)
Advances the cell's phenotypic functions over time.
void avanzar_funciones_del_fenotipo_con_O2 (double hora_global, double dt_ciclo)
Advances the cell's phenotypic functions considering oxygen.
void avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina (double hora_global, double dt_ciclo)
Advances phenotypic functions considering oxygen and oncoprotein.
Celula * dividir ()
Creates a daughter cell through division.
void morir (int indice)
Initiates cell death process.
bool set_posicion (double x, double y, double z)
Sets the cell's position using coordinates.
bool set_posicion (Vector posicion)
Sets the cell's position using a Vector.
void agregar_potenciales (Celula *otra_celula)
Adds mechanical potentials from another cell.
void agregar_potenciales_mb ()
Adds mechanical potentials from microenvironment boundary.
void agregar_potenciales_mb_2 ()
Alternative implementation for boundary potentials.
void actualizar_posicion (double dt)
Updates cell position based on velocity.
void comenzar_muerte (int indice_del_ciclo_de_muerte)
Starts the cell death process.
void registrar_microambiente (Microambiente *)
Registers the microenvironment with the cell.
void actualizar_voxel_del_microambiente ()
Updates the microenvironment voxel containing the cell.
void set_constantes_de_consumo_interno (double dt)
Sets constants for internal consumption.
Microambiente * get_microambiente (void)
Gets the microenvironment associated with this cell.
void simular_secrecion_y_consumo (double dt)
Simulates secretion and consumption of microenvironment substrates.
int get_indice_del_voxel_del_microambiente ()
Gets the index of the microenvironment voxel.
std::vector< double > & vector_de_densidades_mas_cercano (void)
Gets the closest density vector from the microenvironment.
std::vector< double > & gradiente_mas_cercano (int substrate_index)
Gets the gradient of a specific substrate.
void inicializar_celula ()
Initializes a cell with default properties.
void inicializar_celula_sana ()
Initializes a cell with healthy properties.
void mostrar_informacion_de_la_celula (std::ostream &os)
Outputs detailed cell information.
virtual void es_movil (bool valor)
Sets whether the cell is mobile (overridden in derived classes)
virtual void actualizar_vector_de_motilidad (double dt, std::vector< Celula * > celulas_en_mi_voxel)
Updates the cell's motility vector (overridden in derived classes)
virtual void avanzar_linfocito (double dt, std::vector< Celula * > celulas_en_mi_voxel)
Advances lymphocyte-specific behaviors (overridden in derived classes)
virtual ~Celula ()
Virtual destructor for proper inheritance.
Public Attributes
int voxel_del_microambiente
int voxel
std::string nombre
int tipo
int id
int indice
int madre
double tiempo_desde_el_ultimo_ciclo
double tiempo_desde_la_ultima_mecanica
double hora_del_ultimo_ciclo
double hora_de_la_ultima_mecanica
double hora_global
double tasa
bool adherida
Fenotipo fenotipo
Parametros parametros
Vector posicion
Vector velocidad
Vector desplazamiento
Celula * celula_adherida
Protected Attributes
std::vector< double > temp_celula_fuente_sumidero_solver1
std::vector< double > temp_celula_fuente_sumidero_solver2
std::vector< double > temp_celula_fuente_sumidero_exportacion_solver1
std::vector< double > temp_celula_fuente_sumidero_exportacion_solver2
Vector velocidad_anterior
bool es_activa
Private Attributes
Microambiente * microambiente
Detailed Description
Base class for cell agents in the simulation.
Represents individual cells with physical properties, behavioral characteristics, and interaction capabilities. Each cell has position, velocity, size, and various phenotypic states. Cells can interact with the microenvironment, move according to physical forces, divide, die, and secrete/consume substances.
Cancer Research Context: This class is the foundation for modeling cancer cells, capturing their behavior, proliferation patterns, and response to environmental factors like oxygen. This enables researchers to study tumor growth dynamics and heterogeneity.
Definition at line 66 of file Celula.h.
Constructor & Destructor Documentation
Celula()
Celula::Celula ()
Default constructor for Cell.
Default constructor for the Cell class.
Initializes a cell with default properties
Initializes a cell with default parameters and properties. This creates an inactive cell that needs further initialization before being used in simulation. In cancer research, this provides the basic foundation for modeling both normal and cancer cells with their respective behaviors.
Definition at line 42 of file Celula.cpp.
References adherida, celula_adherida, es_activa, get_microambiente_default(), hora_de_la_ultima_mecanica, hora_del_ultimo_ciclo, indice, madre, microambiente, nombre, posicion, registrar_microambiente(), tiempo_desde_el_ultimo_ciclo, tiempo_desde_la_ultima_mecanica, tipo, voxel, Vector::x, Vector::y, and Vector::z.
~Celula()
virtual Celula::~Celula () inline virtual
Virtual destructor for proper inheritance.
Definition at line 317 of file Celula.h.
Member Function Documentation
actualizar_parametros_de_celula_y_muerte_con_o2()
void Celula::actualizar_parametros_de_celula_y_muerte_con_o2 (Fenotipo & fenotipo, double dt)
Updates cell and death parameters based on oxygen concentration.
Updates cell cycle and death parameters based on local oxygen concentration.
Parameters
fenotipo The cell's phenotype
dt Time step for the update
This method implements the cell's response to oxygen levels in the microenvironment, which is critical for modeling cancer cell behavior in hypoxic conditions. The method:
Identifies the appropriate cell cycle model (Ki67 or simple live/dead)
Retrieves local oxygen concentration
Adjusts proliferation rates based on oxygen availability (modeling hypoxia effects)
Adjusts necrosis rates when oxygen is severely limited
This is particularly important for cancer research as hypoxia influences tumor growth, migration, and treatment response.
Parameters
fenotipo The cell phenotype containing cycle and death parameters
dt Time step size for the update (in minutes)
Definition at line 154 of file Celula.cpp.
References Fenotipo::ciclo, Constantes::ciclo_de_muerte_necrosis, Constantes::ciclo_Ki67, Constantes::ciclo_vida, Ciclo_Modelo::codigo, Microambiente::encontrar_indice_de_densidad(), Ciclo_Modelo::encontrar_indice_de_la_fase(), Muerte::encontrar_indice_del_ciclo_de_muerte(), fenotipo, Constantes::Ki67_negativa, Constantes::Ki67_positiva_premitotica, microambiente, Muerte::muerta, Fenotipo::muerte, Parametros::o2_limite_de_proliferacion, Parametros::o2_necrosis_limite, Parametros::o2_necrosis_max, Parametros::o2_saturacion_para_la_proliferacion, parametros, Ciclo::pCiclo_Modelo, Ciclo_Modelo::tasa_de_transicion(), Parametros::tasa_necrosis_max, Muerte::tasas, Ciclo::tasas_de_transicion, vector_de_densidades_mas_cercano(), and Constantes::viva.
Referenced by avanzar_funciones_del_fenotipo(), and avanzar_funciones_del_fenotipo_con_O2().
actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina()
void Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina (Fenotipo & fenotipo, double dt)
Updates cell and death parameters based on oxygen and oncoprotein.
Updates cell cycle and death parameters based on oxygen and oncoprotein levels.
Parameters
fenotipo The cell's phenotype
dt Time step for the update
Similar to actualizar_parametros_de_celula_y_muerte_con_o2, but also incorporates the effect of oncoprotein expression on cell cycle progression. This method is specific to modeling cancer cells (type 0) and provides a mechanism to simulate oncogene-driven proliferation, which can be modulated by the microenvironment.
Key cancer research aspects:
Combines hypoxia response with oncogene activity
Models how oncogene expression can override normal oxygen dependency
Simulates tumor growth drivers at the molecular and microenvironmental levels
Parameters
fenotipo The cell phenotype containing cycle, death and secretion parameters
dt Time step size for the update (in minutes)
Definition at line 224 of file Celula.cpp.
References Ciclo::actualizar_mis_tasas_de_transicion(), Fenotipo::ciclo, Constantes::ciclo_de_muerte_necrosis, Constantes::ciclo_Ki67, Constantes::ciclo_vida, Ciclo_Modelo::codigo, Microambiente::encontrar_indice_de_densidad(), Ciclo_Modelo::encontrar_indice_de_la_fase(), Muerte::encontrar_indice_del_ciclo_de_muerte(), fenotipo, Constantes::Ki67_negativa, Constantes::Ki67_positiva_premitotica, microambiente, Muerte::muerta, Fenotipo::muerte, Parametros::o2_limite_de_proliferacion, Parametros::o2_necrosis_limite, Parametros::o2_necrosis_max, Parametros::o2_saturacion_para_la_proliferacion, Secrecion::oncoproteina, parametros, Ciclo::pCiclo_Modelo, Fenotipo::secrecion, Ciclo::tasa_aleatoria, Parametros::tasa_necrosis_max, Muerte::tasas, tipo, vector_de_densidades_mas_cercano(), and Constantes::viva.
Referenced by avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina().
actualizar_posicion()
void Celula::actualizar_posicion (double dt)
Updates cell position based on velocity.
Updates the cell's position based on accumulated velocity.
Parameters
dt Time step for the update
Applies the calculated velocity to update the cell's position using a modified Euler integration scheme. This method also handles periodic boundary conditions and updates the cell's voxel assignment.
In cancer research, this method is critical for modeling:
Tumor growth patterns and spatial organization
Cell migration and invasion
Mechanical interactions within the tumor microenvironment
Spatial heterogeneity in tumor tissue
Parameters
dt Time step size for the update
Definition at line 1005 of file Celula.cpp.
References actualizar_voxel_del_microambiente(), posicion, set_posicion(), velocidad, velocidad_anterior, Vector::x, Vector::y, and Vector::z.
actualizar_vector_de_motilidad()
virtual void Celula::actualizar_vector_de_motilidad (double dt, std::vector< Celula * > celulas_en_mi_voxel) inline virtual
Updates the cell's motility vector (overridden in derived classes)
Parameters
dt Time step
celulas_en_mi_voxel Cells in the same voxel
Reimplemented in Linfocito.
Definition at line 304 of file Celula.h.
actualizar_volumen()
void Celula::actualizar_volumen (Fenotipo & fenotipo, double dt)
Updates the cell volume based on growth/shrinkage rates.
Updates the cell volume according to phenotype parameters.
Parameters
fenotipo The cell's phenotype containing volume properties
dt Time step for the update
Manages fluid and solid volume components for the cell, including nuclear and cytoplasmic components. This method is critical for cancer modeling as aberrant cell growth is a hallmark of cancer.
The method handles:
Changes in fluid fraction
Nuclear and cytoplasmic volume changes
Volume-based geometry updates
Calcification fraction changes
Parameters
fenotipo The cell phenotype containing volume parameters
dt Time step size for the update (in minutes)
Definition at line 86 of file Celula.cpp.
References Geometria::actualizar(), Volumen::citoplasma_tasa_de_cambio, Volumen::citoplasmatico, Volumen::citoplasmatico_fluido, Volumen::citoplasmatico_solido, fenotipo, Volumen::fluido, Volumen::fluido_tasa_de_cambio, Volumen::fraccion_calcificada, Volumen::fraccion_de_fluido, Fenotipo::geometria, Volumen::nuclear, Volumen::nuclear_fluido, Volumen::nuclear_solido, Volumen::nucleo_tasa_de_cambio, Volumen::solido, Volumen::target_citoplasma_solido, Volumen::target_fraccion_fluido, Volumen::target_nucleo_solido, Volumen::target_relacion_citoplasma_nucleo, Volumen::tasa_de_calcificacion, Volumen::total, and Fenotipo::volumen.
Referenced by avanzar_funciones_del_fenotipo(), avanzar_funciones_del_fenotipo_con_O2(), and avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina().
actualizar_voxel_del_microambiente()
void Celula::actualizar_voxel_del_microambiente ()
Updates the microenvironment voxel containing the cell.
Updates the cell's voxel index in the microenvironment.
Maps the cell to the appropriate voxel in the microenvironment grid based on its current position. This is essential for spatial interactions with the biochemical environment.
In cancer research, this enables modeling:
Local variations in oxygen and nutrients within tumors
Spatial gradients of signaling molecules
Regional differences in treatment efficacy
Definition at line 1147 of file Celula.cpp.
References es_activa, Grillado_General::es_valida_la_posicion(), Microambiente::indice_del_voxel_mas_cercano(), Microambiente::mgrilla, microambiente, posicion, voxel_del_microambiente, Vector::x, Vector::y, and Vector::z.
Referenced by actualizar_posicion(), dividir(), inicializar_celula(), inicializar_celula_sana(), and Linfocito::Linfocito().
agregar_potenciales()
void Celula::agregar_potenciales (Celula * otra_celula)
Adds mechanical potentials from another cell.
Calculates mechanical interaction forces between two cells.
Parameters
otra_celula Another cell to interact with
Implements the core mechanical interactions between cells, including:
Repulsion when cells overlap (preventing excessive compression)
Adhesion when cells are within adhesion distance
These forces are critical for cancer modeling as they determine:
Tumor structure and packing density
Mechanical stress in the tumor microenvironment
Definition at line 696 of file Celula.cpp.
References desplazamiento, Mecanica::distancia_de_adhesion_maxima_relativa, fenotipo, Mecanica::fuerza_de_adhesion_cc, Mecanica::fuerza_de_adhesion_co, Mecanica::fuerza_de_repulsion_cc, Mecanica::fuerza_de_repulsion_co, Fenotipo::geometria, id, Fenotipo::mecanica, pg, posicion, Geometria::radio, Parametros_globales::rango_en_X, Parametros_globales::rango_en_Y, Parametros_globales::rango_en_Z, tipo, velocidad, Vector::x, Vector::y, and Vector::z.
agregar_potenciales_mb()
void Celula::agregar_potenciales_mb ()
Adds mechanical potentials from microenvironment boundary.
Calculates and applies bottom boundary mechanical interactions.
Computes the mechanical forces between the cell and the bottom boundary of the simulation domain. This includes both adhesive and repulsive forces based on distance, which are then applied to the cell's velocity.
In cancer research, this method is significant for modeling:
Tumor-basement membrane interactions
Cancer cell adhesion to boundaries (critical in invasion modeling)
Mechanical constraints on tumor growth
Boundary effects on tumor morphology
The method calculates adhesion and repulsion forces separately and combines them, with forces becoming stronger at closer distances following a quadratic relationship.
Definition at line 798 of file Celula.cpp.
References desplazamiento, Mecanica::distancia_de_adhesion_maxima_relativa, fenotipo, Mecanica::fuerza_de_adhesion_mb, Mecanica::fuerza_de_repulsion_mb, Fenotipo::geometria, Parametros_globales::interactuar_con_mb, Fenotipo::mecanica, pg, posicion, Geometria::radio, Parametros_globales::rango_en_Z, velocidad, Vector::x, Vector::y, and Vector::z.
agregar_potenciales_mb_2()
void Celula::agregar_potenciales_mb_2 ()
Alternative implementation for boundary potentials.
Calculates and applies mechanical interactions with all domain boundaries.
Computes the mechanical forces between the cell and all six boundaries of the simulation domain (X, Y, Z). For each non-periodic boundary, this method calculates both adhesive and repulsive forces based on distance, then applies these forces to the cell's velocity.
In cancer research, this comprehensive boundary interaction model is crucial for:
Studying tumor growth constraints in confined environments
Modeling tumor-basement membrane interactions in all directions
Simulating cancer cell invasion through tissue boundaries
Investigating the effects of spatial constraints on tumor morphology
Replicating in vitro experimental setups with defined boundaries
The method checks each boundary separately and only applies forces for non-periodic boundaries when the cell is within interaction distance, collecting all relevant displacement vectors and applying forces to each.
Definition at line 864 of file Celula.cpp.
References axpy(), Parametros_globales::condiciones_de_periodicidad_x, Parametros_globales::condiciones_de_periodicidad_y, Parametros_globales::condiciones_de_periodicidad_z, desplazamiento, Mecanica::distancia_de_adhesion_maxima_relativa, fenotipo, Mecanica::fuerza_de_adhesion_mb, Mecanica::fuerza_de_repulsion_mb, Fenotipo::geometria, Fenotipo::mecanica, pg, posicion, Geometria::radio, Parametros_globales::rango_en_X, Parametros_globales::rango_en_Y, Parametros_globales::rango_en_Z, velocidad, Vector::x, Vector::y, and Vector::z.
avanzar_funciones_del_fenotipo()
void Celula::avanzar_funciones_del_fenotipo (double hora_global, double dt_ciclo)
Advances the cell's phenotypic functions over time.
Advances cell phenotype functions based on standard model.
Parameters
hora_global Current simulation time
dt_ciclo Time step for the cycle update
This method updates the cell's phenotype over time, handling:
Cell cycle progression
Volume changes
Death processes
Division flagging
Cell removal flagging
It uses oxygen-dependent parameters but doesn't directly check oxygen levels. In cancer research, this represents the basic mechanisms of tumor growth and cell turnover.
Parameters
hora_global Current simulation time
dt_ciclo Time step for cycle advancement
Definition at line 299 of file Celula.cpp.
References actualizar_parametros_de_celula_y_muerte_con_o2(), Ciclo::actualizar_volumen(), actualizar_volumen(), Ciclo::avanzar_en_el_ciclo(), Volumen::cambio_el_volumen, celulas_listas_para_dividirse, celulas_listas_para_remover, Muerte::chequear_muerte(), Fenotipo::ciclo, Muerte::ciclo_actual(), Ciclo::fase_actual(), fenotipo, Ciclo::flagged_para_dividirse, Ciclo::flagged_para_remover, Fase::funcion_de_entrada, Muerte::muerta, Fenotipo::muerte, Secrecion::multiplicar_los_consumos_por_un_factor(), Muerte::parametros_actuales(), Fenotipo::secrecion, Secrecion::set_todas_las_secreciones_a_cero(), Ciclo::sync_con_ciclo_modelo(), Ciclo::tasas_de_transicion, tiempo_desde_el_ultimo_ciclo, and Fenotipo::volumen.
avanzar_funciones_del_fenotipo_con_O2()
void Celula::avanzar_funciones_del_fenotipo_con_O2 (double hora_global, double dt_ciclo)
Advances the cell's phenotypic functions considering oxygen.
Advances cell phenotype functions with explicit oxygen dependency.
Parameters
hora_global Current simulation time
dt_ciclo Time step for the cycle update
Enhanced version of the basic phenotype advancement that explicitly checks oxygen levels to determine if the cell can proliferate. This models the common cancer phenotype where cells stop dividing in hypoxic regions but may still survive.
Key cancer research aspects:
Models oxygen-dependent cell cycle progression
Implements different behavior for dead vs. living cells
Captures cellular adaptation to hypoxic tumor microenvironments
Parameters
hora_global Current simulation time
dt_ciclo Time step for cycle advancement
Definition at line 360 of file Celula.cpp.
References actualizar_parametros_de_celula_y_muerte_con_o2(), Ciclo::actualizar_volumen(), actualizar_volumen(), Ciclo::avanzar_en_el_ciclo(), Volumen::cambio_el_volumen, celulas_listas_para_dividirse, celulas_listas_para_remover, Muerte::chequear_muerte(), Fenotipo::ciclo, Muerte::ciclo_actual(), Microambiente::encontrar_indice_de_densidad(), Ciclo::fase_actual(), fenotipo, Ciclo::flagged_para_dividirse, Ciclo::flagged_para_remover, Fase::funcion_de_entrada, microambiente, Muerte::muerta, Fenotipo::muerte, Secrecion::multiplicar_los_consumos_por_un_factor(), Parametros::o2_limite_de_proliferacion, parametros, Muerte::parametros_actuales(), Fenotipo::secrecion, Secrecion::set_todas_las_secreciones_a_cero(), Ciclo::sync_con_ciclo_modelo(), Ciclo::tasas_de_transicion, tiempo_desde_el_ultimo_ciclo, vector_de_densidades_mas_cercano(), and Fenotipo::volumen.
avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina()
void Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina (double hora_global, double dt_ciclo)
Advances phenotypic functions considering oxygen and oncoprotein.
Advances cell phenotype functions considering oxygen and oncoprotein.
Parameters
hora_global Current simulation time
dt_ciclo Time step for the cycle update
Most sophisticated version of phenotype advancement that takes into account:
Oxygen availability
Oncoprotein expression
Cell attachment status
Cell type specific behaviors (especially for lymphocytes)
This method is particularly important for cancer research because it integrates:
Molecular factors (oncoprotein)
Microenvironmental factors (oxygen)
Cellular interactions (attachment)
Cell-specific behaviors that may vary between tumor and immune cells
Parameters
hora_global Current simulation time
dt_ciclo Time step for cycle advancement
Definition at line 435 of file Celula.cpp.
References actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), Ciclo::actualizar_volumen(), actualizar_volumen(), adherida, Ciclo::avanzar_en_el_ciclo(), Volumen::cambio_el_volumen, celula_adherida, celulas_listas_para_dividirse, celulas_listas_para_remover, Muerte::chequear_muerte(), Fenotipo::ciclo, Muerte::ciclo_actual(), Microambiente::encontrar_indice_de_densidad(), es_movil(), Ciclo::fase_actual(), fenotipo, Ciclo::flagged_para_dividirse, Ciclo::flagged_para_remover, Fase::funcion_de_entrada, Ciclo::indice_de_la_fase_actual, microambiente, Muerte::muerta, Fenotipo::muerte, Secrecion::multiplicar_los_consumos_por_un_factor(), Parametros::o2_limite_de_proliferacion, parametros, Muerte::parametros_actuales(), Fenotipo::secrecion, Secrecion::set_todas_las_secreciones_a_cero(), Ciclo::sync_con_ciclo_modelo(), Muerte::tasas, Ciclo::tasas_de_transicion, Ciclo::tiempo_acumulado_en_la_fase, tiempo_desde_el_ultimo_ciclo, tipo, vector_de_densidades_mas_cercano(), and Fenotipo::volumen.
avanzar_linfocito()
virtual void Celula::avanzar_linfocito (double dt, std::vector< Celula * > celulas_en_mi_voxel) inline virtual
Advances lymphocyte-specific behaviors (overridden in derived classes)
Parameters
dt Time step
celulas_en_mi_voxel Cells in the same voxel
Reimplemented in Linfocito.
Definition at line 312 of file Celula.h.
comenzar_muerte()
void Celula::comenzar_muerte (int indice_del_ciclo_de_muerte)
Starts the cell death process.
Initiates the cell death process.
Parameters
indice_del_ciclo_de_muerte Index of the death cycle
Transitions the cell to a death pathway by synchronizing with the appropriate death cycle model, resetting the cell's phase, and adjusting its secretion rates. For lymphocytes, also handles detachment from target cells.
In cancer research, this method is critical for modeling:
Cell death in response to therapy
Programmed cell death (apoptosis) mechanisms
Stress-induced cell death (necrosis)
Cell clearance from the tumor microenvironment
Immune cell detachment after target cell engagement
Parameters
indice_del_ciclo_de_muerte Index of the death cycle to initiate
Definition at line 1057 of file Celula.cpp.
References adherida, celula_adherida, Fenotipo::ciclo, Muerte::ciclo_actual(), Muerte::comenzar_muerte(), es_movil(), Ciclo::fase_actual(), fenotipo, Fase::funcion_de_entrada, Ciclo::indice_de_la_fase_actual, Muerte::muerta, Fenotipo::muerte, Secrecion::multiplicar_los_consumos_por_un_factor(), Muerte::parametros_actuales(), Fenotipo::secrecion, Secrecion::set_todas_las_secreciones_a_cero(), Ciclo::sync_con_ciclo_modelo(), Ciclo::tiempo_acumulado_en_la_fase, tipo, and Fenotipo::volumen.
Referenced by Linfocito::desencadenar_apoptosis().
dividir()
Celula * Celula::dividir ()
Creates a daughter cell through division.
Returns
Pointer to the newly created daughter cell
Definition at line 600 of file Celula.cpp.
References Geometria::actualizar(), Ciclo::actualizar_mis_tasas_de_transicion(), actualizar_voxel_del_microambiente(), adherida, Fenotipo::ciclo, crear_celula(), Parametros_globales::crecer_al_costado, Volumen::dividir(), fenotipo, Fenotipo::geometria, hora_de_la_ultima_mecanica, hora_del_ultimo_ciclo, id, madre, nombre, RNG::NormalRandom_CM(), parametros, pg, posicion, Geometria::radio, RNG::RandomNumber(), rng, set_posicion(), Ciclo::tasa_aleatoria, tipo, Fenotipo::volumen, Vector::x, Vector::y, and Vector::z.
es_movil()
virtual void Celula::es_movil (bool valor) inline virtual
Sets whether the cell is mobile (overridden in derived classes)
Parameters
valor Mobility flag
Reimplemented in Linfocito.
Definition at line 296 of file Celula.h.
Referenced by avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), and comenzar_muerte().
get_indice_del_voxel_del_microambiente()
int Celula::get_indice_del_voxel_del_microambiente (void)
Gets the index of the microenvironment voxel.
Gets the cell's voxel index in the microenvironment.
Returns
Voxel index
Definition at line 1217 of file Celula.cpp.
References voxel_del_microambiente.
get_microambiente()
Microambiente * Celula::get_microambiente (void)
Gets the microenvironment associated with this cell.
Gets the cell's microenvironment.
Returns
Pointer to the microenvironment
Definition at line 1207 of file Celula.cpp.
References microambiente.
Referenced by Linfocito::Linfocito(), and Linfocito::motilidad_de_linfocito().
gradiente_mas_cercano()
std::vector< double > & Celula::gradiente_mas_cercano (int indice_del_sustrato)
Gets the gradient of a specific substrate.
Gets the nearest gradient vector for a specific substrate.
Parameters
substrate_index Index of the substrate
Returns
Reference to gradient vector
Provides access to the spatial gradient of a substrate at the cell's location This is used for processes like chemotaxis.
In cancer research, this enables modeling:
Directional cell migration in response to chemical gradients
Cell polarization based on microenvironmental cues
Parameters
indice_del_sustrato Index of the substrate in the microenvironment
Returns
Reference to the gradient vector
Definition at line 1252 of file Celula.cpp.
References microambiente, Microambiente::vector_de_gradientes(), and voxel_del_microambiente.
Referenced by Linfocito::motilidad_de_linfocito().
inicializar_celula()
void Celula::inicializar_celula ()
Initializes a cell with default properties.
Initializes a cell with default parameters.
Sets up the cell's cycle model, secretion/consumption rates, volume change rates, death pathways, and other key properties.
In cancer research, this method establishes:
Baseline metabolic parameters (oxygen consumption)
Immunostimulatory factor secretion for immune response modeling
Oncoprotein expression levels (variable between cells)
Proliferation parameters and oxygen sensitivity
Apoptosis and necrosis pathways
This method creates heterogeneity in the cell population through stochastic parameter assignment, a key aspect of realistic tumor modeling.
Definition at line 1312 of file Celula.cpp.
References Parametros_globales::activar_respuesta_inmune, Ciclo::actualizar_mis_tasas_de_transicion(), actualizar_voxel_del_microambiente(), Muerte::agregar_ciclo_de_muerte(), apoptosis, apoptosis_parametros, Parametros_globales::c_nombre, Fenotipo::ciclo, Volumen::citoplasma_tasa_de_cambio, Parametros_globales::densidades_de_saturacion, Secrecion::densidades_de_saturacion, Microambiente::encontrar_indice_de_densidad(), fenotipo, Volumen::fluido_tasa_de_cambio, Parametros_globales::imm_mean, Parametros_globales::imm_sd, microambiente, Fenotipo::muerte, necrosis, necrosis_parametros, nombre, RNG::NormalRandom_CM(), Volumen::nucleo_tasa_de_cambio, Parametros::o2_referencia, Parametros_globales::o2_referencia, Parametros::o2_saturacion_para_la_proliferacion, Parametros_globales::o2_saturacion_para_la_proliferacion, Secrecion::oncoproteina, parametros, pg, rng, Fenotipo::secrecion, Ciclo::sync_con_ciclo_modelo(), Ciclo::tasa_aleatoria, Parametros_globales::tasas_de_consumo, Secrecion::tasas_de_consumo, Parametros_globales::tasas_de_secrecion, Secrecion::tasas_de_secrecion, vida, and Fenotipo::volumen.
Referenced by Tejido::inicializar_tejido().
inicializar_celula_sana()
void Celula::inicializar_celula_sana ()
Initializes a cell with healthy properties.
Initializes a healthy cell with non-proliferative parameters.
Sets up a cell with healthy cell parameters, including turning off proliferation and setting appropriate oxygen consumption rates. The cell is set to type 1 (healthy) and given the name "Sana".
In cancer research, this method enables:
Modeling the normal tissue surrounding tumors
Establishing baseline healthy cell behavior for comparison
Creating heterogeneous tissue environments with both normal and cancer cells
Studying cancer cell interactions with healthy tissue
This is crucial for realistic tumor microenvironment simulation.
Definition at line 1401 of file Celula.cpp.
References actualizar_voxel_del_microambiente(), Muerte::agregar_ciclo_de_muerte(), c, Fenotipo::ciclo, Microambiente::encontrar_indice_de_densidad(), Ciclo_Modelo::encontrar_indice_de_la_fase(), fenotipo, microambiente, Fenotipo::muerte, necrosis, necrosis_parametros, nombre, Ciclo::pCiclo_Modelo, Fenotipo::secrecion, Ciclo::sync_con_ciclo_modelo(), Ciclo_Modelo::tasa_de_transicion(), Secrecion::tasas_de_consumo, Secrecion::tasas_de_secrecion, Ciclo::tasas_de_transicion, Ciclo_Modelo::tasas_de_transicion, tipo, vida, and Constantes::viva.
morir()
void Celula::morir (int indice)
Initiates cell death process.
Removes a cell from the simulation.
Parameters
indice Index of the death type
Deletes a cell and updates the global cell collection. This is used when cells are removed from the simulation due to completion of death processes. In cancer research, this models cell clearance after cell death, which affects tumor dynamics and treatment responses.
Parameters
indice Index of the cell to remove in the todas_las_celulas array
Definition at line 671 of file Celula.cpp.
References indice, and todas_las_celulas.
mostrar_informacion_de_la_celula()
void Celula::mostrar_informacion_de_la_celula (std::ostream & os)
Outputs detailed cell information.
Displays detailed information about the cell.
Parameters
os Output stream
Prints the cell's type, name, physical properties (radius, volume), position, voxel indices, cycle model details, and secretion/consumption rates.
In cancer research, this method is valuable for:
Debugging simulation behavior
Tracking individual cell characteristics
Analyzing heterogeneity in the tumor cell population
Validating cell parameter initialization
Parameters
os Output stream to write the information to
Definition at line 1363 of file Celula.cpp.
References Fenotipo::ciclo, Ciclo_Modelo::codigo, Secrecion::densidades_de_saturacion, fenotipo, Fenotipo::geometria, Ciclo_Modelo::mostrar_ciclo(), nombre, Ciclo_Modelo::nombre, Ciclo::pCiclo_Modelo, posicion, Geometria::radio, Fenotipo::secrecion, Secrecion::tasas_de_consumo, Secrecion::tasas_de_secrecion, tipo, Volumen::total, Fenotipo::volumen, voxel, and voxel_del_microambiente.
registrar_microambiente()
void Celula::registrar_microambiente (Microambiente *)
Registers the microenvironment with the cell.
Registers the cell with the microenvironment.
Parameters
m Pointer to the microenvironment
Sets up the cell's secretion and consumption vectors to match the microenvironment's substrates. This is essential for the cell to interact with the biochemical environment.
In cancer research, this enables modeling:
Cell metabolism (nutrients uptake)
Signaling factor secretion
Hypoxic responses
Cell-cell communication via diffusible factors
Parameters
microambiente Pointer to the microenvironment (unused parameter - uses class member)
Definition at line 1118 of file Celula.cpp.
References Secrecion::densidades_de_saturacion, fenotipo, microambiente, Fenotipo::secrecion, Secrecion::tasas_de_consumo, Secrecion::tasas_de_exportacion_neta, Secrecion::tasas_de_secrecion, temp_celula_fuente_sumidero_exportacion_solver1, temp_celula_fuente_sumidero_solver1, temp_celula_fuente_sumidero_solver2, and Microambiente::vector_de_densidades().
Referenced by Celula().
set_constantes_de_consumo_interno()
void Celula::set_constantes_de_consumo_interno (double dt)
Sets constants for internal consumption.
Sets internal constants for secretion/consumption calculations.
Parameters
dt Time step
Prepares the cell-specific constants used for calculating the cell's impact on the microenvironment. This includes factors accounting for:
Cell volume relative to voxel volume
Secretion and consumption rates
Saturation levels
In cancer research, this models how individual cells modify their local biochemical environment, a critical aspect of tumor metabolism and microenvironment evolution.
Parameters
dt Time step size for the update
Definition at line 1174 of file Celula.cpp.
References axpy(), Volumen::cambio_el_volumen, Secrecion::densidades_de_saturacion, fenotipo, microambiente, Fenotipo::secrecion, Secrecion::tasas_de_consumo, Secrecion::tasas_de_exportacion_neta, Secrecion::tasas_de_secrecion, temp_celula_fuente_sumidero_exportacion_solver1, temp_celula_fuente_sumidero_exportacion_solver2, temp_celula_fuente_sumidero_solver1, temp_celula_fuente_sumidero_solver2, Volumen::total, Fenotipo::volumen, Voxel::volumen, voxel_del_microambiente, and Microambiente::voxeles().
Referenced by simular_secrecion_y_consumo().
set_posicion() [1/2]
bool Celula::set_posicion (double x, double y, double z)
Sets the cell's position using coordinates.
Sets the cell position in 3D space with boundary handling.
Parameters
x X coordinate
y Y coordinate
z Z coordinate
Returns
Success status
Positions the cell at specified coordinates, handling periodic boundary conditions if enabled. This is critical for spatial modeling of tumors and their microenvironment in cancer research.
Parameters
x X-coordinate
y Y-coordinate
z Z-coordinate
Returns
True if position was successfully set
Definition at line 568 of file Celula.cpp.
References Parametros_globales::condiciones_de_periodicidad, Parametros_globales::condiciones_de_periodicidad_x, Parametros_globales::condiciones_de_periodicidad_y, Parametros_globales::condiciones_de_periodicidad_z, pg, posicion, Parametros_globales::rango_en_X, Parametros_globales::rango_en_Y, Parametros_globales::rango_en_Z, Vector::x, Vector::y, and Vector::z.
Referenced by actualizar_posicion(), dividir(), Tejido::inicializar_tejido(), Tejido::introducir_linfocitos(), Tejido::introducir_linfocitos_aleatorios(), and set_posicion().
set_posicion() [2/2]
bool Celula::set_posicion (Vector posicion)
Sets the cell's position using a Vector.
Parameters
posicion Position vector
Returns
Success status
Definition at line 594 of file Celula.cpp.
References posicion, set_posicion(), Vector::x, Vector::y, and Vector::z.
simular_secrecion_y_consumo()
void Celula::simular_secrecion_y_consumo (double dt)
Simulates secretion and consumption of microenvironment substrates.
Simulates the cell's secretion and consumption processes.
Parameters
dt Time step
Updates the microenvironment based on the cell's secretion and consumption rates. This method physically changes the substrate concentrations in the cell's voxel.
In cancer research, this models:
Oxygen consumption by tumor cells
Growth factor and cytokine secretion
pH changes due to metabolic byproducts
Nutrient depletion in densely packed tumors
Parameters
dt Time step size for the update
Definition at line 1272 of file Celula.cpp.
References Volumen::cambio_el_volumen, es_activa, fenotipo, set_constantes_de_consumo_interno(), temp_celula_fuente_sumidero_exportacion_solver2, temp_celula_fuente_sumidero_solver1, temp_celula_fuente_sumidero_solver2, Fenotipo::volumen, and voxel_del_microambiente.
vector_de_densidades_mas_cercano()
std::vector< double > & Celula::vector_de_densidades_mas_cercano (void)
Gets the closest density vector from the microenvironment.
Gets the nearest density vector from the microenvironment.
Returns
Reference to density vector
Provides access to the substrate concentrations in the cell's voxel This is essential for cells to sense their biochemical environment.
In cancer research, this enables modeling:
Cell response to hypoxia
Nutrient-dependent proliferation
Adaptation to microenvironmental conditions
Returns
Reference to the vector of substrate densities
Definition at line 1234 of file Celula.cpp.
References microambiente, Microambiente::vector_de_densidades_mas_cercano(), and voxel_del_microambiente.
Referenced by actualizar_parametros_de_celula_y_muerte_con_o2(), actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), avanzar_funciones_del_fenotipo_con_O2(), and avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina().
Member Data Documentation
adherida
bool Celula::adherida
Definition at line 92 of file Celula.h.
Referenced by Linfocito::adherir_celula(), avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Linfocito::avanzar_linfocito(), Celula(), Linfocito::chequear_vecinos_para_adherirse(), comenzar_muerte(), dividir(), Linfocito::intentar_adherirse(), and Linfocito::soltar_celula().
celula_adherida
Celula* Celula::celula_adherida
Definition at line 98 of file Celula.h.
Referenced by Linfocito::adherir_celula(), avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Linfocito::avanzar_linfocito(), Celula(), comenzar_muerte(), Linfocito::desencadenar_apoptosis(), Linfocito::intento_de_apoptosis(), and Linfocito::soltar_celula().
desplazamiento
Vector Celula::desplazamiento
Definition at line 97 of file Celula.h.
Referenced by agregar_potenciales(), Contenedor_de_Celulas::agregar_potenciales_cdc(), agregar_potenciales_mb(), agregar_potenciales_mb_2(), Linfocito::avanzar_linfocito(), and Linfocito::intentar_adherirse().
es_activa
bool Celula::es_activa protected
Definition at line 76 of file Celula.h.
Referenced by actualizar_voxel_del_microambiente(), Celula(), and simular_secrecion_y_consumo().
fenotipo
Fenotipo Celula::fenotipo
Definition at line 93 of file Celula.h.
Referenced by actualizar_parametros_de_celula_y_muerte_con_o2(), actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), actualizar_volumen(), agregar_potenciales(), Contenedor_de_Celulas::agregar_potenciales_cdc(), agregar_potenciales_mb(), agregar_potenciales_mb_2(), avanzar_funciones_del_fenotipo(), avanzar_funciones_del_fenotipo_con_O2(), avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Linfocito::avanzar_linfocito(), comenzar_muerte(), Tejido::crear_esfera_de_celulas(), Tejido::crear_planos_de_celulas_sanas_en_Z(), Linfocito::desencadenar_apoptosis(), dividir(), inicializar_celula(), inicializar_celula_sana(), Tejido::inicializar_tejido(), Linfocito::intentar_adherirse(), Linfocito::intento_de_apoptosis(), Linfocito::Linfocito(), mostrar_informacion_de_la_celula(), registrar_microambiente(), set_constantes_de_consumo_interno(), and simular_secrecion_y_consumo().
hora_de_la_ultima_mecanica
double Celula::hora_de_la_ultima_mecanica
Definition at line 89 of file Celula.h.
Referenced by Celula(), dividir(), and Linfocito::Linfocito().
hora_del_ultimo_ciclo
double Celula::hora_del_ultimo_ciclo
Definition at line 88 of file Celula.h.
Referenced by Celula(), dividir(), and Linfocito::Linfocito().
hora_global
double Celula::hora_global
Definition at line 90 of file Celula.h.
id
int Celula::id
Definition at line 83 of file Celula.h.
Referenced by agregar_potenciales(), Contenedor_de_Celulas::agregar_potenciales_cdc(), crear_celula(), crear_linfocito(), dividir(), and Contenedor_de_Celulas::registrar_celula().
indice
int Celula::indice
Definition at line 84 of file Celula.h.
Referenced by Celula(), crear_celula(), crear_linfocito(), Tejido::introducir_linfocitos(), Tejido::introducir_linfocitos_aleatorios(), and morir().
madre
int Celula::madre
Definition at line 85 of file Celula.h.
Referenced by Celula(), and dividir().
microambiente
Microambiente* Celula::microambiente private
Definition at line 68 of file Celula.h.
Referenced by actualizar_parametros_de_celula_y_muerte_con_o2(), actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), actualizar_voxel_del_microambiente(), avanzar_funciones_del_fenotipo_con_O2(), avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Celula(), get_microambiente(), gradiente_mas_cercano(), inicializar_celula(), inicializar_celula_sana(), registrar_microambiente(), set_constantes_de_consumo_interno(), and vector_de_densidades_mas_cercano().
nombre
std::string Celula::nombre
Definition at line 81 of file Celula.h.
Referenced by Celula(), dividir(), inicializar_celula(), inicializar_celula_sana(), Linfocito::Linfocito(), and mostrar_informacion_de_la_celula().
parametros
Parametros Celula::parametros
Definition at line 94 of file Celula.h.
Referenced by actualizar_parametros_de_celula_y_muerte_con_o2(), actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), avanzar_funciones_del_fenotipo_con_O2(), avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), dividir(), and inicializar_celula().
posicion
Vector Celula::posicion
Definition at line 95 of file Celula.h.
Referenced by actualizar_posicion(), actualizar_voxel_del_microambiente(), agregar_potenciales(), Contenedor_de_Celulas::agregar_potenciales_cdc(), agregar_potenciales_mb(), agregar_potenciales_mb_2(), Linfocito::avanzar_linfocito(), Celula(), dividir(), Linfocito::intentar_adherirse(), mostrar_informacion_de_la_celula(), Contenedor_de_Celulas::registrar_celula(), and set_posicion().
tasa
double Celula::tasa
Definition at line 91 of file Celula.h.
temp_celula_fuente_sumidero_exportacion_solver1
std::vector<double> Celula::temp_celula_fuente_sumidero_exportacion_solver1 protected
Definition at line 73 of file Celula.h.
Referenced by registrar_microambiente(), and set_constantes_de_consumo_interno().
temp_celula_fuente_sumidero_exportacion_solver2
std::vector<double> Celula::temp_celula_fuente_sumidero_exportacion_solver2 protected
Definition at line 74 of file Celula.h.
Referenced by set_constantes_de_consumo_interno(), and simular_secrecion_y_consumo().
temp_celula_fuente_sumidero_solver1
std::vector<double> Celula::temp_celula_fuente_sumidero_solver1 protected
Definition at line 71 of file Celula.h.
Referenced by registrar_microambiente(), set_constantes_de_consumo_interno(), and simular_secrecion_y_consumo().
temp_celula_fuente_sumidero_solver2
std::vector<double> Celula::temp_celula_fuente_sumidero_solver2 protected
Definition at line 72 of file Celula.h.
Referenced by registrar_microambiente(), set_constantes_de_consumo_interno(), and simular_secrecion_y_consumo().
tiempo_desde_el_ultimo_ciclo
double Celula::tiempo_desde_el_ultimo_ciclo
Definition at line 86 of file Celula.h.
Referenced by avanzar_funciones_del_fenotipo(), avanzar_funciones_del_fenotipo_con_O2(), avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), and Celula().
tiempo_desde_la_ultima_mecanica
double Celula::tiempo_desde_la_ultima_mecanica
Definition at line 87 of file Celula.h.
Referenced by Celula().
tipo
int Celula::tipo
Definition at line 82 of file Celula.h.
Referenced by actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), agregar_potenciales(), Contenedor_de_Celulas::agregar_potenciales_cdc(), avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Linfocito::avanzar_linfocito(), Celula(), comenzar_muerte(), dividir(), inicializar_celula_sana(), Linfocito::Linfocito(), mostrar_informacion_de_la_celula(), and Linfocito::motilidad_de_linfocito().
velocidad
Vector Celula::velocidad
Definition at line 96 of file Celula.h.
Referenced by actualizar_posicion(), Linfocito::actualizar_vector_de_motilidad(), agregar_potenciales(), Contenedor_de_Celulas::agregar_potenciales_cdc(), agregar_potenciales_mb(), agregar_potenciales_mb_2(), and Linfocito::avanzar_linfocito().
velocidad_anterior
Vector Celula::velocidad_anterior protected
Definition at line 75 of file Celula.h.
Referenced by actualizar_posicion().
voxel
int Celula::voxel
Definition at line 80 of file Celula.h.
Referenced by Celula(), mostrar_informacion_de_la_celula(), Contenedor_de_Celulas::registrar_celula(), and Contenedor_de_Celulas::sacar_celula_de_voxel().
voxel_del_microambiente
int Celula::voxel_del_microambiente
Definition at line 79 of file Celula.h.
Referenced by actualizar_voxel_del_microambiente(), get_indice_del_voxel_del_microambiente(), gradiente_mas_cercano(), mostrar_informacion_de_la_celula(), set_constantes_de_consumo_interno(), simular_secrecion_y_consumo(), and vector_de_densidades_mas_cercano().
The documentation for this class was generated from the following files:
Celula.h
Celula.cpp