Cancer Cell Agent Simulation: Muerte Class Reference
Muerte Class Reference
#include <Muerte.h>
Public Member Functions
Muerte ()
Default constructor.
int agregar_ciclo_de_muerte (double tasa, Ciclo_Modelo *pModelo)
Adds a new death cycle to the cell.
int agregar_ciclo_de_muerte (double tasa, Ciclo_Modelo *pModelo, Muerte_parametros &muerte_parametros)
Adds a new death cycle with custom parameters.
int encontrar_indice_del_ciclo_de_muerte (int codigo)
Finds death cycle index by code.
int encontrar_indice_del_ciclo_de_muerte (std::string nombre)
Finds death cycle index by name.
bool chequear_muerte (double dt)
Determines if the cell should enter a death process.
void comenzar_muerte (int indice_ciclo_de_muerte)
Initiates a specific death process.
Ciclo_Modelo & ciclo_actual (void)
Gets the currently active death cycle model.
Muerte_parametros & parametros_actuales (void)
Gets the parameters for the current death cycle.
Public Attributes
std::vector< double > tasas
Transition rates for each death cycle.
std::vector< Ciclo_Modelo * > ciclos
Collection of cell death cycle models.
std::vector< Muerte_parametros > parametros
Parameters for each death cycle.
bool muerta
Flag indicating if the cell is dead.
int indice_del_ciclo_de_muerte_actual
Index of the currently active death cycle.
Detailed Description
Definition at line 41 of file Muerte.h.
Constructor & Destructor Documentation
Muerte()
Muerte::Muerte ()
Default constructor.
Constructor for the Muerte (Death) class.
Initializes a new Muerte object with default settings. Sets up the death tracking system for a new cell in the cancer simulation.
Initializes a new death management object with empty collections for death rates, cycle models, and parameters. Sets the cell as initially alive (not dead).
In cancer research, this initialization represents the starting state of a cancer cell that has not yet entered any death pathway, which is the default state for newly created cells in the simulation.
Definition at line 43 of file Muerte.cpp.
References ciclos, indice_del_ciclo_de_muerte_actual, muerta, parametros, and tasas.
Member Function Documentation
agregar_ciclo_de_muerte() [1/2]
int Muerte::agregar_ciclo_de_muerte (double tasa, Ciclo_Modelo * pModelo)
Adds a new death cycle to the cell.
Adds a new death cycle with default parameters.
Registers a new death cycle with a specified transition rate. Enables modeling of multiple death pathways relevant to cancer research, such as apoptosis or necrosis, each with their own transition dynamics.
Parameters
tasa The base rate at which cells enter this death cycle
pModelo Pointer to the cell cycle model defining the death process
Returns
The index of the newly added death cycle
Registers a new death cycle with the specified transition rate and cycle model, using default parameters. This method allows the simulation to incorporate different death mechanisms with their specific transition dynamics.
In cancer research, this enables modeling of various death pathways like apoptosis or necrosis, each with characteristic rates that may be altered in cancer cells. For example, reduced apoptosis rates can model the apoptotic resistance common in many cancer types.
Parameters
tasa The base rate at which cells enter this death cycle
pModelo Pointer to the cell cycle model defining the death process
Returns
The index of the newly added death cycle
Definition at line 71 of file Muerte.cpp.
References ciclos, parametros, and tasas.
Referenced by Celula::inicializar_celula(), Celula::inicializar_celula_sana(), and Linfocito::Linfocito().
agregar_ciclo_de_muerte() [2/2]
int Muerte::agregar_ciclo_de_muerte (double tasa, Ciclo_Modelo * pModelo, Muerte_parametros & muerte_parametros)
Adds a new death cycle with custom parameters.
Registers a new death cycle with both a transition rate and custom parameters. Allows for detailed customization of death processes to model cancer-specific cell death mechanisms and their unique behaviors.
Parameters
tasa The base rate at which cells enter this death cycle
pModelo Pointer to the cell cycle model defining the death process
muerte_parametros Custom parameters for this specific death mechanism
Returns
The index of the newly added death cycle
Registers a new death cycle with the specified transition rate, cycle model, and custom parameters. This method provides more detailed control over death mechanisms by allowing customization of parameters specific to each death pathway.
In cancer research, this customization is crucial for modeling the heterogeneity of cancer cell responses to death signals. Different cancer types and even subpopulations within the same tumor can exhibit varied death parameters, which this method allows researchers to simulate.
Parameters
tasa The base rate at which cells enter this death cycle
pModelo Pointer to the cell cycle model defining the death process
muerte_parametros Custom parameters for this specific death mechanism
Returns
The index of the newly added death cycle
Definition at line 98 of file Muerte.cpp.
References ciclos, parametros, and tasas.
chequear_muerte()
bool Muerte::chequear_muerte (double dt)
Determines if the cell should enter a death process.
Stochastically evaluates whether the cell should begin dying based on current death rates and elapsed time. This method models the probabilistic nature of cell death decisions in cancer, which are influenced by various factors.
In cancer research, this represents how cells respond to death signals, with altered probabilities reflecting cancer cells' characteristic resistance to death triggers.
Parameters
dt The time step for the current simulation iteration
Returns
True if the cell should begin a death process, false otherwise
Stochastically evaluates whether the cell should begin dying based on current death rates and elapsed time. The method checks each registered death pathway in sequence, using random number generation to model the probabilistic nature of cell death decisions.
In cancer research, this stochastic approach is essential for realistic modeling:
It captures the probabilistic nature of cell death in biological systems
It allows for modeling reduced death probabilities in cancer cells
It enables simulation of heterogeneous responses within cell populations
It can reflect how microenvironmental factors influence death likelihood
It supports modeling of treatment efficacy through modified death rates
The method returns immediately if the cell is already dead, preventing multiple death pathways from being activated simultaneously.
Parameters
dt The time step for the current simulation iteration
Returns
True if the cell should begin a death process, false otherwise
Definition at line 180 of file Muerte.cpp.
References indice_del_ciclo_de_muerte_actual, muerta, RNG::RandomNumber(), rng, and tasas.
Referenced by Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), and Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina().
ciclo_actual()
Ciclo_Modelo & Muerte::ciclo_actual (void)
Gets the currently active death cycle model.
Retrieves the cycle model for the current death process. Used to determine how the cell progresses through its death in cancer simulations, modeling various temporal patterns of cell death observed in different cancer types.
Returns
Reference to the current death cycle model
Retrieves the cycle model for the current death process. This method provides access to the specific death pathway the cell is currently undergoing, allowing the simulation to determine how the cell progresses through its death.
In cancer research, this is important for modeling:
Different temporal patterns of cell death (rapid vs. slow)
Morphological changes during death processes
Phase-specific behaviors during cell death
Interactions with neighboring cells during death
Biochemical changes associated with specific death pathways
Returns
Reference to the current death cycle model
Definition at line 246 of file Muerte.cpp.
References ciclos, and indice_del_ciclo_de_muerte_actual.
Referenced by Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), and Celula::comenzar_muerte().
comenzar_muerte()
void Muerte::comenzar_muerte (int indice_ciclo_de_muerte)
Initiates a specific death process.
Starts a particular death cycle for the cell and marks it as dying. This method is critical for modeling how cancer cells enter different death pathways in response to environmental stressors, therapeutic agents, or internal signals.
Parameters
indice_ciclo_de_muerte The index of the death cycle to initiate
Explicitly starts a particular death cycle for the cell and marks it as dying. Unlike chequear_muerte which stochastically determines death, this method directly triggers a specific death pathway.
In cancer research, this method is critical for modeling:
Targeted cell killing by immune cells or therapeutic agents
Forced apoptosis in response to specific signals
Necrotic death due to severe environmental stress
Experimental interventions that directly induce cell death
Programmed cell death during development or tissue homeostasis
This deterministic approach complements the stochastic death checks, allowing for both random and directed cell death in the simulation.
Parameters
indice_ciclo_de_muerte The index of the death cycle to initiate
Definition at line 222 of file Muerte.cpp.
References indice_del_ciclo_de_muerte_actual, and muerta.
Referenced by Celula::comenzar_muerte().
encontrar_indice_del_ciclo_de_muerte() [1/2]
int Muerte::encontrar_indice_del_ciclo_de_muerte (int codigo)
Finds death cycle index by code.
Finds death cycle index by code identifier.
Retrieves the index of a death cycle based on its code identifier. Used in cancer models to reference specific death mechanisms during simulation.
Parameters
codigo The code identifier for the death cycle
Returns
The index of the death cycle, or -1 if not found
Searches through the registered death cycles to find one with a matching code identifier. This method enables referencing specific death mechanisms by their unique codes during simulation.
In cancer research, this functionality allows the simulation to target specific death pathways (e.g., apoptosis vs. necrosis) when modeling responses to treatments or environmental stressors that may trigger particular death mechanisms.
Parameters
codigo The code identifier for the death cycle to find
Returns
The index of the matching death cycle, or 0 if not found
Definition at line 122 of file Muerte.cpp.
References ciclos.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), and Linfocito::desencadenar_apoptosis().
encontrar_indice_del_ciclo_de_muerte() [2/2]
int Muerte::encontrar_indice_del_ciclo_de_muerte (std::string nombre)
Finds death cycle index by name.
Retrieves the index of a death cycle based on its name. Allows cancer researchers to reference death mechanisms by descriptive names like "apoptosis" or "necrosis" in the simulation.
Parameters
nombre The name of the death cycle to find
Returns
The index of the death cycle, or -1 if not found
Searches through the registered death cycles to find one with a matching name. This method provides a more human-readable way to reference specific death mechanisms during simulation.
In cancer research, this allows for intuitive referencing of death pathways by descriptive names like "apoptosis" or "necrosis" when analyzing simulation results or configuring cell responses to different stimuli, enhancing the interpretability of the model.
Parameters
nombre The name of the death cycle to find
Returns
The index of the matching death cycle, or 0 if not found
Definition at line 148 of file Muerte.cpp.
References ciclos.
parametros_actuales()
Muerte_parametros & Muerte::parametros_actuales (void)
Gets the parameters for the current death cycle.
Retrieves the parameter set controlling the current death process. Allows access to specific configuration of the active death mechanism, which may vary across different cancer types or microenvironmental conditions.
Returns
Reference to the current death parameters
Retrieves the parameter set controlling the current death process. This method provides access to the specific configuration parameters for the active death mechanism, allowing the simulation to apply the appropriate behaviors during cell death.
In cancer research, these parameters are crucial for modeling:
Cell-type specific death characteristics
Microenvironmental influences on death processes
Treatment-modified death behaviors
Tumor-specific alterations to death pathways
Experimental interventions that modify death parameters
Returns
Reference to the current death parameters
Definition at line 268 of file Muerte.cpp.
References indice_del_ciclo_de_muerte_actual, and parametros.
Referenced by Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), and Celula::comenzar_muerte().
Member Data Documentation
ciclos
std::vector<Ciclo_Modelo*> Muerte::ciclos
Collection of cell death cycle models.
Stores pointers to the cycle models (finite state machines) that define how cells progress through different death mechanisms like apoptosis and necrosis, which are critical for modeling cancer cell populations.
Definition at line 58 of file Muerte.h.
Referenced by agregar_ciclo_de_muerte(), ciclo_actual(), encontrar_indice_del_ciclo_de_muerte(), and Muerte().
indice_del_ciclo_de_muerte_actual
int Muerte::indice_del_ciclo_de_muerte_actual
Index of the currently active death cycle.
Tracks which death mechanism the cell is currently undergoing. Allows the simulation to apply the appropriate death behavior for modeling various causes of cancer cell death.
Definition at line 82 of file Muerte.h.
Referenced by chequear_muerte(), ciclo_actual(), comenzar_muerte(), Muerte(), and parametros_actuales().
muerta
bool Muerte::muerta
Flag indicating if the cell is dead.
When true, indicates the cell has entered an irreversible death process. In cancer research, tracking dead cells is important for modeling tumor necrotic cores and response to treatments.
Definition at line 74 of file Muerte.h.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), Celula::avanzar_funciones_del_fenotipo(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Linfocito::avanzar_linfocito(), chequear_muerte(), comenzar_muerte(), Celula::comenzar_muerte(), Linfocito::desencadenar_apoptosis(), Linfocito::intentar_adherirse(), and Muerte().
parametros
std::vector<Muerte_parametros> Muerte::parametros
Parameters for each death cycle.
Contains the specific parameters that control each death mechanism's behavior, allowing for customization of death processes to model different cancer types and their characteristic patterns of cell death.
Definition at line 66 of file Muerte.h.
Referenced by agregar_ciclo_de_muerte(), Muerte(), and parametros_actuales().
tasas
std::vector<double> Muerte::tasas
Transition rates for each death cycle.
Vector of rates at which cells may enter each death cycle. These rates can be adjusted dynamically based on environmental conditions, allowing for modeling of environmentally-induced cell death in cancer.
Definition at line 50 of file Muerte.h.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), agregar_ciclo_de_muerte(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), chequear_muerte(), and Muerte().
The documentation for this class was generated from the following files:
Muerte.h
Muerte.cpp