Cancer Cell Agent Simulation: Microambiente Class Reference
Microambiente Class Reference
Models the biochemical environment where cells exist.
#include <Microambiente.h>
Public Member Functions
void actualizar_tasas (void)
Updates all rates in the microenvironment.
Microambiente ()
Default constructor.
unsigned int numero_de_densidades (void)
Gets the number of tracked densities/substrates.
unsigned int numero_de_voxeles (void)
Gets the total number of voxels in the domain.
void redimensionar_espacio (double x_ini, double x_fin, double y_ini, double y_fin, double z_ini, double z_fin, double dx_nuevo, double dy_nuevo, double dz_nuevo)
Resizes the spatial domain of the microenvironment.
void redimensionar_densidades (int nuevo_tamano)
Resizes the number of tracked densities/substrates.
void agregar_densidad (void)
Adds a new density/substrate with default properties.
void agregar_densidad (std::string nombre, std::string unidades, double coeficiente_de_difusion, double tasa_de_decaimiento)
Adds a new density/substrate with specified properties.
void set_densidad (int indice, std::string nombre, std::string unidades, double coeficiente_de_difusion, double tasa_de_decaimiento)
Sets properties for an existing density/substrate.
void set_densidad (int indice, std::string nombre, std::string unidades)
Sets name and units for an existing density/substrate.
int encontrar_indice_de_densidad (std::string nombre)
Finds the index of a density by its name.
int indice_de_voxel (int i, int j, int k)
Converts 3D Cartesian indices to a voxel index.
std::vector< unsigned int > indices_cartesianos (int n)
Converts a linear voxel index to 3D cartesian indices.
int indice_del_voxel_mas_cercano (Vector &posicion)
Finds the voxel index closest to a given position.
Vector centro_del_voxel (int indice_del_voxel)
Gets the center position of a voxel.
Vector indices_cartesianos_mas_cercanos (Vector &posicion)
Gets Cartesian indices closest to a position.
Voxel & voxel_mas_cercano (Vector &posicion)
Gets the voxel object closest to a given position.
Voxel & voxeles (int indice_de_voxel)
Gets a voxel by its linear index.
std::vector< double > & vector_de_densidades_mas_cercano (Vector &posicion)
Returns the density vector of the voxel closest to the given position.
std::vector< double > & vector_de_densidades_mas_cercano (int indice_de_voxel)
Returns the density vector at the specified voxel index.
std::vector< double > & operator() (int i, int j, int k)
std::vector< double > & operator() (int n)
Operator overload for direct access to density vectors by voxel index.
std::vector< double > & vector_de_densidades (int i, int j, int k)
std::vector< double > & vector_de_densidades (int n)
Returns the density vector at the specified voxel index.
std::vector< gradiente > & vector_de_gradientes (int i, int j, int k)
Returns the gradient vector at the specified 3D voxel coordinates.
std::vector< gradiente > & vector_de_gradientes (int n)
Returns the gradient vector at the specified voxel index.
std::vector< gradiente > & vector_de_gradiente_mas_cercano (Vector &posicion)
Returns the gradient vector of the voxel closest to the given position.
void calcular_todos_los_vectores_de_gradientes (void)
Calculates gradient vectors for all substrates at all voxels in the domain.
void calcular_vector_de_gradiente (int n)
Calculates gradient for a specific density.
void resetear_todos_los_vectores_de_gradientes (void)
Resets all gradient calculations.
void simular_difusion_decaimiento (double dt)
Simulates diffusion and decay of substrates.
void simular_suministro_y_consumo_del_bulk (double dt)
Simulates bulk supply and consumption.
void simular_suministro_y_consumo_de_las_celulas (double dt)
Simulates cell-based supply and consumption.
void mostrar_informacion (std::ostream &os)
Outputs information about the microenvironment.
void agregar_nodo_de_dirichlet (int indice_de_voxel, std::vector< double > &valor)
Adds a Dirichlet node at a voxel.
void actualizar_nodo_de_dirichlet (int indice_de_voxel, std::vector< double > &nuevo_valor)
Updates a Dirichlet node with new values.
void actualizar_nodo_de_dirichlet (int indice_de_voxel, int indice_de_sustrato, double nuevo_valor)
Updates a specific substrate at a Dirichlet node.
void remover_nodo_de_dirichlet (int indice_de_voxel)
Removes a Dirichlet node.
void aplicar_condiciones_de_dirichlet (void)
Applies Dirichlet conditions to the domain.
void set_activacion_de_sustrato_de_dirichlet (int indice_de_sustrato, bool nuevo_valor)
Sets activation status for a substrate's Dirichlet condition.
void set_activacion_de_sustrato_de_dirichlet (int indice_de_sustrato, int indice, bool nuevo_valor)
Sets activation status for a substrate at a specific voxel.
void set_activacion_de_sustrato_de_dirichlet (int indice, std::vector< bool > &nuevo_valor)
Sets activation status for all substrates at a voxel.
bool get_activacion_de_sustrato_de_dirichlet (int indice_de_sustrato, int indice)
Gets activation status for a substrate at a voxel.
bool & es_nodo_de_dirichlet (int indice_de_voxel)
Checks if a voxel is a Dirichlet node.
void solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D (double dt)
Solver for diffusion-decay using LOD (Locally One-Dimensional) method.
void inicializar_microambiente ()
Initializes the microenvironment with default settings.
void crear_vaso_sanguineo (int xmin, int ymin, int zmin, int xmax, int ymax, int zmax)
Creates a blood vessel in the specified region.
Public Attributes
Grillado_Cartesiano mgrilla
std::string unidades_espaciales
std::string unidades_temporales
std::string nombre
std::vector< std::string > densidades_nombres
std::vector< std::string > densidades_unidades
std::vector< double > coeficientes_de_difusion
std::vector< double > tasas_de_decaimiento
std::vector< std::vector< double > > densidades_objetivo_de_suministro_por_tasas_de_suministro
std::vector< std::vector< double > > tasas_de_suministro
std::vector< std::vector< double > > tasas_de_consumo
std::vector< int > voxeles_del_vaso_sanguineo
Private Attributes
std::vector< std::vector< double > > temp_vectores_densidad1
std::vector< std::vector< double > > temp_vectores_densidad2
std::vector< std::vector< double > > temp_bulk_fuente_sumidero_solver1
std::vector< std::vector< double > > temp_bulk_fuente_sumidero_solver2
std::vector< std::vector< double > > temp_bulk_fuente_sumidero_solver3
bool setup_del_solver_bulk_fuente_sumidero_hecho
std::vector< std::vector< double > > * p_vectores_densidad
std::vector< std::vector< gradiente > > vectores_gradiente
std::vector< bool > vector_gradiente_calculado
std::vector< double > uno
std::vector< double > cero
std::vector< double > un_medio
std::vector< double > un_tercio
std::vector< std::vector< double > > thomas_temp1
std::vector< std::vector< double > > thomas_temp2
std::vector< double > thomas_constante1x
std::vector< double > thomas_constante1y
std::vector< double > thomas_constante1z
std::vector< double > thomas_neg_constante1x
std::vector< double > thomas_neg_constante1y
std::vector< double > thomas_neg_constante1z
bool setup_de_thomas_hecho
int thomas_salto_en_i
int thomas_salto_en_j
int thomas_salto_en_k
std::vector< double > thomas_constante1
std::vector< double > thomas_constante1a
std::vector< double > thomas_constante2
std::vector< double > thomas_constante3
std::vector< double > thomas_constante3a
std::vector< std::vector< double > > thomas_denomx
std::vector< std::vector< double > > thomas_cx
std::vector< std::vector< double > > thomas_denomy
std::vector< std::vector< double > > thomas_cy
std::vector< std::vector< double > > thomas_denomz
std::vector< std::vector< double > > thomas_cz
bool setup_del_solver_de_difusion_hecho
std::vector< std::vector< double > > vector_valores_de_dirichlet
std::vector< bool > vector_activacion_dirichlet
std::vector< std::vector< bool > > dirichlet_vectorES_activacion
Detailed Description
Models the biochemical environment where cells exist.
Implements a multi-substrate diffusive microenvironment using a finite volume method. Tracks concentrations of various biochemical factors (like oxygen, nutrients, and signaling molecules) and models their diffusion, decay, and interaction with cells. The microenvironment is discretized into voxels on a Cartesian grid.
Cancer Research Context: The microenvironment is critical in cancer research, as it models tumor microenvironmental conditions like hypoxia (low oxygen), nutrient gradients, and signaling molecule distributions that significantly affect cancer cell behavior, proliferation patterns, and treatment response.
Definition at line 52 of file Microambiente.h.
Constructor & Destructor Documentation
Microambiente()
Microambiente::Microambiente ()
Default constructor.
Constructor for the Microambiente class.
Initializes a new microenvironment with default properties, including substrate vectors, diffusion coefficients, decay rates, and boundary conditions. Creates a minimal 1x1x1 grid initially, which will typically be resized before simulation.
Cancer Research Context: Creates the foundation for modeling biochemical conditions within and around a tumor, which significantly influence cancer progression.
Definition at line 88 of file Microambiente.cpp.
References cero, coeficientes_de_difusion, densidades_nombres, densidades_unidades, dirichlet_vectorES_activacion, Parametros_globales::dirichlet_xmax_valores, Parametros_globales::dirichlet_xmin_valores, Parametros_globales::dirichlet_ymax_valores, Parametros_globales::dirichlet_ymin_valores, Parametros_globales::dirichlet_zmax_valores, Parametros_globales::dirichlet_zmin_valores, mgrilla, microambiente_default, nombre, numero_de_densidades(), p_vectores_densidad, pg, Grillado_Cartesiano::redimensionar(), setup_de_thomas_hecho, setup_del_solver_bulk_fuente_sumidero_hecho, setup_del_solver_de_difusion_hecho, tasas_de_decaimiento, temp_vectores_densidad1, temp_vectores_densidad2, un_medio, un_tercio, unidades_espaciales, unidades_temporales, uno, vector_activacion_dirichlet, vector_gradiente_calculado, vector_valores_de_dirichlet, vectores_gradiente, and Grillado_General::voxeles.
Member Function Documentation
actualizar_nodo_de_dirichlet() [1/2]
void Microambiente::actualizar_nodo_de_dirichlet (int indice_de_voxel, int indice_de_sustrato, double nuevo_valor)
Updates a specific substrate at a Dirichlet node.
Updates a single substrate value at an existing Dirichlet boundary condition node.
Parameters
indice_de_voxel Voxel index
indice_de_sustrato Substrate index
nuevo_valor New density value
indice_de_voxel Index of the Dirichlet node to update
indice_de_sustrato Index of the substrate to update
nuevo_valor New value for the specified substrate
Cancer Research Context: This method enables selective modification of individual substrate concentrations at boundary points, which is important for modeling:
Selective changes in specific signaling molecules
Targeted drug delivery affecting only certain substrates
Differential regulation of nutrients or metabolites This granular control is essential for studying how specific microenvironmental factors influence cancer cell behavior and treatment response.
Definition at line 1127 of file Microambiente.cpp.
References dirichlet_vectorES_activacion, indice_de_voxel(), mgrilla, vector_valores_de_dirichlet, and Grillado_General::voxeles.
actualizar_nodo_de_dirichlet() [2/2]
void Microambiente::actualizar_nodo_de_dirichlet (int indice_de_voxel, std::vector< double > & nuevo_valor)
Updates a Dirichlet node with new values.
Updates the values at an existing Dirichlet boundary condition node.
Parameters
indice_de_voxel Voxel index
nuevo_valor Vector of new density values
indice_de_voxel Index of the Dirichlet node to update
nuevo_valor New vector of substrate values for this node
Cancer Research Context: This method allows for dynamic changes to boundary conditions, which is crucial for modeling:
Temporal changes in blood vessel perfusion affecting oxygen delivery
Dynamic drug delivery profiles during treatment
Changes in metabolite availability at tissue boundaries These dynamic changes can significantly impact tumor growth patterns, hypoxic regions, and treatment efficacy in cancer simulations.
Definition at line 1103 of file Microambiente.cpp.
References indice_de_voxel(), mgrilla, vector_valores_de_dirichlet, and Grillado_General::voxeles.
actualizar_tasas()
void Microambiente::actualizar_tasas (void)
Updates all rates in the microenvironment.
agregar_densidad() [1/2]
void Microambiente::agregar_densidad (std::string nombre, std::string unidades, double coeficiente_de_difusion, double tasa_de_decaimiento)
Adds a new density/substrate with specified properties.
Adds a new substrate to the microenvironment with specified properties.
Parameters
nombre Name of the density
unidades Units of the density
coeficiente_de_difusion Diffusion coefficient
tasa_de_decaimiento Decay rate
nombre Name of the substrate
unidades Units of measurement for the substrate
coeficiente_de_difusion Diffusion coefficient of the substrate
tasa_de_decaimiento Decay rate of the substrate
Cancer Research Context: Different biochemical factors have unique diffusion and decay properties that affect their distribution within tumors. For example, oxygen has a high diffusion coefficient but is rapidly consumed, creating steep gradients in tumors. Growth factors may diffuse more slowly but persist longer. These properties directly influence tumor growth patterns, invasion, and responses to therapy.
Definition at line 319 of file Microambiente.cpp.
References cero, coeficientes_de_difusion, densidades_nombres, densidades_unidades, Parametros_globales::dirichlet_todo, dirichlet_vectorES_activacion, Parametros_globales::dirichlet_vs, Parametros_globales::dirichlet_xmax, Parametros_globales::dirichlet_xmax_valores, Parametros_globales::dirichlet_xmin, Parametros_globales::dirichlet_xmin_valores, Parametros_globales::dirichlet_ymax, Parametros_globales::dirichlet_ymax_valores, Parametros_globales::dirichlet_ymin, Parametros_globales::dirichlet_ymin_valores, Parametros_globales::dirichlet_zmax, Parametros_globales::dirichlet_zmax_valores, Parametros_globales::dirichlet_zmin, Parametros_globales::dirichlet_zmin_valores, mgrilla, nombre, numero_de_densidades(), pg, tasas_de_decaimiento, temp_vectores_densidad1, temp_vectores_densidad2, un_medio, un_tercio, uno, vector_activacion_dirichlet, Parametros_globales::vector_activacion_dirichlet, Parametros_globales::vector_condicion_de_dirichlet, Parametros_globales::vector_condiciones_iniciales, vector_gradiente_calculado, vector_valores_de_dirichlet, vectores_gradiente, and Grillado_General::voxeles.
agregar_densidad() [2/2]
void Microambiente::agregar_densidad (void)
Adds a new density/substrate with default properties.
Referenced by inicializar_microambiente().
agregar_nodo_de_dirichlet()
void Microambiente::agregar_nodo_de_dirichlet (int indice_de_voxel, std::vector< double > & valor)
Adds a Dirichlet node at a voxel.
Adds a Dirichlet boundary condition node at the specified voxel.
Parameters
indice_de_voxel Voxel index
valor Vector of density values
indice_de_voxel Index of the voxel to set as a Dirichlet node
valor Vector of substrate values to maintain at this node
Cancer Research Context: Dirichlet boundary conditions are essential for modeling fixed concentration sources in the tumor microenvironment, such as:
Blood vessels that maintain constant oxygen/nutrient levels
Tissue boundaries with fixed metabolite concentrations
Drug delivery sources with constant concentration These boundary conditions create the concentration gradients that drive diffusion and influence cancer cell behavior, metabolism, and treatment response.
Definition at line 1079 of file Microambiente.cpp.
References indice_de_voxel(), mgrilla, vector_valores_de_dirichlet, and Grillado_General::voxeles.
Referenced by crear_vaso_sanguineo(), and inicializar_microambiente().
aplicar_condiciones_de_dirichlet()
void Microambiente::aplicar_condiciones_de_dirichlet (void)
Applies Dirichlet conditions to the domain.
Applies all Dirichlet boundary conditions to enforce fixed concentrations.
Cancer Research Context: This method enforces fixed concentration boundary conditions throughout the tumor microenvironment, which is essential for modeling:
Blood vessels that maintain constant oxygen/nutrient supply
Interfaces with surrounding normal tissue
Experimental conditions with controlled nutrient or drug delivery
By applying these boundary conditions, the method creates realistic concentration gradients within the tumor that drive critical biological processes including hypoxic adaptation, metabolic zonation, and directional cell migration. This enforces physiologically relevant constraints on the diffusion process.
Definition at line 1152 of file Microambiente.cpp.
References dirichlet_vectorES_activacion, mgrilla, vector_de_densidades(), vector_valores_de_dirichlet, and Grillado_General::voxeles.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
calcular_todos_los_vectores_de_gradientes()
void Microambiente::calcular_todos_los_vectores_de_gradientes (void)
Calculates gradient vectors for all substrates at all voxels in the domain.
Cancer Research Context: This method pre-computes all biochemical gradients throughout the entire tumor microenvironment, which is essential for comprehensive analysis of:
Global patterns of oxygen and nutrient gradients across the tumor
Spatial heterogeneity in microenvironmental factors
Potential migration paths for cancer cells responding to these gradients
Distribution of hypoxic regions and other microenvironmental niches
Pre-computing all gradients enables efficient simulation of gradient-driven behaviors across the entire tumor, though it is computationally intensive. The method uses OpenMP parallelization to improve performance.
Definition at line 765 of file Microambiente.cpp.
References Grillado_Cartesiano::coordenadas_x, Grillado_Cartesiano::coordenadas_y, Grillado_Cartesiano::coordenadas_z, Grillado_Cartesiano::dx, Grillado_Cartesiano::dy, Grillado_Cartesiano::dz, fg_indice_de_voxel, mgrilla, numero_de_densidades(), thomas_salto_en_i, thomas_salto_en_j, thomas_salto_en_k, vector_gradiente_calculado, and vectores_gradiente.
Referenced by main().
calcular_vector_de_gradiente()
void Microambiente::calcular_vector_de_gradiente (int n)
Calculates gradient for a specific density.
Calculates the gradient vectors for all substrates at the specified voxel.
Parameters
n Index of the density
n Index of the voxel to calculate gradients for
Cancer Research Context: This method computes the spatial gradients of biochemical substrates that drive cancer cell behavior. These gradients are essential for modeling:
Chemotaxis of cancer cells toward nutrient sources
Cellular adaptation to hypoxia gradients around necrotic regions
Directional migration of cancer cells during invasion and metastasis
Heterogeneous response to treatment based on microenvironmental gradients
The method uses central differences to calculate gradients, which provides accurate spatial derivatives for modeling how cancer cells sense and respond to their local environment.
Definition at line 939 of file Microambiente.cpp.
References Grillado_Cartesiano::coordenadas_x, Grillado_Cartesiano::coordenadas_y, Grillado_Cartesiano::coordenadas_z, Grillado_Cartesiano::dx, Grillado_Cartesiano::dy, Grillado_Cartesiano::dz, indices_cartesianos(), mgrilla, numero_de_densidades(), thomas_salto_en_i, thomas_salto_en_j, thomas_salto_en_k, vector_gradiente_calculado, and vectores_gradiente.
Referenced by vector_de_gradiente_mas_cercano(), and vector_de_gradientes().
centro_del_voxel()
Vector Microambiente::centro_del_voxel (int indice_del_voxel)
Gets the center position of a voxel.
Parameters
indice_del_voxel Voxel index
Returns
Center position as a Vector
Parameters
indice_del_voxel Linear index of the voxel
Returns
Vector 3D vector representing the center position
This method returns the spatial coordinates of a voxel's center given its linear index.
Cancer Research Context: Accurate voxel positioning is crucial for:
Calculating distances between cells and resources/signals
Determining cellular exposure to diffusing drugs
Mapping the physical landscape of the tumor microenvironment
Visualizing spatial heterogeneity within the tumor
Definition at line 481 of file Microambiente.cpp.
References Grillado_Cartesiano::get_centro_voxel(), and mgrilla.
crear_vaso_sanguineo()
void Microambiente::crear_vaso_sanguineo (int xmin, int ymin, int zmin, int xmax, int ymax, int zmax)
Creates a blood vessel in the specified region.
Creates a blood vessel within the specified 3D region.
Parameters
xmin Minimum x-coordinate
ymin Minimum y-coordinate
zmin Minimum z-coordinate
xmax Maximum x-coordinate
ymax Maximum y-coordinate
zmax Maximum z-coordinate
xmin Minimum x-coordinate of the vessel region
ymin Minimum y-coordinate of the vessel region
zmin Minimum z-coordinate of the vessel region
xmax Maximum x-coordinate of the vessel region
ymax Maximum y-coordinate of the vessel region
zmax Maximum z-coordinate of the vessel region
Cancer Research Context: Blood vessels are critical components of the tumor microenvironment that:
Supply oxygen and nutrients to cancer cells
Create oxygen and nutrient gradients that drive tumor heterogeneity
Serve as routes for metastatic dissemination
Provide delivery pathways for therapeutic agents
This method creates a blood vessel by setting Dirichlet boundary conditions within the specified region, maintaining fixed substrate concentrations that model the continuous supply from the vasculature. This is essential for realistic modeling of tumor growth, hypoxia development, and treatment response.
Definition at line 1838 of file Microambiente.cpp.
References agregar_nodo_de_dirichlet(), Parametros_globales::dirichlet_vs, indice_del_voxel_mas_cercano(), pg, set_activacion_de_sustrato_de_dirichlet(), Parametros_globales::vector_condicion_de_dirichlet, voxeles_del_vaso_sanguineo, Vector::x, Vector::y, and Vector::z.
encontrar_indice_de_densidad()
int Microambiente::encontrar_indice_de_densidad (std::string nombre)
Finds the index of a density by its name.
Parameters
nombre Name of the density
Returns
Index of the density, or -1 if not found
Definition at line 431 of file Microambiente.cpp.
References densidades_nombres, and nombre.
Referenced by Celula::actualizar_parametros_de_celula_y_muerte_con_o2(), Celula::actualizar_parametros_de_celula_y_muerte_con_o2_y_oncoproteina(), Celula::avanzar_funciones_del_fenotipo_con_O2(), Celula::avanzar_funciones_del_fenotipo_con_O2_y_oncoproteina(), Celula::inicializar_celula(), Celula::inicializar_celula_sana(), Linfocito::Linfocito(), and Linfocito::motilidad_de_linfocito().
es_nodo_de_dirichlet()
bool & Microambiente::es_nodo_de_dirichlet (int indice_de_voxel)
Checks if a voxel is a Dirichlet node.
Gets a reference to the Dirichlet node status of the specified voxel.
Parameters
indice_de_voxel Voxel index
Returns
Reference to Dirichlet status
Parameters
indice_de_voxel Index of the voxel to check
Returns
bool& Reference to the Dirichlet status (true = is a Dirichlet node, false = not a Dirichlet node)
Cancer Research Context: This method provides access to check or modify the Dirichlet boundary status of specific locations in the tumor microenvironment. This is important for:
Identifying fixed concentration sources like blood vessels in the tumor
Determining which regions maintain constant biochemical conditions
Analyzing how boundary conditions affect local cancer cell behavior
Tracking the spatial distribution of nutrient/oxygen sources in the simulation
Definition at line 1278 of file Microambiente.cpp.
References indice_de_voxel(), mgrilla, and Grillado_General::voxeles.
get_activacion_de_sustrato_de_dirichlet()
bool Microambiente::get_activacion_de_sustrato_de_dirichlet (int indice_de_sustrato, int indice)
Gets activation status for a substrate at a voxel.
Gets the activation state of a substrate at a specific Dirichlet node.
Parameters
indice_de_sustrato Substrate index
indice Voxel index
Returns
Activation status
Parameters
indice_de_sustrato Index of the substrate to check
indice Index of the Dirichlet node
Returns
bool Current activation state (true = active, false = inactive)
Cancer Research Context: This method enables querying the current state of boundary conditions, which is important for:
Adaptive modeling based on current microenvironmental state
Analysis of boundary effects on tumor growth and behavior
Verification of simulation conditions during complex scenarios This information helps track how boundary conditions influence cancer cell behavior and microenvironmental evolution during simulation.
Definition at line 1258 of file Microambiente.cpp.
References vector_activacion_dirichlet.
indice_de_voxel()
int Microambiente::indice_de_voxel (int i, int j, int k)
Converts 3D Cartesian indices to a voxel index.
Converts 3D cartesian indices to a linear voxel index.
Parameters
i x-index
j y-index
k z-index
Returns
Voxel index
Parameters
i x-axis index
j y-axis index
k z-axis index
Returns
int Linear voxel index
This method maps 3D coordinates in the grid to a single linear index for accessing the voxel data.
Cancer Research Context: Efficient spatial indexing is essential for modeling how cancer cells interact with their local environment. This method facilitates:
Tracking cell positions relative to nutrient/oxygen sources
Modeling cell-cell and cell-matrix interactions in 3D space
Analyzing spatial patterns of cancer growth and invasion
Simulating spatially-targeted therapeutic interventions
Definition at line 460 of file Microambiente.cpp.
References Grillado_Cartesiano::indice_de_voxel(), and mgrilla.
Referenced by actualizar_nodo_de_dirichlet(), agregar_nodo_de_dirichlet(), es_nodo_de_dirichlet(), vector_de_densidades_mas_cercano(), and voxeles().
indice_del_voxel_mas_cercano()
int Microambiente::indice_del_voxel_mas_cercano (Vector & posicion)
Finds the voxel index closest to a given position.
Finds the index of the voxel closest to a given position.
Parameters
posicion 3D position
Returns
Closest voxel index
Parameters
posicion 3D vector representing a spatial position
Returns
int Index of the nearest voxel
This method finds the voxel that contains or is closest to a specified spatial position.
Cancer Research Context: Finding the nearest voxel is essential for:
Determining local substrate concentrations around a cancer cell
Modeling how cells interact with their immediate microenvironment
Simulating cellular responses to local biochemical conditions
Tracking cell migration through varying environmental gradients
Definition at line 525 of file Microambiente.cpp.
References Grillado_Cartesiano::indice_del_voxel_mas_cercano(), and mgrilla.
Referenced by Celula::actualizar_voxel_del_microambiente(), crear_vaso_sanguineo(), and vector_de_gradiente_mas_cercano().
indices_cartesianos()
std::vector< unsigned int > Microambiente::indices_cartesianos (int n)
Converts a linear voxel index to 3D cartesian indices.
Parameters
n Linear voxel index
Returns
std::vector<unsigned int> Vector of cartesian indices (i,j,k)
This method is the inverse of indice_de_voxel, converting a linear index back to 3D coordinates.
Cancer Research Context: Converting between linear and 3D indices enables:
Analysis of spatial patterns in tumor growth
Identification of microenvironmental niches in specific regions
Mapping of metabolic or phenotypic gradients across the tumor
Correlation of molecular data with spatial location in the tumor
Definition at line 503 of file Microambiente.cpp.
References Grillado_Cartesiano::indices_cartesianos(), and mgrilla.
Referenced by calcular_vector_de_gradiente().
indices_cartesianos_mas_cercanos()
Vector Microambiente::indices_cartesianos_mas_cercanos (Vector & posicion)
Gets Cartesian indices closest to a position.
Gets the cartesian indices of the voxel closest to a position.
Parameters
posicion 3D position
Returns
Vector containing the closest i,j,k indices
Parameters
posicion 3D vector representing a spatial position
Returns
Vector Vector containing the nearest voxel's (i,j,k) indices
This method returns the 3D coordinates of the voxel closest to a given position.
Cancer Research Context: This method supports spatial analysis of:
Cancer cell positions relative to vascular structures
Cell proximity to tissue boundaries or other structures
Local density of cells in specific tumor regions
Spatial correlation between cell phenotypes and microenvironmental features
Definition at line 546 of file Microambiente.cpp.
References Grillado_Cartesiano::indices_cartesianos_mas_cercanos(), and mgrilla.
inicializar_microambiente()
void Microambiente::inicializar_microambiente ()
Initializes the microenvironment with default settings.
Initializes the microenvironment with parameters from global settings.
Sets up the microenvironment based on global parameter settings, including substrate types, domain size, boundary conditions, and initial concentrations. By default, configures oxygen as the first substrate if specified.
Cancer Research Context: Proper initialization of the microenvironment is essential for cancer simulation, as it establishes the biochemical landscape that influences tumor growth. Oxygen is typically set as the primary substrate due to its critical role in tumor metabolism, with values calibrated to physiological levels (38 mmHg). The option to include immune factors enables modeling of cancer-immune interactions.
Definition at line 1586 of file Microambiente.cpp.
References Parametros_globales::activar_respuesta_inmune, agregar_densidad(), agregar_nodo_de_dirichlet(), coeficientes_de_difusion, Parametros_globales::condiciones_de_Dirichlet_externas, Grillado_Cartesiano::coordenadas_x, Grillado_Cartesiano::coordenadas_y, Grillado_Cartesiano::coordenadas_z, Parametros_globales::dirichlet_todo, Parametros_globales::dirichlet_xmax, Parametros_globales::dirichlet_xmax_valores, Parametros_globales::dirichlet_xmin, Parametros_globales::dirichlet_xmin_valores, Parametros_globales::dirichlet_ymax, Parametros_globales::dirichlet_ymax_valores, Parametros_globales::dirichlet_ymin, Parametros_globales::dirichlet_ymin_valores, Parametros_globales::dirichlet_zmax, Parametros_globales::dirichlet_zmax_valores, Parametros_globales::dirichlet_zmin, Parametros_globales::dirichlet_zmin_valores, fg_indice_de_voxel, Parametros_globales::m_dx, Parametros_globales::m_dy, Parametros_globales::m_dz, Parametros_globales::m_nombre, mgrilla, mostrar_informacion(), nombre, numero_de_densidades(), numero_de_voxeles(), pg, Parametros_globales::rango_en_X, Parametros_globales::rango_en_Y, Parametros_globales::rango_en_Z, redimensionar_espacio(), set_activacion_de_sustrato_de_dirichlet(), set_densidad(), tasas_de_decaimiento, Grillado_General::unidades, unidades_espaciales, Parametros_globales::unidades_espaciales, unidades_temporales, Parametros_globales::unidades_temporales, Parametros_globales::usar_oxigeno_como_primer_sustrato, vector_activacion_dirichlet, Parametros_globales::vector_activacion_dirichlet, Parametros_globales::vector_condicion_de_dirichlet, Parametros_globales::vector_condiciones_iniciales, and vector_de_densidades().
Referenced by Tejido::inicializar_tejido().
mostrar_informacion()
void Microambiente::mostrar_informacion (std::ostream & os)
Outputs information about the microenvironment.
Displays detailed information about the microenvironment configuration.
Parameters
os Output stream
os Output stream where information will be written
Cancer Research Context: Provides comprehensive information about the microenvironment setup, including diffusion lengths, which are critical for understanding how far oxygen and nutrients can penetrate into tumor tissue. This helps researchers interpret simulation results in the context of known tumor biology, where oxygen diffusion typically limits to 100-200 microns from blood vessels.
Definition at line 1537 of file Microambiente.cpp.
References coeficientes_de_difusion, densidades_nombres, densidades_unidades, mgrilla, Grillado_Cartesiano::mostrar_informacion_cartesiano(), nombre, numero_de_densidades(), pg, tasas_de_decaimiento, unidades_espaciales, unidades_temporales, vector_activacion_dirichlet, Parametros_globales::vector_condicion_de_dirichlet, and Parametros_globales::vector_condiciones_iniciales.
Referenced by inicializar_microambiente().
numero_de_densidades()
unsigned int Microambiente::numero_de_densidades (void)
Gets the number of tracked densities/substrates.
Returns
Number of densities
Definition at line 163 of file Microambiente.cpp.
References p_vectores_densidad.
Referenced by agregar_densidad(), calcular_todos_los_vectores_de_gradientes(), calcular_vector_de_gradiente(), inicializar_microambiente(), Microambiente(), mostrar_informacion(), redimensionar_densidades(), redimensionar_espacio(), and resetear_todos_los_vectores_de_gradientes().
numero_de_voxeles()
unsigned int Microambiente::numero_de_voxeles (void)
Gets the total number of voxels in the domain.
Returns
Number of voxels
Definition at line 168 of file Microambiente.cpp.
References mgrilla, and Grillado_General::voxeles.
Referenced by inicializar_microambiente().
operator()() [1/2]
std::vector<double>& Microambiente::operator() (int i, int j, int k)
acceder al vector de densidades en [ X(i),Y(j),Z(k) ]
operator()() [2/2]
std::vector< double > & Microambiente::operator() (int n)
Operator overload for direct access to density vectors by voxel index.
acceder al vector de densidades en el voxel (n)
Parameters
n Index of the voxel to return density vector for
Returns
std::vector<double>& Reference to the density vector at the specified voxel
Cancer Research Context: Provides convenient syntax for accessing substrate concentrations throughout the tumor microenvironment. This operator simplifies code for analyzing spatial patterns of nutrients, oxygen, and signaling molecules that affect cancer cell behavior and tumor progression.
Definition at line 643 of file Microambiente.cpp.
References p_vectores_densidad.
redimensionar_densidades()
void Microambiente::redimensionar_densidades (int nuevo_tamano)
Resizes the number of tracked densities/substrates.
Resizes the density vectors for all substrates in the microenvironment.
Parameters
nuevo_tamano New number of densities
nuevo_tamano New size for density vectors
This method resizes all data structures related to substrate densities when the number of substrates changes.
Cancer Research Context: The ability to model multiple substrates simultaneously is critical for cancer research as it allows simulation of:
Oxygen and nutrient gradients that drive metabolic adaptations in cancer cells
Signaling molecules that affect cancer cell phenotype and behavior
Drug distributions for treatment response modeling
Waste product accumulation that creates acidic microenvironments Each substrate can have unique diffusion and decay properties, enabling realistic modeling of the complex biochemical landscape that influences cancer progression.
Definition at line 242 of file Microambiente.cpp.
References cero, coeficientes_de_difusion, densidades_nombres, densidades_unidades, Parametros_globales::dirichlet_todo, dirichlet_vectorES_activacion, Parametros_globales::dirichlet_vs, Parametros_globales::dirichlet_xmax, Parametros_globales::dirichlet_xmax_valores, Parametros_globales::dirichlet_xmin, Parametros_globales::dirichlet_xmin_valores, Parametros_globales::dirichlet_ymax, Parametros_globales::dirichlet_ymax_valores, Parametros_globales::dirichlet_ymin, Parametros_globales::dirichlet_ymin_valores, Parametros_globales::dirichlet_zmax, Parametros_globales::dirichlet_zmax_valores, Parametros_globales::dirichlet_zmin, Parametros_globales::dirichlet_zmin_valores, mgrilla, numero_de_densidades(), pg, tasas_de_decaimiento, temp_vectores_densidad1, temp_vectores_densidad2, un_medio, un_tercio, uno, vector_activacion_dirichlet, Parametros_globales::vector_activacion_dirichlet, Parametros_globales::vector_condicion_de_dirichlet, Parametros_globales::vector_condiciones_iniciales, vector_gradiente_calculado, vector_valores_de_dirichlet, vectores_gradiente, and Grillado_General::voxeles.
redimensionar_espacio()
void Microambiente::redimensionar_espacio (double x_ini, double x_fin, double y_ini, double y_fin, double z_ini, double z_fin, double dx_nuevo, double dy_nuevo, double dz_nuevo)
Resizes the spatial domain of the microenvironment.
Resizes the microenvironment's spatial domain.
Parameters
x_ini Initial x coordinate
x_fin Final x coordinate
y_ini Initial y coordinate
y_fin Final y coordinate
z_ini Initial z coordinate
z_fin Final z coordinate
dx_nuevo New x spacing
dy_nuevo New y spacing
dz_nuevo New z spacing
x_ini Initial x-coordinate of the domain
x_fin Final x-coordinate of the domain
y_ini Initial y-coordinate of the domain
y_fin Final y-coordinate of the domain
z_ini Initial z-coordinate of the domain
z_fin Final z-coordinate of the domain
dx_nuevo New voxel size in x-direction
dy_nuevo New voxel size in y-direction
dz_nuevo New voxel size in z-direction
This method resizes the spatial domain of the microenvironment and reinitializes all data structures that depend on the spatial discretization.
Cancer Research Context: The spatial domain configuration is crucial for simulating realistic tumor microenvironments. Proper dimensioning allows for accurate representation of:
Tumor boundaries and invasion zones
Heterogeneous regions with varying substrate concentrations
Local microenvironmental niches that drive cancer cell adaptations The spatial resolution (voxel size) directly impacts the fidelity of diffusion gradient modeling, which is essential for simulating hypoxia-driven malignant progression.
Definition at line 199 of file Microambiente.cpp.
References cero, dirichlet_vectorES_activacion, mgrilla, numero_de_densidades(), Grillado_Cartesiano::redimensionar(), temp_vectores_densidad1, temp_vectores_densidad2, uno, vector_activacion_dirichlet, vector_gradiente_calculado, vector_valores_de_dirichlet, vectores_gradiente, and Grillado_General::voxeles.
Referenced by inicializar_microambiente().
remover_nodo_de_dirichlet()
void Microambiente::remover_nodo_de_dirichlet (int indice_de_voxel)
Removes a Dirichlet node.
Parameters
indice_de_voxel Voxel index
resetear_todos_los_vectores_de_gradientes()
void Microambiente::resetear_todos_los_vectores_de_gradientes (void)
Resets all gradient calculations.
Resets all gradient vectors, marking them as not calculated.
Cancer Research Context: This method is important when the microenvironment has changed significantly (due to diffusion, cellular consumption, or secretion), requiring gradients to be recalculated. This ensures that:
Cancer cell responses to gradients are based on current conditions
Simulations accurately reflect dynamic changes in the tumor microenvironment
Computational resources are used efficiently by only calculating gradients when needed
This is particularly important after diffusion steps or when modeling rapid changes in the tumor microenvironment such as acute hypoxia, drug delivery, or vascular disruption.
Definition at line 1019 of file Microambiente.cpp.
References mgrilla, numero_de_densidades(), vector_gradiente_calculado, vectores_gradiente, and Grillado_General::voxeles.
set_activacion_de_sustrato_de_dirichlet() [1/3]
void Microambiente::set_activacion_de_sustrato_de_dirichlet (int indice, std::vector< bool > & nuevo_valor)
Sets activation status for all substrates at a voxel.
Sets the activation state of all substrates at a specific Dirichlet node.
Parameters
indice Voxel index
nuevo_valor Vector of activation statuses
indice Index of the Dirichlet node
nuevo_valor Vector of activation states for all substrates
Cancer Research Context: This method allows for comprehensive control of all substrates at a specific boundary location, which is important for modeling:
Blood vessels with specific permeability profiles
Tissue interfaces with selective transport properties
Experimental boundary conditions with controlled substrate availability This comprehensive control enables realistic simulation of complex boundary conditions that affect multiple aspects of the tumor microenvironment simultaneously.
Definition at line 1235 of file Microambiente.cpp.
References dirichlet_vectorES_activacion.
set_activacion_de_sustrato_de_dirichlet() [2/3]
void Microambiente::set_activacion_de_sustrato_de_dirichlet (int indice_de_sustrato, bool nuevo_valor)
Sets activation status for a substrate's Dirichlet condition.
Sets the activation state of a substrate at all Dirichlet nodes.
Parameters
indice_de_sustrato Substrate index
nuevo_valor New activation status
indice_de_sustrato Index of the substrate to set activation for
nuevo_valor New activation state (true = active, false = inactive)
Cancer Research Context: This method enables global control over whether specific substrates are maintained at fixed concentrations at boundary points. This is important for modeling:
Selective permeability of tumor vasculature to different molecules
Changes in availability of specific nutrients or drugs
Experimental conditions where certain factors are controlled This control is essential for studying how specific microenvironmental factors influence tumor growth, invasion, and response to therapy.
Definition at line 1187 of file Microambiente.cpp.
References dirichlet_vectorES_activacion, mgrilla, vector_activacion_dirichlet, and Grillado_General::voxeles.
Referenced by crear_vaso_sanguineo(), and inicializar_microambiente().
set_activacion_de_sustrato_de_dirichlet() [3/3]
void Microambiente::set_activacion_de_sustrato_de_dirichlet (int indice_de_sustrato, int indice, bool nuevo_valor)
Sets activation status for a substrate at a specific voxel.
Sets the activation state of a substrate at a specific Dirichlet node.
Parameters
indice_de_sustrato Substrate index
indice Voxel index
nuevo_valor New activation status
indice_de_sustrato Index of the substrate to set activation for
indice Index of the Dirichlet node
nuevo_valor New activation state (true = active, false = inactive)
Cancer Research Context: This method provides localized control over boundary conditions for specific substrates at specific locations. This is crucial for modeling:
Heterogeneous vascular permeability within tumors
Localized drug delivery or metabolite sources
Spatial variations in tissue-tumor interfaces This spatial control allows for more realistic modeling of the heterogeneous tumor microenvironment that influences cancer progression and treatment response.
Definition at line 1213 of file Microambiente.cpp.
References dirichlet_vectorES_activacion.
set_densidad() [1/2]
void Microambiente::set_densidad (int indice, std::string nombre, std::string unidades)
Sets name and units for an existing density/substrate.
Parameters
indice Index of the density
nombre Name of the density
unidades Units of the density
Definition at line 422 of file Microambiente.cpp.
References densidades_nombres, densidades_unidades, nombre, pg, and Parametros_globales::usar_oxigeno_como_primer_sustrato.
set_densidad() [2/2]
void Microambiente::set_densidad (int indice, std::string nombre, std::string unidades, double coeficiente_de_difusion, double tasa_de_decaimiento)
Sets properties for an existing density/substrate.
Sets properties for an existing substrate at the specified index.
Parameters
indice Index of the density
nombre Name of the density
unidades Units of the density
coeficiente_de_difusion Diffusion coefficient
tasa_de_decaimiento Decay rate
indice Index of the substrate to modify
nombre Name of the substrate
unidades Units of measurement for the substrate
coeficiente_de_difusion Diffusion coefficient of the substrate
tasa_de_decaimiento Decay rate of the substrate
Cancer Research Context: This method allows configuring specific substrates with properties that match experimental measurements. For example, setting oxygen with appropriate diffusion coefficients (1e5 m/min) and consumption rates (0.1/min) creates realistic oxygen gradients observed in tumors. These correctly calibrated parameters are essential for accurately modeling hypoxic regions and their effects on cancer cell behavior.
Definition at line 406 of file Microambiente.cpp.
References coeficientes_de_difusion, densidades_nombres, densidades_unidades, nombre, pg, tasas_de_decaimiento, and Parametros_globales::usar_oxigeno_como_primer_sustrato.
Referenced by inicializar_microambiente().
simular_difusion_decaimiento()
void Microambiente::simular_difusion_decaimiento (double dt)
Simulates diffusion and decay of substrates.
Simulates diffusion and decay of all substrates for one time step.
Parameters
dt Time step
dt Time step size for the simulation
Cancer Research Context: This method is central to modeling the tumor microenvironment dynamics by simulating how biochemical factors (oxygen, nutrients, signaling molecules) diffuse through the tissue and decay over time. These processes create the spatial gradients that:
Drive hypoxic adaptation in cancer cells
Create metabolically distinct regions within tumors
Influence cancer cell migration and invasion patterns
Affect drug delivery and efficacy in different tumor regions
The method uses a locally one-dimensional (LOD) scheme for 3D diffusion-reaction equations, which is computationally efficient for modeling complex tumor microenvironments.
Definition at line 1054 of file Microambiente.cpp.
References solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
Referenced by main().
simular_suministro_y_consumo_de_las_celulas()
void Microambiente::simular_suministro_y_consumo_de_las_celulas (double dt)
Simulates cell-based supply and consumption.
Parameters
dt Time step
simular_suministro_y_consumo_del_bulk()
void Microambiente::simular_suministro_y_consumo_del_bulk (double dt)
Simulates bulk supply and consumption.
Parameters
dt Time step
solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D()
void Microambiente::solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D (double dt)
Solver for diffusion-decay using LOD (Locally One-Dimensional) method.
Implements a locally one-dimensional (LOD) 3D diffusion-reaction solver.
Parameters
dt Time step
dt Time step size for the simulation
Cancer Research Context: This method is the core numerical implementation for simulating how biochemical factors diffuse and decay within the tumor microenvironment. It is critical for modeling:
Oxygen gradients that drive cancer cell hypoxic adaptation
Nutrient distribution that affects cancer cell metabolism and proliferation
Drug penetration through tumor tissue for treatment efficacy studies
Signaling molecule gradients that influence cancer cell phenotypes
The method implements a computationally efficient LOD (Alternating Direction Implicit) approach that solves the diffusion equation sequentially along each spatial dimension. This enables realistic 3D modeling of complex biochemical gradients that are known to significantly influence tumor progression, invasion, and treatment response.
Definition at line 1301 of file Microambiente.cpp.
References aplicar_condiciones_de_dirichlet(), axpy(), cero, coeficientes_de_difusion, Grillado_Cartesiano::coordenadas_x, Grillado_Cartesiano::coordenadas_y, Grillado_Cartesiano::coordenadas_z, Grillado_Cartesiano::dx, fg_indice_de_voxel, mgrilla, setup_del_solver_de_difusion_hecho, tasas_de_decaimiento, thomas_constante1, thomas_constante1a, thomas_constante2, thomas_constante3, thomas_constante3a, thomas_cx, thomas_cy, thomas_cz, thomas_denomx, thomas_denomy, thomas_denomz, thomas_salto_en_i, thomas_salto_en_j, thomas_salto_en_k, and uno.
Referenced by simular_difusion_decaimiento().
vector_de_densidades() [1/2]
std::vector<double>& Microambiente::vector_de_densidades (int i, int j, int k)
acceder al vector de densidades en [ X(i),Y(j),Z(k) ]
Referenced by aplicar_condiciones_de_dirichlet(), inicializar_microambiente(), and Celula::registrar_microambiente().
vector_de_densidades() [2/2]
std::vector< double > & Microambiente::vector_de_densidades (int n)
Returns the density vector at the specified voxel index.
acceder al vector de densidades en el voxel (n)
Parameters
n Index of the voxel to return density vector for
Returns
std::vector<double>& Reference to the density vector at the specified voxel
Cancer Research Context: This method provides direct access to substrate concentrations at specific locations within the tumor microenvironment. Accessing density vectors is crucial for analyzing how biochemical factors like oxygen, nutrients, and signaling molecules influence cancer cell behavior, metabolism, and phenotypic adaptations at different spatial locations. These substrate distributions drive tumor heterogeneity and influence treatment response.
Definition at line 663 of file Microambiente.cpp.
References p_vectores_densidad.
vector_de_densidades_mas_cercano() [1/2]
std::vector< double > & Microambiente::vector_de_densidades_mas_cercano (int indice_de_voxel)
Returns the density vector at the specified voxel index.
Parameters
indice_de_voxel Index of the voxel to return density vector for
Returns
std::vector<double>& Reference to the density vector at the specified voxel
Cancer Research Context: Provides direct access to substrate concentrations at specific locations within the tumor microenvironment. This allows for analyzing spatial heterogeneity in biochemical components that drive cancer cell behavior, metabolism, and phenotypic adaptation.
Definition at line 624 of file Microambiente.cpp.
References indice_de_voxel(), and p_vectores_densidad.
vector_de_densidades_mas_cercano() [2/2]
std::vector< double > & Microambiente::vector_de_densidades_mas_cercano (Vector & posicion)
Returns the density vector of the voxel closest to the given position.
Parameters
posicion 3D spatial position to find nearest voxel
Returns
std::vector<double>& Reference to the density vector at the nearest voxel
Cancer Research Context: This method enables sampling of biochemical components (oxygen, nutrients, etc.) at specific spatial positions, allowing cancer cells to sense and respond to their local microenvironment. This is crucial for modeling how cancer cells adapt to gradients of nutrients, oxygen, and signaling molecules within the tumor.
Definition at line 606 of file Microambiente.cpp.
References Grillado_Cartesiano::indice_del_voxel_mas_cercano(), mgrilla, and p_vectores_densidad.
Referenced by Celula::vector_de_densidades_mas_cercano().
vector_de_gradiente_mas_cercano()
std::vector< gradiente > & Microambiente::vector_de_gradiente_mas_cercano (Vector & posicion)
Returns the gradient vector of the voxel closest to the given position.
Parameters
posicion 3D spatial position to find nearest voxel
Returns
std::vector<gradiente>& Reference to the gradient vector at the nearest voxel
Cancer Research Context: This method provides convenient access to biochemical gradients at any 3D position, which is essential for modeling how cancer cells sense and respond to their local microenvironment. This enables simulation of:
Directional migration of cancer cells along nutrient or oxygen gradients
Cellular responses to cytokine or growth factor gradients
Invasion patterns driven by chemotactic responses
Adaptation of cancer cells to local concentration changes
Definition at line 738 of file Microambiente.cpp.
References calcular_vector_de_gradiente(), indice_del_voxel_mas_cercano(), vector_gradiente_calculado, and vectores_gradiente.
vector_de_gradientes() [1/2]
std::vector< gradiente > & Microambiente::vector_de_gradientes (int i, int j, int k)
Returns the gradient vector at the specified 3D voxel coordinates.
Parameters
i X-coordinate index
j Y-coordinate index
k Z-coordinate index
Returns
std::vector<gradiente>& Reference to the gradient vector at the specified location
Cancer Research Context: Gradients of biochemical substrates (oxygen, nutrients, signaling molecules) are critical drivers of cancer cell behavior. This method provides access to these gradients for modeling chemotaxis, cellular adaptation, and migration responses. Steep gradients often exist around blood vessels and necrotic regions in tumors, influencing invasion patterns and treatment response.
Definition at line 685 of file Microambiente.cpp.
References calcular_vector_de_gradiente(), fg_indice_de_voxel, vector_gradiente_calculado, and vectores_gradiente.
Referenced by Celula::gradiente_mas_cercano().
vector_de_gradientes() [2/2]
std::vector< gradiente > & Microambiente::vector_de_gradientes (int n)
Returns the gradient vector at the specified voxel index.
Parameters
n Index of the voxel to return gradient vector for
Returns
std::vector<gradiente>& Reference to the gradient vector at the specified voxel
Cancer Research Context: This method enables modeling of directional cellular responses to biochemical gradients, which is essential for simulating cancer cell migration, invasion, and adaptation to the tumor microenvironment. Gradient-driven behaviors are key factors in metastatic potential and treatment resistance in cancer.
Definition at line 709 of file Microambiente.cpp.
References calcular_vector_de_gradiente(), vector_gradiente_calculado, and vectores_gradiente.
voxel_mas_cercano()
Voxel & Microambiente::voxel_mas_cercano (Vector & posicion)
Gets the voxel object closest to a given position.
Parameters
posicion 3D vector representing a spatial position
Returns
Voxel& Reference to the nearest voxel
This method provides direct access to the voxel object nearest to a specified position.
Cancer Research Context: Direct voxel access enables:
Detailed analysis of the microenvironment at specific locations
Modeling cell-microenvironment interactions at cellular scale
Studying how local features affect cancer cell behavior
Simulating how treatments modify the local environment around cells
Definition at line 567 of file Microambiente.cpp.
References mgrilla, and Grillado_Cartesiano::voxel_mas_cercano().
voxeles()
Voxel & Microambiente::voxeles (int indice_de_voxel)
Gets a voxel by its linear index.
Parameters
indice_de_voxel Linear index of the voxel
Returns
Voxel& Reference to the specified voxel
This method provides direct access to a voxel object by its linear index.
Cancer Research Context: Accessing voxels by index allows:
Systematic analysis of the entire tumor microenvironment
Mapping substrate distributions throughout the simulated domain
Identifying regions with specific biochemical signatures
Correlating microenvironmental features with cancer cell phenotypes
Definition at line 588 of file Microambiente.cpp.
References indice_de_voxel(), mgrilla, and Grillado_General::voxeles.
Referenced by Celula::set_constantes_de_consumo_interno().
Member Data Documentation
cero
std::vector<double> Microambiente::cero private
Definition at line 75 of file Microambiente.h.
Referenced by agregar_densidad(), Microambiente(), redimensionar_densidades(), redimensionar_espacio(), and solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
coeficientes_de_difusion
std::vector< double > Microambiente::coeficientes_de_difusion
Definition at line 128 of file Microambiente.h.
Referenced by agregar_densidad(), inicializar_microambiente(), Microambiente(), mostrar_informacion(), redimensionar_densidades(), set_densidad(), and solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
densidades_nombres
std::vector< std::string > Microambiente::densidades_nombres
Definition at line 124 of file Microambiente.h.
Referenced by agregar_densidad(), encontrar_indice_de_densidad(), Microambiente(), mostrar_informacion(), redimensionar_densidades(), and set_densidad().
densidades_objetivo_de_suministro_por_tasas_de_suministro
std::vector< std::vector<double> > Microambiente::densidades_objetivo_de_suministro_por_tasas_de_suministro
Definition at line 131 of file Microambiente.h.
densidades_unidades
std::vector< std::string > Microambiente::densidades_unidades
Definition at line 125 of file Microambiente.h.
Referenced by agregar_densidad(), Microambiente(), mostrar_informacion(), redimensionar_densidades(), and set_densidad().
dirichlet_vectorES_activacion
std::vector< std::vector<bool> > Microambiente::dirichlet_vectorES_activacion private
Definition at line 110 of file Microambiente.h.
Referenced by actualizar_nodo_de_dirichlet(), agregar_densidad(), aplicar_condiciones_de_dirichlet(), Microambiente(), redimensionar_densidades(), redimensionar_espacio(), and set_activacion_de_sustrato_de_dirichlet().
mgrilla
Grillado_Cartesiano Microambiente::mgrilla
Definition at line 116 of file Microambiente.h.
Referenced by actualizar_nodo_de_dirichlet(), Celula::actualizar_voxel_del_microambiente(), agregar_densidad(), agregar_nodo_de_dirichlet(), aplicar_condiciones_de_dirichlet(), calcular_todos_los_vectores_de_gradientes(), calcular_vector_de_gradiente(), centro_del_voxel(), es_nodo_de_dirichlet(), indice_de_voxel(), indice_del_voxel_mas_cercano(), indices_cartesianos(), indices_cartesianos_mas_cercanos(), inicializar_microambiente(), Microambiente(), mostrar_informacion(), numero_de_voxeles(), redimensionar_densidades(), redimensionar_espacio(), resetear_todos_los_vectores_de_gradientes(), set_activacion_de_sustrato_de_dirichlet(), solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D(), vector_de_densidades_mas_cercano(), voxel_mas_cercano(), and voxeles().
nombre
std::string Microambiente::nombre
Definition at line 121 of file Microambiente.h.
Referenced by agregar_densidad(), encontrar_indice_de_densidad(), inicializar_microambiente(), Microambiente(), mostrar_informacion(), and set_densidad().
p_vectores_densidad
std::vector< std::vector<double> >* Microambiente::p_vectores_densidad private
Almacena los punteros a las densidades. Se accede mediante las funciones operador().
Definition at line 67 of file Microambiente.h.
Referenced by Microambiente(), numero_de_densidades(), operator()(), vector_de_densidades(), and vector_de_densidades_mas_cercano().
setup_de_thomas_hecho
bool Microambiente::setup_de_thomas_hecho private
Definition at line 88 of file Microambiente.h.
Referenced by Microambiente().
setup_del_solver_bulk_fuente_sumidero_hecho
bool Microambiente::setup_del_solver_bulk_fuente_sumidero_hecho private
Definition at line 63 of file Microambiente.h.
Referenced by Microambiente().
setup_del_solver_de_difusion_hecho
bool Microambiente::setup_del_solver_de_difusion_hecho private
Definition at line 103 of file Microambiente.h.
Referenced by Microambiente(), and solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
tasas_de_consumo
std::vector< std::vector<double> > Microambiente::tasas_de_consumo
Definition at line 133 of file Microambiente.h.
tasas_de_decaimiento
std::vector< double > Microambiente::tasas_de_decaimiento
Definition at line 129 of file Microambiente.h.
Referenced by agregar_densidad(), inicializar_microambiente(), Microambiente(), mostrar_informacion(), redimensionar_densidades(), set_densidad(), and solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
tasas_de_suministro
std::vector< std::vector<double> > Microambiente::tasas_de_suministro
Definition at line 132 of file Microambiente.h.
temp_bulk_fuente_sumidero_solver1
std::vector< std::vector<double> > Microambiente::temp_bulk_fuente_sumidero_solver1 private
para uso interno en los solvers de fuente/sumidero del bulk
Definition at line 60 of file Microambiente.h.
temp_bulk_fuente_sumidero_solver2
std::vector< std::vector<double> > Microambiente::temp_bulk_fuente_sumidero_solver2 private
Definition at line 61 of file Microambiente.h.
temp_bulk_fuente_sumidero_solver3
std::vector< std::vector<double> > Microambiente::temp_bulk_fuente_sumidero_solver3 private
Definition at line 62 of file Microambiente.h.
temp_vectores_densidad1
std::vector< std::vector<double> > Microambiente::temp_vectores_densidad1 private
Para uso interno y acelerar los solvers
Definition at line 56 of file Microambiente.h.
Referenced by agregar_densidad(), Microambiente(), redimensionar_densidades(), and redimensionar_espacio().
temp_vectores_densidad2
std::vector< std::vector<double> > Microambiente::temp_vectores_densidad2 private
Definition at line 57 of file Microambiente.h.
Referenced by agregar_densidad(), Microambiente(), redimensionar_densidades(), and redimensionar_espacio().
thomas_constante1
std::vector<double> Microambiente::thomas_constante1 private
Definition at line 92 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_constante1a
std::vector<double> Microambiente::thomas_constante1a private
Definition at line 93 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_constante1x
std::vector<double> Microambiente::thomas_constante1x private
Definition at line 82 of file Microambiente.h.
thomas_constante1y
std::vector<double> Microambiente::thomas_constante1y private
Definition at line 83 of file Microambiente.h.
thomas_constante1z
std::vector<double> Microambiente::thomas_constante1z private
Definition at line 84 of file Microambiente.h.
thomas_constante2
std::vector<double> Microambiente::thomas_constante2 private
Definition at line 94 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_constante3
std::vector<double> Microambiente::thomas_constante3 private
Definition at line 95 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_constante3a
std::vector<double> Microambiente::thomas_constante3a private
Definition at line 96 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_cx
std::vector< std::vector<double> > Microambiente::thomas_cx private
Definition at line 98 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_cy
std::vector< std::vector<double> > Microambiente::thomas_cy private
Definition at line 100 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_cz
std::vector< std::vector<double> > Microambiente::thomas_cz private
Definition at line 102 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_denomx
std::vector< std::vector<double> > Microambiente::thomas_denomx private
Definition at line 97 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_denomy
std::vector< std::vector<double> > Microambiente::thomas_denomy private
Definition at line 99 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_denomz
std::vector< std::vector<double> > Microambiente::thomas_denomz private
Definition at line 101 of file Microambiente.h.
Referenced by solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_neg_constante1x
std::vector<double> Microambiente::thomas_neg_constante1x private
Definition at line 85 of file Microambiente.h.
thomas_neg_constante1y
std::vector<double> Microambiente::thomas_neg_constante1y private
Definition at line 86 of file Microambiente.h.
thomas_neg_constante1z
std::vector<double> Microambiente::thomas_neg_constante1z private
Definition at line 87 of file Microambiente.h.
thomas_salto_en_i
int Microambiente::thomas_salto_en_i private
Definition at line 89 of file Microambiente.h.
Referenced by calcular_todos_los_vectores_de_gradientes(), calcular_vector_de_gradiente(), and solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_salto_en_j
int Microambiente::thomas_salto_en_j private
Definition at line 90 of file Microambiente.h.
Referenced by calcular_todos_los_vectores_de_gradientes(), calcular_vector_de_gradiente(), and solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_salto_en_k
int Microambiente::thomas_salto_en_k private
Definition at line 91 of file Microambiente.h.
Referenced by calcular_todos_los_vectores_de_gradientes(), calcular_vector_de_gradiente(), and solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
thomas_temp1
std::vector< std::vector<double> > Microambiente::thomas_temp1 private
Cosas de Thomas para uso interno en los solvers de difucin.
Definition at line 80 of file Microambiente.h.
thomas_temp2
std::vector< std::vector<double> > Microambiente::thomas_temp2 private
Definition at line 81 of file Microambiente.h.
un_medio
std::vector<double> Microambiente::un_medio private
Definition at line 76 of file Microambiente.h.
Referenced by agregar_densidad(), Microambiente(), and redimensionar_densidades().
un_tercio
std::vector<double> Microambiente::un_tercio private
Definition at line 77 of file Microambiente.h.
Referenced by agregar_densidad(), Microambiente(), and redimensionar_densidades().
unidades_espaciales
std::string Microambiente::unidades_espaciales
Definition at line 119 of file Microambiente.h.
Referenced by inicializar_microambiente(), Microambiente(), and mostrar_informacion().
unidades_temporales
std::string Microambiente::unidades_temporales
Definition at line 120 of file Microambiente.h.
Referenced by inicializar_microambiente(), Microambiente(), and mostrar_informacion().
uno
std::vector<double> Microambiente::uno private
tiles para los solvers. Redimensionar cuando se agreguen/saquen sustratos
Definition at line 74 of file Microambiente.h.
Referenced by agregar_densidad(), Microambiente(), redimensionar_densidades(), redimensionar_espacio(), and solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
vector_activacion_dirichlet
std::vector<bool> Microambiente::vector_activacion_dirichlet private
Definition at line 106 of file Microambiente.h.
Referenced by agregar_densidad(), get_activacion_de_sustrato_de_dirichlet(), inicializar_microambiente(), Microambiente(), mostrar_informacion(), redimensionar_densidades(), redimensionar_espacio(), and set_activacion_de_sustrato_de_dirichlet().
vector_gradiente_calculado
std::vector<bool> Microambiente::vector_gradiente_calculado private
Definition at line 70 of file Microambiente.h.
Referenced by agregar_densidad(), calcular_todos_los_vectores_de_gradientes(), calcular_vector_de_gradiente(), Microambiente(), redimensionar_densidades(), redimensionar_espacio(), resetear_todos_los_vectores_de_gradientes(), vector_de_gradiente_mas_cercano(), and vector_de_gradientes().
vector_valores_de_dirichlet
std::vector< std::vector<double> > Microambiente::vector_valores_de_dirichlet private
Definition at line 105 of file Microambiente.h.
Referenced by actualizar_nodo_de_dirichlet(), agregar_densidad(), agregar_nodo_de_dirichlet(), aplicar_condiciones_de_dirichlet(), Microambiente(), redimensionar_densidades(), and redimensionar_espacio().
vectores_gradiente
std::vector< std::vector<gradiente> > Microambiente::vectores_gradiente private
Definition at line 69 of file Microambiente.h.
Referenced by agregar_densidad(), calcular_todos_los_vectores_de_gradientes(), calcular_vector_de_gradiente(), Microambiente(), redimensionar_densidades(), redimensionar_espacio(), resetear_todos_los_vectores_de_gradientes(), vector_de_gradiente_mas_cercano(), and vector_de_gradientes().
voxeles_del_vaso_sanguineo
std::vector<int> Microambiente::voxeles_del_vaso_sanguineo
Definition at line 135 of file Microambiente.h.
Referenced by crear_vaso_sanguineo().
The documentation for this class was generated from the following files:
Microambiente.h
Microambiente.cpp