Cancer Cell Agent Simulation: Vector.cpp File Reference
Vector.cpp File Reference
Archivo de implementación de la clase Vector.
#include "Vector.h"
Functions
std::ostream & operator<< (std::ostream &out, const Vector &v)
Stream output operator for Vector.
Vector operator- (double d, Vector v)
Scalar-vector subtraction operator.
void axpy (Vector *v, double &a, Vector &vv)
Vector axpy operation (y = y + a*x).
void operator+= (std::vector< double > &v1, const std::vector< double > &v2)
Component-wise addition of std::vector<double> containers.
void operator-= (std::vector< double > &v1, const std::vector< double > &v2)
Component-wise subtraction of std::vector<double> containers.
void operator/= (std::vector< double > &v1, const std::vector< double > &v2)
Component-wise division of std::vector<double> containers.
void operator*= (std::vector< double > &v1, const double &a)
Scalar multiplication of std::vector<double>.
void operator*= (std::vector< double > &v1, const std::vector< double > &v2)
Component-wise multiplication of std::vector<double> containers.
void operator/= (std::vector< double > &v1, const double &a)
Scalar division of std::vector<double>.
void axpy (std::vector< double > *y, double &a, std::vector< double > &x)
Vector axpy operation for std::vector<double> (y = y + a*x).
void axpy (std::vector< double > *y, std::vector< double > &a, std::vector< double > &x)
Vector component-wise axpy operation (y = y + a.*x).
void naxpy (std::vector< double > *y, double &a, std::vector< double > &x)
Vector negative axpy operation (y = y - a*x).
void naxpy (std::vector< double > *y, std::vector< double > &a, std::vector< double > &x)
Vector component-wise negative axpy operation (y = y - a.*x).
double norm_squared (const std::vector< double > &v)
Squared norm of a std::vector<double>.
double norm_squared (const Vector &v)
Squared norm of a Vector.
double norma (const Vector &v)
Norm (magnitude) of a Vector.
double norma (const std::vector< double > &v)
Norm (magnitude) of a std::vector<double>.
Detailed Description
Archivo de implementación de la clase Vector.
Author
Luciana Melina Luque
Implementation of vector mathematics operations critical for 3D spatial calculations in cancer simulations. These operations provide the foundation for representing cell positions, mechanical interactions, movement, and microenvironmental gradients.
In cancer research, these vector operations enable:
Precise tracking of tumor cell positions and movements in tissue
Calculation of mechanical forces between cells that drive tumor morphology
Representation of biochemical gradients that influence cell migration
Quantification of spatial characteristics within the tumor microenvironment
Inbound Dependencies: Vector.h
Outbound Dependencies: Used by mechanical interaction, cell movement, and gradient calculations
@license: Open Access - Creative Commons Attribution 4.0 International License (http://creativecommons.org/licenses/by/4.0/)
Definition in file Vector.cpp.
Function Documentation
axpy() [1/3]
void axpy (std::vector< double > * y, double & a, std::vector< double > & x)
Vector axpy operation for std::vector<double> (y = y + a*x).
Parameters
y Pointer to vector to be modified
a Scalar multiplier
x Vector to be scaled and added
Performs the operation y = y + a*x in place for substrate vectors, essential in diffusion solvers and biochemical reaction calculations in tumor microenvironment modeling.
Definition at line 456 of file Vector.cpp.
axpy() [2/3]
void axpy (std::vector< double > * y, std::vector< double > & a, std::vector< double > & x)
Vector component-wise axpy operation (y = y + a.*x).
Parameters
y Pointer to vector to be modified
a Vector of multipliers
x Vector to be scaled and added
Performs the operation y = y + a.*x in place (element-wise multiplication), used for complex substrate interaction calculations in tumor microenvironment models where each component has a different scaling factor.
Definition at line 475 of file Vector.cpp.
axpy() [3/3]
void axpy (Vector * v, double & a, Vector & vv)
Vector axpy operation (y = y + a*x).
Parameters
v Pointer to y vector to be modified
a Scalar multiplier
vv x vector to be scaled and added
Performs the operation y = y + a*x in place, a common operation in numerical methods for diffusion, mechanics, and cell movement calculations in cancer models.
Definition at line 330 of file Vector.cpp.
Referenced by Linfocito::actualizar_vector_de_motilidad(), Celula::agregar_potenciales_mb_2(), Linfocito::avanzar_linfocito(), Celula::set_constantes_de_consumo_interno(), and Microambiente::solver_decaimiento_de_la_difusion__coeficientes_constantes_LOD_3D().
naxpy() [1/2]
void naxpy (std::vector< double > * y, double & a, std::vector< double > & x)
Vector negative axpy operation (y = y - a*x).
Parameters
y Pointer to vector to be modified
a Scalar multiplier
x Vector to be scaled and subtracted
Performs the operation y = y - a*x in place, used in diffusion solvers and substrate consumption calculations when modeling cancer cell metabolism.
Definition at line 493 of file Vector.cpp.
naxpy() [2/2]
void naxpy (std::vector< double > * y, std::vector< double > & a, std::vector< double > & x)
Vector component-wise negative axpy operation (y = y - a.*x).
Parameters
y Pointer to vector to be modified
a Vector of multipliers
x Vector to be scaled and subtracted
Performs the operation y = y - a.*x in place (element-wise multiplication), used for modeling differential consumption of multiple substrates in tumor metabolism with varying consumption rates.
Definition at line 512 of file Vector.cpp.
norm_squared() [1/2]
double norm_squared (const std::vector< double > & v)
Squared norm of a std::vector<double>.
Parameters
v Vector to calculate squared norm
Returns
The squared magnitude of the vector
Calculates the sum of squares of elements, used for efficient distance calculations and convergence testing in cancer simulation algorithms without the computational cost of a square root operation.
Definition at line 530 of file Vector.cpp.
References v.
Referenced by Tejido::geometria_del_tumor(), Tejido::introducir_linfocitos(), Tejido::introducir_linfocitos_aleatorios(), and norma().
norm_squared() [2/2]
double norm_squared (const Vector & v)
Squared norm of a Vector.
Parameters
v Vector to calculate squared norm
Returns
The squared magnitude of the vector
Calculates the squared length of the vector, used for efficient distance calculations between cells when the exact magnitude isn't required, reducing computational cost in tumor simulations.
Definition at line 547 of file Vector.cpp.
References v, Vector::x, Vector::y, and Vector::z.
norma() [1/2]
double norma (const std::vector< double > & v)
Norm (magnitude) of a std::vector<double>.
Parameters
v Vector to calculate norm
Returns
The magnitude of the vector
Calculates the Euclidean norm, used for measuring distances between substrate states or determining gradient magnitudes in tumor microenvironment modeling.
Definition at line 581 of file Vector.cpp.
References norm_squared(), and v.
norma() [2/2]
double norma (const Vector & v)
Norm (magnitude) of a Vector.
Parameters
v Vector to calculate norm
Returns
The magnitude of the vector
Calculates the length of the vector, used for measuring exact distances between cells or determining the strength of forces in cancer simulations.
Definition at line 566 of file Vector.cpp.
References norm_squared(), and v.
Referenced by Linfocito::intentar_adherirse().
operator*=() [1/2]
void operator*= (std::vector< double > & v1, const double & a)
Scalar multiplication of std::vector<double>.
Parameters
v1 Vector to be scaled in place (v1 = v1 * a)
a Scalar multiplier
Multiplies each element by a scalar, used for scaling substrate concentrations or adjusting diffusion coefficients in cancer simulations.
Definition at line 408 of file Vector.cpp.
operator*=() [2/2]
void operator*= (std::vector< double > & v1, const std::vector< double > & v2)
Component-wise multiplication of std::vector<double> containers.
Parameters
v1 First vector, modified in place (v1 = v1 * v2)
v2 Second vector to multiply with
Multiplies two std::vector containers element-wise, used for combining factors that have multiplicative effects in cancer biology, such as reaction rates or synergistic factors.
Definition at line 424 of file Vector.cpp.
operator+=()
void operator+= (std::vector< double > & v1, const std::vector< double > & v2)
Component-wise addition of std::vector<double> containers.
Parameters
v1 First vector, modified in place (v1 = v1 + v2)
v2 Second vector to add
Adds two std::vector containers element-wise, used for operating on substrate concentration vectors in tumor microenvironment calculations.
Definition at line 361 of file Vector.cpp.
operator-()
Vector operator- (double d, Vector v)
Scalar-vector subtraction operator.
Parameters
d Scalar value
v Vector to subtract
Returns
Result vector of d-v
Computes d-v element-wise, used in specialized micro-environment calculations and boundary condition implementations for tumor models.
Definition at line 312 of file Vector.cpp.
operator-=()
void operator-= (std::vector< double > & v1, const std::vector< double > & v2)
Component-wise subtraction of std::vector<double> containers.
Parameters
v1 First vector, modified in place (v1 = v1 - v2)
v2 Second vector to subtract
Subtracts two std::vector containers element-wise, used for calculating changes in substrate concentrations over time in tumor growth simulations.
Definition at line 377 of file Vector.cpp.
operator/=() [1/2]
void operator/= (std::vector< double > & v1, const double & a)
Scalar division of std::vector<double>.
Parameters
v1 Vector to be divided in place (v1 = v1 / a)
a Scalar divisor
Divides each element by a scalar, used for normalizing substrate concentrations or calculating relative values in cancer simulations.
Definition at line 439 of file Vector.cpp.
operator/=() [2/2]
void operator/= (std::vector< double > & v1, const std::vector< double > & v2)
Component-wise division of std::vector<double> containers.
Parameters
v1 First vector, modified in place (v1 = v1 / v2)
v2 Second vector as divisor
Divides two std::vector containers element-wise, used for normalizing substrate concentrations or calculating ratios of different biochemical factors in cancer modeling.
Definition at line 393 of file Vector.cpp.
operator<<()
std::ostream& operator<< (std::ostream & out, const Vector & v)
Stream output operator for Vector.
Parameters
out Output stream
v Vector to output
Returns
Modified output stream
Enables printing vector data in a readable format, useful for debugging and visualization of cell positions, forces, or other spatial properties in cancer simulation outputs.
Definition at line 294 of file Vector.cpp.